/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.4
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Document,
  HTTPValidationError,
  ListClientDocumentsParams,
  PaginatedResponseDocument
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListClientDocumentsUrl = (params?: ListClientDocumentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/documents?${stringifiedParams}` : `/v1/documents`
}

/**
 * 获取已发布文档列表（客户端）
 * @summary List Published Documents
 */
export const listClientDocuments = async (params?: ListClientDocumentsParams, options?: RequestInit): Promise<PaginatedResponseDocument | null> => {

  return customFetch<PaginatedResponseDocument | null>(getListClientDocumentsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListClientDocumentsQueryKey = (params?: ListClientDocumentsParams,) => {
    return [
    `/v1/documents`, ...(params ? [params] : [])
    ] as const;
    }


export const getListClientDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof listClientDocuments>>, TError = HTTPValidationError>(params?: ListClientDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientDocuments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListClientDocumentsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listClientDocuments>>> = ({ signal }) => listClientDocuments(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listClientDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListClientDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listClientDocuments>>>
export type ListClientDocumentsQueryError = HTTPValidationError


export function useListClientDocuments<TData = Awaited<ReturnType<typeof listClientDocuments>>, TError = HTTPValidationError>(
 params: undefined |  ListClientDocumentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClientDocuments>>,
          TError,
          Awaited<ReturnType<typeof listClientDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListClientDocuments<TData = Awaited<ReturnType<typeof listClientDocuments>>, TError = HTTPValidationError>(
 params?: ListClientDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClientDocuments>>,
          TError,
          Awaited<ReturnType<typeof listClientDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListClientDocuments<TData = Awaited<ReturnType<typeof listClientDocuments>>, TError = HTTPValidationError>(
 params?: ListClientDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientDocuments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Published Documents
 */

export function useListClientDocuments<TData = Awaited<ReturnType<typeof listClientDocuments>>, TError = HTTPValidationError>(
 params?: ListClientDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientDocuments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListClientDocumentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetClientDocumentUrl = (documentId: number,) => {




  return `/v1/documents/${documentId}`
}

/**
 * 获取文档详情（客户端，自动增加浏览量并记录浏览事件）
 * @summary Get Document
 */
export const getClientDocument = async (documentId: number, options?: RequestInit): Promise<Document | null> => {

  return customFetch<Document | null>(getGetClientDocumentUrl(documentId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClientDocumentQueryKey = (documentId: number,) => {
    return [
    `/v1/documents/${documentId}`
    ] as const;
    }


export const getGetClientDocumentQueryOptions = <TData = Awaited<ReturnType<typeof getClientDocument>>, TError = HTTPValidationError>(documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientDocument>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientDocumentQueryKey(documentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientDocument>>> = ({ signal }) => getClientDocument(documentId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: documentId !== null && documentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientDocument>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof getClientDocument>>>
export type GetClientDocumentQueryError = HTTPValidationError


export function useGetClientDocument<TData = Awaited<ReturnType<typeof getClientDocument>>, TError = HTTPValidationError>(
 documentId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientDocument>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientDocument>>,
          TError,
          Awaited<ReturnType<typeof getClientDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientDocument<TData = Awaited<ReturnType<typeof getClientDocument>>, TError = HTTPValidationError>(
 documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientDocument>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientDocument>>,
          TError,
          Awaited<ReturnType<typeof getClientDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientDocument<TData = Awaited<ReturnType<typeof getClientDocument>>, TError = HTTPValidationError>(
 documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientDocument>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document
 */

export function useGetClientDocument<TData = Awaited<ReturnType<typeof getClientDocument>>, TError = HTTPValidationError>(
 documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientDocument>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientDocumentQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






