/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.6
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetClientFileInfo200,
  GetClientPresignedUrl200,
  GetClientPresignedUrlParams,
  HTTPValidationError
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getDownloadClientFileUrl = (objectName: string,) => {




  return `/v1/files/${objectName}:download`
}

/**
 * 下载文件（客户端）
 * @summary Download File
 */
export const downloadClientFile = async (objectName: string, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getDownloadClientFileUrl(objectName),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDownloadClientFileQueryKey = (objectName: string,) => {
    return [
    `/v1/files/${objectName}:download`
    ] as const;
    }


export const getDownloadClientFileQueryOptions = <TData = Awaited<ReturnType<typeof downloadClientFile>>, TError = HTTPValidationError>(objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadClientFile>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadClientFileQueryKey(objectName);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadClientFile>>> = ({ signal }) => downloadClientFile(objectName, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadClientFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadClientFileQueryResult = NonNullable<Awaited<ReturnType<typeof downloadClientFile>>>
export type DownloadClientFileQueryError = HTTPValidationError


export function useDownloadClientFile<TData = Awaited<ReturnType<typeof downloadClientFile>>, TError = HTTPValidationError>(
 objectName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadClientFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadClientFile>>,
          TError,
          Awaited<ReturnType<typeof downloadClientFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadClientFile<TData = Awaited<ReturnType<typeof downloadClientFile>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadClientFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadClientFile>>,
          TError,
          Awaited<ReturnType<typeof downloadClientFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadClientFile<TData = Awaited<ReturnType<typeof downloadClientFile>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadClientFile>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download File
 */

export function useDownloadClientFile<TData = Awaited<ReturnType<typeof downloadClientFile>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadClientFile>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadClientFileQueryOptions(objectName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetClientFileInfoUrl = (objectName: string,) => {




  return `/v1/files/${objectName}:info`
}

/**
 * 获取文件信息（客户端）
 * @summary Get File Info
 */
export const getClientFileInfo = async (objectName: string, options?: RequestInit): Promise<GetClientFileInfo200> => {

  return customFetch<GetClientFileInfo200>(getGetClientFileInfoUrl(objectName),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClientFileInfoQueryKey = (objectName: string,) => {
    return [
    `/v1/files/${objectName}:info`
    ] as const;
    }


export const getGetClientFileInfoQueryOptions = <TData = Awaited<ReturnType<typeof getClientFileInfo>>, TError = HTTPValidationError>(objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientFileInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientFileInfoQueryKey(objectName);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientFileInfo>>> = ({ signal }) => getClientFileInfo(objectName, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientFileInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientFileInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getClientFileInfo>>>
export type GetClientFileInfoQueryError = HTTPValidationError


export function useGetClientFileInfo<TData = Awaited<ReturnType<typeof getClientFileInfo>>, TError = HTTPValidationError>(
 objectName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientFileInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientFileInfo>>,
          TError,
          Awaited<ReturnType<typeof getClientFileInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientFileInfo<TData = Awaited<ReturnType<typeof getClientFileInfo>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientFileInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientFileInfo>>,
          TError,
          Awaited<ReturnType<typeof getClientFileInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientFileInfo<TData = Awaited<ReturnType<typeof getClientFileInfo>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientFileInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get File Info
 */

export function useGetClientFileInfo<TData = Awaited<ReturnType<typeof getClientFileInfo>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientFileInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientFileInfoQueryOptions(objectName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetClientPresignedUrlUrl = (objectName: string,
    params?: GetClientPresignedUrlParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/files/${objectName}:presignedUrl?${stringifiedParams}` : `/v1/files/${objectName}:presignedUrl`
}

/**
 * 获取文件的访问 URL（客户端）
 * @summary Get Presigned Url
 */
export const getClientPresignedUrl = async (objectName: string,
    params?: GetClientPresignedUrlParams, options?: RequestInit): Promise<GetClientPresignedUrl200> => {

  return customFetch<GetClientPresignedUrl200>(getGetClientPresignedUrlUrl(objectName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClientPresignedUrlQueryKey = (objectName: string,
    params?: GetClientPresignedUrlParams,) => {
    return [
    `/v1/files/${objectName}:presignedUrl`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetClientPresignedUrlQueryOptions = <TData = Awaited<ReturnType<typeof getClientPresignedUrl>>, TError = HTTPValidationError>(objectName: string,
    params?: GetClientPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPresignedUrl>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientPresignedUrlQueryKey(objectName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientPresignedUrl>>> = ({ signal }) => getClientPresignedUrl(objectName,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientPresignedUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientPresignedUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getClientPresignedUrl>>>
export type GetClientPresignedUrlQueryError = HTTPValidationError


export function useGetClientPresignedUrl<TData = Awaited<ReturnType<typeof getClientPresignedUrl>>, TError = HTTPValidationError>(
 objectName: string,
    params: undefined |  GetClientPresignedUrlParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPresignedUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientPresignedUrl>>,
          TError,
          Awaited<ReturnType<typeof getClientPresignedUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientPresignedUrl<TData = Awaited<ReturnType<typeof getClientPresignedUrl>>, TError = HTTPValidationError>(
 objectName: string,
    params?: GetClientPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPresignedUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientPresignedUrl>>,
          TError,
          Awaited<ReturnType<typeof getClientPresignedUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientPresignedUrl<TData = Awaited<ReturnType<typeof getClientPresignedUrl>>, TError = HTTPValidationError>(
 objectName: string,
    params?: GetClientPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPresignedUrl>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Presigned Url
 */

export function useGetClientPresignedUrl<TData = Awaited<ReturnType<typeof getClientPresignedUrl>>, TError = HTTPValidationError>(
 objectName: string,
    params?: GetClientPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPresignedUrl>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientPresignedUrlQueryOptions(objectName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






