/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.7
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CollectionTree,
  GetClientCollectionTreeParams,
  HTTPValidationError
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetClientCollectionTreeUrl = (params: GetClientCollectionTreeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/collections:tree?${stringifiedParams}` : `/v1/collections:tree`
}

/**
 * 获取合集树形结构（客户端）
 * @summary Get Collection Tree
 */
export const getClientCollectionTree = async (params: GetClientCollectionTreeParams, options?: RequestInit): Promise<CollectionTree[] | null> => {

  return customFetch<CollectionTree[] | null>(getGetClientCollectionTreeUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClientCollectionTreeQueryKey = (params?: GetClientCollectionTreeParams,) => {
    return [
    `/v1/collections:tree`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetClientCollectionTreeQueryOptions = <TData = Awaited<ReturnType<typeof getClientCollectionTree>>, TError = HTTPValidationError>(params: GetClientCollectionTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientCollectionTree>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientCollectionTreeQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientCollectionTree>>> = ({ signal }) => getClientCollectionTree(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientCollectionTree>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientCollectionTreeQueryResult = NonNullable<Awaited<ReturnType<typeof getClientCollectionTree>>>
export type GetClientCollectionTreeQueryError = HTTPValidationError


export function useGetClientCollectionTree<TData = Awaited<ReturnType<typeof getClientCollectionTree>>, TError = HTTPValidationError>(
 params: GetClientCollectionTreeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientCollectionTree>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientCollectionTree>>,
          TError,
          Awaited<ReturnType<typeof getClientCollectionTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientCollectionTree<TData = Awaited<ReturnType<typeof getClientCollectionTree>>, TError = HTTPValidationError>(
 params: GetClientCollectionTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientCollectionTree>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientCollectionTree>>,
          TError,
          Awaited<ReturnType<typeof getClientCollectionTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientCollectionTree<TData = Awaited<ReturnType<typeof getClientCollectionTree>>, TError = HTTPValidationError>(
 params: GetClientCollectionTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientCollectionTree>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Collection Tree
 */

export function useGetClientCollectionTree<TData = Awaited<ReturnType<typeof getClientCollectionTree>>, TError = HTTPValidationError>(
 params: GetClientCollectionTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientCollectionTree>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientCollectionTreeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






