/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.4
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChatSessionListResponse,
  ChatSessionMessagesResponse,
  ChatSessionResponse,
  ClearAllChatSessions200,
  ClearAllChatSessionsParams,
  DeleteChatSession200,
  DeleteChatSessionParams,
  GetChatSessionMessagesParams,
  GetChatSessionParams,
  GetChatToolResult200,
  GetChatToolResultParams,
  HTTPValidationError,
  ListChatSessionsParams
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListChatSessionsUrl = (params: ListChatSessionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/chat/sessions?${stringifiedParams}` : `/v1/chat/sessions`
}

/**
 * 获取会话列表

member_id 为必填，仅返回该访客自己的会话。站点级全量审计请使用 Admin API。
 * @summary List Sessions
 */
export const listChatSessions = async (params: ListChatSessionsParams, options?: RequestInit): Promise<ChatSessionListResponse | null> => {

  return customFetch<ChatSessionListResponse | null>(getListChatSessionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListChatSessionsQueryKey = (params?: ListChatSessionsParams,) => {
    return [
    `/v1/chat/sessions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListChatSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listChatSessions>>, TError = HTTPValidationError>(params: ListChatSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChatSessions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChatSessionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChatSessions>>> = ({ signal }) => listChatSessions(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChatSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListChatSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listChatSessions>>>
export type ListChatSessionsQueryError = HTTPValidationError


export function useListChatSessions<TData = Awaited<ReturnType<typeof listChatSessions>>, TError = HTTPValidationError>(
 params: ListChatSessionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChatSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChatSessions>>,
          TError,
          Awaited<ReturnType<typeof listChatSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChatSessions<TData = Awaited<ReturnType<typeof listChatSessions>>, TError = HTTPValidationError>(
 params: ListChatSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChatSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChatSessions>>,
          TError,
          Awaited<ReturnType<typeof listChatSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChatSessions<TData = Awaited<ReturnType<typeof listChatSessions>>, TError = HTTPValidationError>(
 params: ListChatSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChatSessions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Sessions
 */

export function useListChatSessions<TData = Awaited<ReturnType<typeof listChatSessions>>, TError = HTTPValidationError>(
 params: ListChatSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChatSessions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListChatSessionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getClearAllChatSessionsUrl = (params: ClearAllChatSessionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/chat/sessions?${stringifiedParams}` : `/v1/chat/sessions`
}

/**
 * 清空指定访客的全部会话

删除该访客在指定站点（或全局）下的所有会话及 LangGraph checkpoints。
 * @summary Clear All Sessions
 */
export const clearAllChatSessions = async (params: ClearAllChatSessionsParams, options?: RequestInit): Promise<ClearAllChatSessions200> => {

  return customFetch<ClearAllChatSessions200>(getClearAllChatSessionsUrl(params),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getClearAllChatSessionsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearAllChatSessions>>, TError,{params: ClearAllChatSessionsParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof clearAllChatSessions>>, TError,{params: ClearAllChatSessionsParams}, TContext> => {

const mutationKey = ['clearAllChatSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clearAllChatSessions>>, {params: ClearAllChatSessionsParams}> = (props) => {
          const {params} = props ?? {};

          return  clearAllChatSessions(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClearAllChatSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof clearAllChatSessions>>>

    export type ClearAllChatSessionsMutationError = HTTPValidationError

    /**
 * @summary Clear All Sessions
 */
export const useClearAllChatSessions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearAllChatSessions>>, TError,{params: ClearAllChatSessionsParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clearAllChatSessions>>,
        TError,
        {params: ClearAllChatSessionsParams},
        TContext
      > => {
      return useMutation(getClearAllChatSessionsMutationOptions(options), queryClient);
    }
    export const getGetChatSessionUrl = (threadId: string,
    params: GetChatSessionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/chat/sessions/${threadId}?${stringifiedParams}` : `/v1/chat/sessions/${threadId}`
}

/**
 * 获取会话详情

返回会话元数据。如需获取完整消息历史，请调用 GET /chat/sessions/{thread_id}/messages。
 * @summary Get Session
 */
export const getChatSession = async (threadId: string,
    params: GetChatSessionParams, options?: RequestInit): Promise<ChatSessionResponse | null> => {

  return customFetch<ChatSessionResponse | null>(getGetChatSessionUrl(threadId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetChatSessionQueryKey = (threadId: string,
    params?: GetChatSessionParams,) => {
    return [
    `/v1/chat/sessions/${threadId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetChatSessionQueryOptions = <TData = Awaited<ReturnType<typeof getChatSession>>, TError = HTTPValidationError>(threadId: string,
    params: GetChatSessionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChatSessionQueryKey(threadId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChatSession>>> = ({ signal }) => getChatSession(threadId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: threadId !== null && threadId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChatSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChatSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getChatSession>>>
export type GetChatSessionQueryError = HTTPValidationError


export function useGetChatSession<TData = Awaited<ReturnType<typeof getChatSession>>, TError = HTTPValidationError>(
 threadId: string,
    params: GetChatSessionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatSession>>,
          TError,
          Awaited<ReturnType<typeof getChatSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatSession<TData = Awaited<ReturnType<typeof getChatSession>>, TError = HTTPValidationError>(
 threadId: string,
    params: GetChatSessionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatSession>>,
          TError,
          Awaited<ReturnType<typeof getChatSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatSession<TData = Awaited<ReturnType<typeof getChatSession>>, TError = HTTPValidationError>(
 threadId: string,
    params: GetChatSessionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Session
 */

export function useGetChatSession<TData = Awaited<ReturnType<typeof getChatSession>>, TError = HTTPValidationError>(
 threadId: string,
    params: GetChatSessionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSession>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChatSessionQueryOptions(threadId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getDeleteChatSessionUrl = (threadId: string,
    params: DeleteChatSessionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/chat/sessions/${threadId}?${stringifiedParams}` : `/v1/chat/sessions/${threadId}`
}

/**
 * 删除会话

删除会话元数据记录，并同步删除 LangGraph Checkpointer 中的消息历史。
仅允许删除自己（member_id 匹配）的会话。
 * @summary Delete Session
 */
export const deleteChatSession = async (threadId: string,
    params: DeleteChatSessionParams, options?: RequestInit): Promise<DeleteChatSession200> => {

  return customFetch<DeleteChatSession200>(getDeleteChatSessionUrl(threadId,params),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteChatSessionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChatSession>>, TError,{threadId: string;params: DeleteChatSessionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteChatSession>>, TError,{threadId: string;params: DeleteChatSessionParams}, TContext> => {

const mutationKey = ['deleteChatSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChatSession>>, {threadId: string;params: DeleteChatSessionParams}> = (props) => {
          const {threadId,params} = props ?? {};

          return  deleteChatSession(threadId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteChatSessionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChatSession>>>

    export type DeleteChatSessionMutationError = HTTPValidationError

    /**
 * @summary Delete Session
 */
export const useDeleteChatSession = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChatSession>>, TError,{threadId: string;params: DeleteChatSessionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteChatSession>>,
        TError,
        {threadId: string;params: DeleteChatSessionParams},
        TContext
      > => {
      return useMutation(getDeleteChatSessionMutationOptions(options), queryClient);
    }
    export const getGetChatSessionMessagesUrl = (threadId: string,
    params: GetChatSessionMessagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/chat/sessions/${threadId}/messages?${stringifiedParams}` : `/v1/chat/sessions/${threadId}/messages`
}

/**
 * 获取单个会话的完整聊天历史信息

从数据库全量历史表中读取所有消息。
 * @summary Get Session Messages
 */
export const getChatSessionMessages = async (threadId: string,
    params: GetChatSessionMessagesParams, options?: RequestInit): Promise<ChatSessionMessagesResponse | null> => {

  return customFetch<ChatSessionMessagesResponse | null>(getGetChatSessionMessagesUrl(threadId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetChatSessionMessagesQueryKey = (threadId: string,
    params?: GetChatSessionMessagesParams,) => {
    return [
    `/v1/chat/sessions/${threadId}/messages`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetChatSessionMessagesQueryOptions = <TData = Awaited<ReturnType<typeof getChatSessionMessages>>, TError = HTTPValidationError>(threadId: string,
    params: GetChatSessionMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSessionMessages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChatSessionMessagesQueryKey(threadId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChatSessionMessages>>> = ({ signal }) => getChatSessionMessages(threadId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: threadId !== null && threadId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChatSessionMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChatSessionMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getChatSessionMessages>>>
export type GetChatSessionMessagesQueryError = HTTPValidationError


export function useGetChatSessionMessages<TData = Awaited<ReturnType<typeof getChatSessionMessages>>, TError = HTTPValidationError>(
 threadId: string,
    params: GetChatSessionMessagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSessionMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatSessionMessages>>,
          TError,
          Awaited<ReturnType<typeof getChatSessionMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatSessionMessages<TData = Awaited<ReturnType<typeof getChatSessionMessages>>, TError = HTTPValidationError>(
 threadId: string,
    params: GetChatSessionMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSessionMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatSessionMessages>>,
          TError,
          Awaited<ReturnType<typeof getChatSessionMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatSessionMessages<TData = Awaited<ReturnType<typeof getChatSessionMessages>>, TError = HTTPValidationError>(
 threadId: string,
    params: GetChatSessionMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSessionMessages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Session Messages
 */

export function useGetChatSessionMessages<TData = Awaited<ReturnType<typeof getChatSessionMessages>>, TError = HTTPValidationError>(
 threadId: string,
    params: GetChatSessionMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatSessionMessages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChatSessionMessagesQueryOptions(threadId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetChatToolResultUrl = (threadId: string,
    toolCallId: string,
    params: GetChatToolResultParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/chat/sessions/${threadId}/tool-result/${toolCallId}?${stringifiedParams}` : `/v1/chat/sessions/${threadId}/tool-result/${toolCallId}`
}

/**
 * 获取单个工具调用的检索结果

根据 tool_call_id 查找对应的 tool 消息内容。
 * @summary Get Tool Result
 */
export const getChatToolResult = async (threadId: string,
    toolCallId: string,
    params: GetChatToolResultParams, options?: RequestInit): Promise<GetChatToolResult200> => {

  return customFetch<GetChatToolResult200>(getGetChatToolResultUrl(threadId,toolCallId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetChatToolResultQueryKey = (threadId: string,
    toolCallId: string,
    params?: GetChatToolResultParams,) => {
    return [
    `/v1/chat/sessions/${threadId}/tool-result/${toolCallId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetChatToolResultQueryOptions = <TData = Awaited<ReturnType<typeof getChatToolResult>>, TError = HTTPValidationError>(threadId: string,
    toolCallId: string,
    params: GetChatToolResultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatToolResult>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChatToolResultQueryKey(threadId,toolCallId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChatToolResult>>> = ({ signal }) => getChatToolResult(threadId,toolCallId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: threadId !== null && threadId !== undefined && toolCallId !== null && toolCallId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChatToolResult>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChatToolResultQueryResult = NonNullable<Awaited<ReturnType<typeof getChatToolResult>>>
export type GetChatToolResultQueryError = HTTPValidationError


export function useGetChatToolResult<TData = Awaited<ReturnType<typeof getChatToolResult>>, TError = HTTPValidationError>(
 threadId: string,
    toolCallId: string,
    params: GetChatToolResultParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatToolResult>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatToolResult>>,
          TError,
          Awaited<ReturnType<typeof getChatToolResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatToolResult<TData = Awaited<ReturnType<typeof getChatToolResult>>, TError = HTTPValidationError>(
 threadId: string,
    toolCallId: string,
    params: GetChatToolResultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatToolResult>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatToolResult>>,
          TError,
          Awaited<ReturnType<typeof getChatToolResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatToolResult<TData = Awaited<ReturnType<typeof getChatToolResult>>, TError = HTTPValidationError>(
 threadId: string,
    toolCallId: string,
    params: GetChatToolResultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatToolResult>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Tool Result
 */

export function useGetChatToolResult<TData = Awaited<ReturnType<typeof getChatToolResult>>, TError = HTTPValidationError>(
 threadId: string,
    toolCallId: string,
    params: GetChatToolResultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatToolResult>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChatToolResultQueryOptions(threadId,toolCallId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






