/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.7
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  HandleAppMessageV1BotWecomAppPostParams,
  HandleKefuMessageV1BotWecomKefuPostParams,
  VerifyAppUrlV1BotWecomAppGetParams,
  VerifyKefuUrlV1BotWecomKefuGetParams
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getVerifyKefuUrlV1BotWecomKefuGetUrl = (params: VerifyKefuUrlV1BotWecomKefuGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/bot/wecom-kefu?${stringifiedParams}` : `/v1/bot/wecom-kefu`
}

/**
 * 验证回调 URL (企业微信客服设置时触发)
 * @summary Verify Kefu Url
 */
export const verifyKefuUrlV1BotWecomKefuGet = async (params: VerifyKefuUrlV1BotWecomKefuGetParams, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getVerifyKefuUrlV1BotWecomKefuGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getVerifyKefuUrlV1BotWecomKefuGetQueryKey = (params?: VerifyKefuUrlV1BotWecomKefuGetParams,) => {
    return [
    `/v1/bot/wecom-kefu`, ...(params ? [params] : [])
    ] as const;
    }


export const getVerifyKefuUrlV1BotWecomKefuGetQueryOptions = <TData = Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError = HTTPValidationError>(params: VerifyKefuUrlV1BotWecomKefuGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVerifyKefuUrlV1BotWecomKefuGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>> = ({ signal }) => verifyKefuUrlV1BotWecomKefuGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VerifyKefuUrlV1BotWecomKefuGetQueryResult = NonNullable<Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>>
export type VerifyKefuUrlV1BotWecomKefuGetQueryError = HTTPValidationError


export function useVerifyKefuUrlV1BotWecomKefuGet<TData = Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError = HTTPValidationError>(
 params: VerifyKefuUrlV1BotWecomKefuGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>,
          TError,
          Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifyKefuUrlV1BotWecomKefuGet<TData = Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError = HTTPValidationError>(
 params: VerifyKefuUrlV1BotWecomKefuGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>,
          TError,
          Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifyKefuUrlV1BotWecomKefuGet<TData = Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError = HTTPValidationError>(
 params: VerifyKefuUrlV1BotWecomKefuGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Verify Kefu Url
 */

export function useVerifyKefuUrlV1BotWecomKefuGet<TData = Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError = HTTPValidationError>(
 params: VerifyKefuUrlV1BotWecomKefuGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyKefuUrlV1BotWecomKefuGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVerifyKefuUrlV1BotWecomKefuGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getHandleKefuMessageV1BotWecomKefuPostUrl = (params: HandleKefuMessageV1BotWecomKefuPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/bot/wecom-kefu?${stringifiedParams}` : `/v1/bot/wecom-kefu`
}

/**
 * 处理企业微信客服消息回调 (XML 协议)
 * @summary Handle Kefu Message
 */
export const handleKefuMessageV1BotWecomKefuPost = async (params: HandleKefuMessageV1BotWecomKefuPostParams, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getHandleKefuMessageV1BotWecomKefuPostUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getHandleKefuMessageV1BotWecomKefuPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleKefuMessageV1BotWecomKefuPost>>, TError,{params: HandleKefuMessageV1BotWecomKefuPostParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof handleKefuMessageV1BotWecomKefuPost>>, TError,{params: HandleKefuMessageV1BotWecomKefuPostParams}, TContext> => {

const mutationKey = ['handleKefuMessageV1BotWecomKefuPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof handleKefuMessageV1BotWecomKefuPost>>, {params: HandleKefuMessageV1BotWecomKefuPostParams}> = (props) => {
          const {params} = props ?? {};

          return  handleKefuMessageV1BotWecomKefuPost(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HandleKefuMessageV1BotWecomKefuPostMutationResult = NonNullable<Awaited<ReturnType<typeof handleKefuMessageV1BotWecomKefuPost>>>

    export type HandleKefuMessageV1BotWecomKefuPostMutationError = HTTPValidationError

    /**
 * @summary Handle Kefu Message
 */
export const useHandleKefuMessageV1BotWecomKefuPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleKefuMessageV1BotWecomKefuPost>>, TError,{params: HandleKefuMessageV1BotWecomKefuPostParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof handleKefuMessageV1BotWecomKefuPost>>,
        TError,
        {params: HandleKefuMessageV1BotWecomKefuPostParams},
        TContext
      > => {
      return useMutation(getHandleKefuMessageV1BotWecomKefuPostMutationOptions(options), queryClient);
    }
    export const getVerifyAppUrlV1BotWecomAppGetUrl = (params: VerifyAppUrlV1BotWecomAppGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/bot/wecom-app?${stringifiedParams}` : `/v1/bot/wecom-app`
}

/**
 * 验证回调 URL (企业微信机器人设置时触发)
 * @summary Verify App Url
 */
export const verifyAppUrlV1BotWecomAppGet = async (params: VerifyAppUrlV1BotWecomAppGetParams, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getVerifyAppUrlV1BotWecomAppGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getVerifyAppUrlV1BotWecomAppGetQueryKey = (params?: VerifyAppUrlV1BotWecomAppGetParams,) => {
    return [
    `/v1/bot/wecom-app`, ...(params ? [params] : [])
    ] as const;
    }


export const getVerifyAppUrlV1BotWecomAppGetQueryOptions = <TData = Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError = HTTPValidationError>(params: VerifyAppUrlV1BotWecomAppGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVerifyAppUrlV1BotWecomAppGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>> = ({ signal }) => verifyAppUrlV1BotWecomAppGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VerifyAppUrlV1BotWecomAppGetQueryResult = NonNullable<Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>>
export type VerifyAppUrlV1BotWecomAppGetQueryError = HTTPValidationError


export function useVerifyAppUrlV1BotWecomAppGet<TData = Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError = HTTPValidationError>(
 params: VerifyAppUrlV1BotWecomAppGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>,
          TError,
          Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifyAppUrlV1BotWecomAppGet<TData = Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError = HTTPValidationError>(
 params: VerifyAppUrlV1BotWecomAppGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>,
          TError,
          Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifyAppUrlV1BotWecomAppGet<TData = Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError = HTTPValidationError>(
 params: VerifyAppUrlV1BotWecomAppGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Verify App Url
 */

export function useVerifyAppUrlV1BotWecomAppGet<TData = Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError = HTTPValidationError>(
 params: VerifyAppUrlV1BotWecomAppGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyAppUrlV1BotWecomAppGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVerifyAppUrlV1BotWecomAppGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getHandleAppMessageV1BotWecomAppPostUrl = (params: HandleAppMessageV1BotWecomAppPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/bot/wecom-app?${stringifiedParams}` : `/v1/bot/wecom-app`
}

/**
 * 处理企业微信机器人消息回调 (XML 协议)
 * @summary Handle App Message
 */
export const handleAppMessageV1BotWecomAppPost = async (params: HandleAppMessageV1BotWecomAppPostParams, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getHandleAppMessageV1BotWecomAppPostUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getHandleAppMessageV1BotWecomAppPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleAppMessageV1BotWecomAppPost>>, TError,{params: HandleAppMessageV1BotWecomAppPostParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof handleAppMessageV1BotWecomAppPost>>, TError,{params: HandleAppMessageV1BotWecomAppPostParams}, TContext> => {

const mutationKey = ['handleAppMessageV1BotWecomAppPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof handleAppMessageV1BotWecomAppPost>>, {params: HandleAppMessageV1BotWecomAppPostParams}> = (props) => {
          const {params} = props ?? {};

          return  handleAppMessageV1BotWecomAppPost(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HandleAppMessageV1BotWecomAppPostMutationResult = NonNullable<Awaited<ReturnType<typeof handleAppMessageV1BotWecomAppPost>>>

    export type HandleAppMessageV1BotWecomAppPostMutationError = HTTPValidationError

    /**
 * @summary Handle App Message
 */
export const useHandleAppMessageV1BotWecomAppPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleAppMessageV1BotWecomAppPost>>, TError,{params: HandleAppMessageV1BotWecomAppPostParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof handleAppMessageV1BotWecomAppPost>>,
        TError,
        {params: HandleAppMessageV1BotWecomAppPostParams},
        TContext
      > => {
      return useMutation(getHandleAppMessageV1BotWecomAppPostMutationOptions(options), queryClient);
    }
