/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.4
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HealthResponse
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetClientHealthUrl = () => {




  return `/v1/health`
}

/**
 * 检查 API 服务状态并返回版本信息
 * @summary 健康检查 (客户端)
 */
export const getClientHealth = async ( options?: RequestInit): Promise<HealthResponse | null> => {

  return customFetch<HealthResponse | null>(getGetClientHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClientHealthQueryKey = () => {
    return [
    `/v1/health`
    ] as const;
    }


export const getGetClientHealthQueryOptions = <TData = Awaited<ReturnType<typeof getClientHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientHealth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientHealth>>> = ({ signal }) => getClientHealth({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getClientHealth>>>
export type GetClientHealthQueryError = unknown


export function useGetClientHealth<TData = Awaited<ReturnType<typeof getClientHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientHealth>>,
          TError,
          Awaited<ReturnType<typeof getClientHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientHealth<TData = Awaited<ReturnType<typeof getClientHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientHealth>>,
          TError,
          Awaited<ReturnType<typeof getClientHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientHealth<TData = Awaited<ReturnType<typeof getClientHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientHealth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 健康检查 (客户端)
 */

export function useGetClientHealth<TData = Awaited<ReturnType<typeof getClientHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientHealth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






