/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.5
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ResponsesAPIRequest,
  ResponsesAPIResponse
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getCreateResponseUrl = () => {




  return `/v1/chat/responses`
}

/**
 * 创建 AI 响应（标准 OpenAI Responses API，含 CatWiki 扩展字段 filter）
 * @summary Create Response
 */
export const createResponse = async (responsesAPIRequest: ResponsesAPIRequest, options?: RequestInit): Promise<ResponsesAPIResponse> => {

  return customFetch<ResponsesAPIResponse>(getCreateResponseUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(responsesAPIRequest)
  }
);}




export const getCreateResponseMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResponse>>, TError,{data: ResponsesAPIRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createResponse>>, TError,{data: ResponsesAPIRequest}, TContext> => {

const mutationKey = ['createResponse'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createResponse>>, {data: ResponsesAPIRequest}> = (props) => {
          const {data} = props ?? {};

          return  createResponse(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateResponseMutationResult = NonNullable<Awaited<ReturnType<typeof createResponse>>>
    export type CreateResponseMutationBody = ResponsesAPIRequest
    export type CreateResponseMutationError = HTTPValidationError

    /**
 * @summary Create Response
 */
export const useCreateResponse = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResponse>>, TError,{data: ResponsesAPIRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createResponse>>,
        TError,
        {data: ResponsesAPIRequest},
        TContext
      > => {
      return useMutation(getCreateResponseMutationOptions(options), queryClient);
    }
