/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.6
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClientSite,
  GetClientSiteBySlugParams,
  HTTPValidationError,
  ListClientSitesParams,
  PaginatedResponseClientSite
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListClientSitesUrl = (params?: ListClientSitesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/sites?${stringifiedParams}` : `/v1/sites`
}

/**
 * 获取激活的站点列表（客户端）

- 不传 tenant_id：返回所有租户的激活站点（站点广场）
- 传 tenant_id：仅返回该租户下的激活站点
 * @summary List Active Sites
 */
export const listClientSites = async (params?: ListClientSitesParams, options?: RequestInit): Promise<PaginatedResponseClientSite | null> => {

  return customFetch<PaginatedResponseClientSite | null>(getListClientSitesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListClientSitesQueryKey = (params?: ListClientSitesParams,) => {
    return [
    `/v1/sites`, ...(params ? [params] : [])
    ] as const;
    }


export const getListClientSitesQueryOptions = <TData = Awaited<ReturnType<typeof listClientSites>>, TError = HTTPValidationError>(params?: ListClientSitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientSites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListClientSitesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listClientSites>>> = ({ signal }) => listClientSites(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listClientSites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListClientSitesQueryResult = NonNullable<Awaited<ReturnType<typeof listClientSites>>>
export type ListClientSitesQueryError = HTTPValidationError


export function useListClientSites<TData = Awaited<ReturnType<typeof listClientSites>>, TError = HTTPValidationError>(
 params: undefined |  ListClientSitesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientSites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClientSites>>,
          TError,
          Awaited<ReturnType<typeof listClientSites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListClientSites<TData = Awaited<ReturnType<typeof listClientSites>>, TError = HTTPValidationError>(
 params?: ListClientSitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientSites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClientSites>>,
          TError,
          Awaited<ReturnType<typeof listClientSites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListClientSites<TData = Awaited<ReturnType<typeof listClientSites>>, TError = HTTPValidationError>(
 params?: ListClientSitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientSites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Active Sites
 */

export function useListClientSites<TData = Awaited<ReturnType<typeof listClientSites>>, TError = HTTPValidationError>(
 params?: ListClientSitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listClientSites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListClientSitesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetClientSiteBySlugUrl = (slug: string,
    params?: GetClientSiteBySlugParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/sites:bySlug/${slug}?${stringifiedParams}` : `/v1/sites:bySlug/${slug}`
}

/**
 * 通过 slug 获取站点详情（客户端）
 * @summary Get Site By Slug
 */
export const getClientSiteBySlug = async (slug: string,
    params?: GetClientSiteBySlugParams, options?: RequestInit): Promise<ClientSite | null> => {

  return customFetch<ClientSite | null>(getGetClientSiteBySlugUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClientSiteBySlugQueryKey = (slug: string,
    params?: GetClientSiteBySlugParams,) => {
    return [
    `/v1/sites:bySlug/${slug}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetClientSiteBySlugQueryOptions = <TData = Awaited<ReturnType<typeof getClientSiteBySlug>>, TError = HTTPValidationError>(slug: string,
    params?: GetClientSiteBySlugParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSiteBySlug>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientSiteBySlugQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientSiteBySlug>>> = ({ signal }) => getClientSiteBySlug(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientSiteBySlug>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientSiteBySlugQueryResult = NonNullable<Awaited<ReturnType<typeof getClientSiteBySlug>>>
export type GetClientSiteBySlugQueryError = HTTPValidationError


export function useGetClientSiteBySlug<TData = Awaited<ReturnType<typeof getClientSiteBySlug>>, TError = HTTPValidationError>(
 slug: string,
    params: undefined |  GetClientSiteBySlugParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSiteBySlug>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientSiteBySlug>>,
          TError,
          Awaited<ReturnType<typeof getClientSiteBySlug>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientSiteBySlug<TData = Awaited<ReturnType<typeof getClientSiteBySlug>>, TError = HTTPValidationError>(
 slug: string,
    params?: GetClientSiteBySlugParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSiteBySlug>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientSiteBySlug>>,
          TError,
          Awaited<ReturnType<typeof getClientSiteBySlug>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientSiteBySlug<TData = Awaited<ReturnType<typeof getClientSiteBySlug>>, TError = HTTPValidationError>(
 slug: string,
    params?: GetClientSiteBySlugParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSiteBySlug>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Site By Slug
 */

export function useGetClientSiteBySlug<TData = Awaited<ReturnType<typeof getClientSiteBySlug>>, TError = HTTPValidationError>(
 slug: string,
    params?: GetClientSiteBySlugParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSiteBySlug>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientSiteBySlugQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetClientSiteUrl = (siteId: number,) => {




  return `/v1/sites/${siteId}`
}

/**
 * 获取站点详情（客户端）
 * @summary Get Site
 */
export const getClientSite = async (siteId: number, options?: RequestInit): Promise<ClientSite | null> => {

  return customFetch<ClientSite | null>(getGetClientSiteUrl(siteId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClientSiteQueryKey = (siteId: number,) => {
    return [
    `/v1/sites/${siteId}`
    ] as const;
    }


export const getGetClientSiteQueryOptions = <TData = Awaited<ReturnType<typeof getClientSite>>, TError = HTTPValidationError>(siteId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSite>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientSiteQueryKey(siteId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientSite>>> = ({ signal }) => getClientSite(siteId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: siteId !== null && siteId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientSite>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientSiteQueryResult = NonNullable<Awaited<ReturnType<typeof getClientSite>>>
export type GetClientSiteQueryError = HTTPValidationError


export function useGetClientSite<TData = Awaited<ReturnType<typeof getClientSite>>, TError = HTTPValidationError>(
 siteId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSite>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientSite>>,
          TError,
          Awaited<ReturnType<typeof getClientSite>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientSite<TData = Awaited<ReturnType<typeof getClientSite>>, TError = HTTPValidationError>(
 siteId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSite>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientSite>>,
          TError,
          Awaited<ReturnType<typeof getClientSite>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientSite<TData = Awaited<ReturnType<typeof getClientSite>>, TError = HTTPValidationError>(
 siteId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSite>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Site
 */

export function useGetClientSite<TData = Awaited<ReturnType<typeof getClientSite>>, TError = HTTPValidationError>(
 siteId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientSite>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientSiteQueryOptions(siteId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






