/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.5
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ModelList,
  OpenAIChatCompletionRequest
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getCreateSiteChatCompletionUrl = () => {




  return `/v1/bot/chat/completions`
}

/**
 * 创建聊天补全 (专用接口，兼容 OpenAI 格式)
[企业版专属功能]
 * @summary Create Site Chat Completion
 */
export const createSiteChatCompletion = async (openAIChatCompletionRequest: OpenAIChatCompletionRequest, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getCreateSiteChatCompletionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(openAIChatCompletionRequest)
  }
);}




export const getCreateSiteChatCompletionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSiteChatCompletion>>, TError,{data: OpenAIChatCompletionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createSiteChatCompletion>>, TError,{data: OpenAIChatCompletionRequest}, TContext> => {

const mutationKey = ['createSiteChatCompletion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSiteChatCompletion>>, {data: OpenAIChatCompletionRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSiteChatCompletion(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSiteChatCompletionMutationResult = NonNullable<Awaited<ReturnType<typeof createSiteChatCompletion>>>
    export type CreateSiteChatCompletionMutationBody = OpenAIChatCompletionRequest
    export type CreateSiteChatCompletionMutationError = HTTPValidationError

    /**
 * @summary Create Site Chat Completion
 */
export const useCreateSiteChatCompletion = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSiteChatCompletion>>, TError,{data: OpenAIChatCompletionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSiteChatCompletion>>,
        TError,
        {data: OpenAIChatCompletionRequest},
        TContext
      > => {
      return useMutation(getCreateSiteChatCompletionMutationOptions(options), queryClient);
    }
    export const getListEeClientBotModelsUrl = () => {




  return `/v1/bot/models`
}

/**
 * 列出可用的模型 (兼容 OpenAI 格式)
 * @summary List Models
 */
export const listEeClientBotModels = async ( options?: RequestInit): Promise<ModelList> => {

  return customFetch<ModelList>(getListEeClientBotModelsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEeClientBotModelsQueryKey = () => {
    return [
    `/v1/bot/models`
    ] as const;
    }


export const getListEeClientBotModelsQueryOptions = <TData = Awaited<ReturnType<typeof listEeClientBotModels>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEeClientBotModels>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEeClientBotModelsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEeClientBotModels>>> = ({ signal }) => listEeClientBotModels({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEeClientBotModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEeClientBotModelsQueryResult = NonNullable<Awaited<ReturnType<typeof listEeClientBotModels>>>
export type ListEeClientBotModelsQueryError = HTTPValidationError


export function useListEeClientBotModels<TData = Awaited<ReturnType<typeof listEeClientBotModels>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEeClientBotModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEeClientBotModels>>,
          TError,
          Awaited<ReturnType<typeof listEeClientBotModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEeClientBotModels<TData = Awaited<ReturnType<typeof listEeClientBotModels>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEeClientBotModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEeClientBotModels>>,
          TError,
          Awaited<ReturnType<typeof listEeClientBotModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEeClientBotModels<TData = Awaited<ReturnType<typeof listEeClientBotModels>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEeClientBotModels>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Models
 */

export function useListEeClientBotModels<TData = Awaited<ReturnType<typeof listEeClientBotModels>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEeClientBotModels>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEeClientBotModelsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






