/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Client API
 * 客户端 API - 仅提供已发布内容的只读访问
 * OpenAPI spec version: 1.1.5
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSiteAccessStatus200,
  GetSiteAccessStatusParams,
  HTTPValidationError,
  VerifyPasswordRequest,
  VerifyPasswordResponse,
  VerifySitePasswordParams
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetSiteAccessStatusUrl = (slug: string,
    params?: GetSiteAccessStatusParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/client/sites/${slug}/access-status?${stringifiedParams}` : `/v1/client/sites/${slug}/access-status`
}

/**
 * 客户端接口：获取站点的访问状态（是否公开、是否需要密码）
 * @summary Get Site Access Status
 */
export const getSiteAccessStatus = async (slug: string,
    params?: GetSiteAccessStatusParams, options?: RequestInit): Promise<GetSiteAccessStatus200> => {

  return customFetch<GetSiteAccessStatus200>(getGetSiteAccessStatusUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSiteAccessStatusQueryKey = (slug: string,
    params?: GetSiteAccessStatusParams,) => {
    return [
    `/v1/client/sites/${slug}/access-status`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetSiteAccessStatusQueryOptions = <TData = Awaited<ReturnType<typeof getSiteAccessStatus>>, TError = HTTPValidationError>(slug: string,
    params?: GetSiteAccessStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSiteAccessStatus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSiteAccessStatusQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSiteAccessStatus>>> = ({ signal }) => getSiteAccessStatus(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSiteAccessStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSiteAccessStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getSiteAccessStatus>>>
export type GetSiteAccessStatusQueryError = HTTPValidationError


export function useGetSiteAccessStatus<TData = Awaited<ReturnType<typeof getSiteAccessStatus>>, TError = HTTPValidationError>(
 slug: string,
    params: undefined |  GetSiteAccessStatusParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSiteAccessStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSiteAccessStatus>>,
          TError,
          Awaited<ReturnType<typeof getSiteAccessStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSiteAccessStatus<TData = Awaited<ReturnType<typeof getSiteAccessStatus>>, TError = HTTPValidationError>(
 slug: string,
    params?: GetSiteAccessStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSiteAccessStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSiteAccessStatus>>,
          TError,
          Awaited<ReturnType<typeof getSiteAccessStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSiteAccessStatus<TData = Awaited<ReturnType<typeof getSiteAccessStatus>>, TError = HTTPValidationError>(
 slug: string,
    params?: GetSiteAccessStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSiteAccessStatus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Site Access Status
 */

export function useGetSiteAccessStatus<TData = Awaited<ReturnType<typeof getSiteAccessStatus>>, TError = HTTPValidationError>(
 slug: string,
    params?: GetSiteAccessStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSiteAccessStatus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSiteAccessStatusQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getVerifySitePasswordUrl = (slug: string,
    params?: VerifySitePasswordParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/client/sites/${slug}/verify-password?${stringifiedParams}` : `/v1/client/sites/${slug}/verify-password`
}

/**
 * 客户端接口：验证站点访问密码，返回短期访问 token
 * @summary Verify Site Password
 */
export const verifySitePassword = async (slug: string,
    verifyPasswordRequest: VerifyPasswordRequest,
    params?: VerifySitePasswordParams, options?: RequestInit): Promise<VerifyPasswordResponse | null> => {

  return customFetch<VerifyPasswordResponse | null>(getVerifySitePasswordUrl(slug,params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(verifyPasswordRequest)
  }
);}




export const getVerifySitePasswordMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifySitePassword>>, TError,{slug: string;data: VerifyPasswordRequest;params?: VerifySitePasswordParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof verifySitePassword>>, TError,{slug: string;data: VerifyPasswordRequest;params?: VerifySitePasswordParams}, TContext> => {

const mutationKey = ['verifySitePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifySitePassword>>, {slug: string;data: VerifyPasswordRequest;params?: VerifySitePasswordParams}> = (props) => {
          const {slug,data,params} = props ?? {};

          return  verifySitePassword(slug,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VerifySitePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof verifySitePassword>>>
    export type VerifySitePasswordMutationBody = VerifyPasswordRequest
    export type VerifySitePasswordMutationError = HTTPValidationError

    /**
 * @summary Verify Site Password
 */
export const useVerifySitePassword = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifySitePassword>>, TError,{slug: string;data: VerifyPasswordRequest;params?: VerifySitePasswordParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifySitePassword>>,
        TError,
        {slug: string;data: VerifyPasswordRequest;params?: VerifySitePasswordParams},
        TContext
      > => {
      return useMutation(getVerifySitePasswordMutationOptions(options), queryClient);
    }
