"""add parse_meta to document

Revision ID: 09c3ac2de938
Revises: ee01a0b0c0d0
Create Date: 2026-04-15 15:25:45.804082

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "09c3ac2de938"
down_revision = "ee01a0b0c0d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_sessions",
        "thread_id",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="LangGraph Checkpointer thread_id",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_sessions",
        "site_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="站点ID",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_sessions",
        "member_id",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="会员ID或访客标识（可选，支持匿名）",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_sessions",
        "title",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="会话标题",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_sessions",
        "last_message",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="最后消息预览",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_sessions",
        "last_message_role",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="最后消息角色 user/assistant",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_sessions",
        "message_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        comment=None,
        existing_comment="消息数量",
        existing_server_default=sa.text("0"),
    )
    op.drop_index(op.f("ix_chat_sessions_tenant_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_updated_at"), table_name="chat_sessions")
    op.create_index(op.f("ix_chat_sessions_id"), "chat_sessions", ["id"], unique=False)
    op.add_column(
        "document",
        sa.Column(
            "parse_meta",
            sa.JSON(),
            nullable=True,
            comment="文档解析元数据：解析器类型、原始文件路径、耗时等",
        ),
    )
    op.alter_column(
        "document_view_events",
        "tenant_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="所属租户ID",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_view_events_member"), table_name="document_view_events")
    op.create_index(
        op.f("ix_document_view_events_document_id"),
        "document_view_events",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_view_events_member_id"),
        "document_view_events",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_view_events_tenant_id"),
        "document_view_events",
        ["tenant_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_site_ee_configs_site_id"), table_name="site_ee_configs")
    op.create_index(op.f("ix_site_ee_configs_id"), "site_ee_configs", ["id"], unique=False)
    op.drop_index(op.f("ix_sites_tenant_id"), table_name="sites")
    op.alter_column(
        "system_configs",
        "tenant_id",
        existing_type=sa.INTEGER(),
        comment="所属租户ID(null表示平台全局配置)",
        existing_comment="所属租户ID(null=平台全局配置)",
        existing_nullable=True,
    )
    op.alter_column(
        "system_configs",
        "config_key",
        existing_type=sa.VARCHAR(length=100),
        comment="配置键，如 'ai_config'",
        existing_comment="配置键，如 'ai_config', 'bot_config'",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_system_configs_tenant_id"), table_name="system_configs")
    op.drop_index(op.f("ix_tenant_ee_configs_tenant_id"), table_name="tenant_ee_configs")
    op.create_index(op.f("ix_tenant_ee_configs_id"), "tenant_ee_configs", ["id"], unique=False)
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.drop_index(op.f("ix_tenant_ee_configs_id"), table_name="tenant_ee_configs")
    op.create_index(
        op.f("ix_tenant_ee_configs_tenant_id"), "tenant_ee_configs", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_system_configs_tenant_id"), "system_configs", ["tenant_id"], unique=False
    )
    op.alter_column(
        "system_configs",
        "config_key",
        existing_type=sa.VARCHAR(length=100),
        comment="配置键，如 'ai_config', 'bot_config'",
        existing_comment="配置键，如 'ai_config'",
        existing_nullable=False,
    )
    op.alter_column(
        "system_configs",
        "tenant_id",
        existing_type=sa.INTEGER(),
        comment="所属租户ID(null=平台全局配置)",
        existing_comment="所属租户ID(null表示平台全局配置)",
        existing_nullable=True,
    )
    op.create_index(op.f("ix_sites_tenant_id"), "sites", ["tenant_id"], unique=False)
    op.drop_index(op.f("ix_site_ee_configs_id"), table_name="site_ee_configs")
    op.create_index(
        op.f("ix_site_ee_configs_site_id"), "site_ee_configs", ["site_id"], unique=False
    )
    op.drop_index(op.f("ix_document_view_events_tenant_id"), table_name="document_view_events")
    op.drop_index(op.f("ix_document_view_events_member_id"), table_name="document_view_events")
    op.drop_index(op.f("ix_document_view_events_document_id"), table_name="document_view_events")
    op.create_index(
        op.f("idx_view_events_member"), "document_view_events", ["member_id"], unique=False
    )
    op.alter_column(
        "document_view_events",
        "tenant_id",
        existing_type=sa.INTEGER(),
        comment="所属租户ID",
        existing_nullable=False,
    )
    op.drop_column("document", "parse_meta")
    op.drop_index(op.f("ix_chat_sessions_id"), table_name="chat_sessions")
    op.create_index(
        op.f("ix_chat_sessions_updated_at"), "chat_sessions", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_chat_sessions_tenant_id"), "chat_sessions", ["tenant_id"], unique=False
    )
    op.alter_column(
        "chat_sessions",
        "message_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        comment="消息数量",
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "chat_sessions",
        "last_message_role",
        existing_type=sa.VARCHAR(length=20),
        comment="最后消息角色 user/assistant",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_sessions",
        "last_message",
        existing_type=sa.TEXT(),
        comment="最后消息预览",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_sessions",
        "title",
        existing_type=sa.VARCHAR(length=255),
        comment="会话标题",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_sessions",
        "member_id",
        existing_type=sa.VARCHAR(length=255),
        comment="会员ID或访客标识（可选，支持匿名）",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_sessions",
        "site_id",
        existing_type=sa.INTEGER(),
        comment="站点ID",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_sessions",
        "thread_id",
        existing_type=sa.VARCHAR(length=255),
        comment="LangGraph Checkpointer thread_id",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
