"""initial_schema_and_admin_user

Revision ID: d161a6891c2d
Revises:
Create Date: 2025-12-30 21:01:25.687934

"""
import hashlib
import secrets
from datetime import UTC, datetime

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd161a6891c2d'
down_revision = None
branch_labels = None
depends_on = None



def upgrade() -> None:
    # Enable vector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('title', sa.String(length=200), nullable=False, comment='合集名称'),
    sa.Column('site_id', sa.Integer(), nullable=False, comment='所属站点ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父合集ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_id'), 'collection', ['id'], unique=False)
    op.create_index(op.f('ix_collection_parent_id'), 'collection', ['parent_id'], unique=False)
    op.create_index(op.f('ix_collection_site_id'), 'collection', ['site_id'], unique=False)
    op.create_index(op.f('ix_collection_title'), 'collection', ['title'], unique=False)
    op.create_table('document',
    sa.Column('title', sa.String(length=200), nullable=False, comment='文章标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='文章内容(Markdown)'),
    sa.Column('summary', sa.Text(), nullable=True, comment='文章摘要'),
    sa.Column('cover_image', sa.String(length=500), nullable=True, comment='封面图片URL'),
    sa.Column('site_id', sa.Integer(), nullable=False, comment='所属站点ID'),
    sa.Column('collection_id', sa.Integer(), nullable=True, comment='所属合集ID'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='分类'),
    sa.Column('author', sa.String(length=100), nullable=False, comment='作者'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: published, draft'),
    sa.Column('vector_status', sa.String(length=20), nullable=False, server_default='none', comment='向量化状态: none, pending, processing, completed, failed'),
    sa.Column('vector_error', sa.Text(), nullable=True, comment='向量化失败错误信息'),
    sa.Column('vectorized_at', sa.DateTime(timezone=True), nullable=True, comment='最后向量化完成时间'),
    sa.Column('views', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('reading_time', sa.Integer(), nullable=False, comment='预计阅读时间(分钟)'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_collection_id'), 'document', ['collection_id'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_site_id'), 'document', ['site_id'], unique=False)
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    op.create_index(op.f('ix_document_vector_status'), 'document', ['vector_status'], unique=False)
    op.create_table('system_configs',
    sa.Column('config_key', sa.String(length=100), nullable=False, comment="配置键，如 'ai_config', 'bot_config'"),
    sa.Column('config_value', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='配置值（JSON 格式）'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='配置项描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用该配置'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('role', sa.Enum('ADMIN', 'SITE_ADMIN', 'EDITOR', name='userrole', native_enum=False, length=20), nullable=False, comment='用户角色'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', name='userstatus', native_enum=False, length=20), nullable=False, comment='用户状态'),
    sa.Column('managed_site_ids', sa.String(length=500), nullable=True, comment='管理的站点ID列表，逗号分隔'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('name', sa.String(length=100), nullable=False, comment='站点名称'),
    sa.Column('domain', sa.String(length=200), nullable=True, comment='站点域名'),
    sa.Column('description', sa.Text(), nullable=True, comment='站点描述'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标名称'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active(激活), disabled(禁用)'),
    sa.Column('article_count', sa.Integer(), nullable=False, comment='文章数量'),
    sa.Column('theme_color', sa.String(length=50), nullable=True, comment='主题色'),
    sa.Column('layout_mode', sa.String(length=20), nullable=True, comment='布局模式: sidebar, top'),
    sa.Column('quick_questions', sa.JSON(), nullable=True, comment='快速问题配置，JSON数组格式'),
    sa.Column('bot_config', sa.JSON(), nullable=True, comment='机器人配置，包含网页挂件、API等'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    # ### end Alembic commands ###

    # 数据迁移：创建默认管理员用户
    _create_default_admin_user()
    # 数据迁移：创建 Demo 站点
    _create_demo_site()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 数据迁移：删除默认管理员用户
    _delete_default_admin_user()

    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_document_vector_status'), table_name='document')
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_index(op.f('ix_document_site_id'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index(op.f('ix_document_collection_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_collection_title'), table_name='collection')
    op.drop_index(op.f('ix_collection_site_id'), table_name='collection')
    op.drop_index(op.f('ix_collection_parent_id'), table_name='collection')
    op.drop_index(op.f('ix_collection_id'), table_name='collection')
    op.drop_table('collection')
    # ### end Alembic commands ###

    # Drop vector extension
    op.execute("DROP EXTENSION IF EXISTS vector")


def _get_password_hash(password: str) -> str:
    """
    生成密码哈希
    使用 SHA256 + salt
    """
    salt = secrets.token_hex(16)
    hash_value = hashlib.sha256((salt + password).encode()).hexdigest()
    return f"{salt}${hash_value}"


def _create_default_admin_user() -> None:
    """
    创建默认管理员用户
    邮箱: admin@example.com
    密码: admin123
    """
    # 创建 users 表的引用（DateTime 需要指定 timezone=True 以匹配实际表定义）
    users_table = sa.table(
        'users',
        sa.column('name', sa.String),
        sa.column('email', sa.String),
        sa.column('password_hash', sa.String),
        sa.column('role', sa.String),
        sa.column('status', sa.String),
        sa.column('managed_site_ids', sa.String),
        sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )

    # 检查管理员用户是否已存在
    conn = op.get_bind()
    result = conn.execute(
        sa.text("SELECT COUNT(*) FROM users WHERE email = :email"),
        {"email": "admin@example.com"}
    )
    count = result.scalar()

    # 如果不存在，则创建
    if count == 0:
        now = datetime.now(UTC)
        op.bulk_insert(
            users_table,
            [
                {
                    'name': 'Admin',
                    'email': 'admin@example.com',
                    'password_hash': _get_password_hash('admin123'),
                    'role': 'ADMIN',
                    'status': 'ACTIVE',
                    'managed_site_ids': '',
                    'created_at': now,
                    'updated_at': now,
                }
            ]
        )
        print("✅ 创建默认管理员用户：admin@example.com / admin123")
    else:
        print("⚠️  管理员用户已存在，跳过创建")


def _delete_default_admin_user() -> None:
    """
    删除默认管理员用户
    """
    conn = op.get_bind()
    conn.execute(
        sa.text("DELETE FROM users WHERE email = :email"),
        {"email": "admin@example.com"}
    )
    print("🗑️  删除默认管理员用户：admin@example.com")


def _create_demo_site() -> None:
    """
    创建 Demo 站点及初始化快速问题
    """
    sites_table = sa.table(
        'sites',
        sa.column('name', sa.String),
        sa.column('domain', sa.String),
        sa.column('description', sa.String),
        sa.column('icon', sa.String),
        sa.column('status', sa.String),
        sa.column('article_count', sa.Integer),
        sa.column('theme_color', sa.String),
        sa.column('layout_mode', sa.String),
        sa.column('quick_questions', sa.JSON),
        sa.column('bot_config', sa.JSON),
        sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )

    # 检查 Demo 站点是否已存在
    conn = op.get_bind()
    result = conn.execute(
        sa.text("SELECT COUNT(*) FROM sites WHERE domain = :domain"),
        {"domain": "medical"}
    )
    count = result.scalar()

    if count == 0:
        now = datetime.now(UTC)
        quick_questions = [
            {"text": "高血压有哪些危害？", "category": "常见疾病"},
            {"text": "如何进行心肺复苏？", "category": "急救知识"},
            {"text": "日常饮食应该注意什么？", "category": "健康生活"}
        ]
        
        op.bulk_insert(
            sites_table,
            [
                {
                    'name': '医学科普',
                    'domain': 'medical',
                    'description': '医学知识科普站点，提供常见疾病、健康生活、急救知识等内容',
                    'icon': 'medical',
                    'status': 'active',
                    'article_count': 0,
                    'theme_color': 'blue',
                    'layout_mode': 'sidebar',
                    'quick_questions': quick_questions,
                    'created_at': now,
                    'updated_at': now,
                }
            ]
        )
        print("✅ 创建 Demo 站点及其快速问题配置")
    else:
        print("⚠️  Demo 站点已存在，跳过创建")


