/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.5
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClearAdminCache200,
  GetAdminCacheStats200
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetAdminCacheStatsUrl = () => {




  return `/admin/v1/cache:stats`
}

/**
 * 获取缓存统计信息
 * @summary Get Cache Stats
 */
export const getAdminCacheStats = async ( options?: RequestInit): Promise<GetAdminCacheStats200> => {

  return customFetch<GetAdminCacheStats200>(getGetAdminCacheStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminCacheStatsQueryKey = () => {
    return [
    `/admin/v1/cache:stats`
    ] as const;
    }


export const getGetAdminCacheStatsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminCacheStats>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCacheStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminCacheStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminCacheStats>>> = ({ signal }) => getAdminCacheStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminCacheStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminCacheStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminCacheStats>>>
export type GetAdminCacheStatsQueryError = unknown


export function useGetAdminCacheStats<TData = Awaited<ReturnType<typeof getAdminCacheStats>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCacheStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCacheStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminCacheStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCacheStats<TData = Awaited<ReturnType<typeof getAdminCacheStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCacheStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCacheStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminCacheStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCacheStats<TData = Awaited<ReturnType<typeof getAdminCacheStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCacheStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Cache Stats
 */

export function useGetAdminCacheStats<TData = Awaited<ReturnType<typeof getAdminCacheStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCacheStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminCacheStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getClearAdminCacheUrl = () => {




  return `/admin/v1/cache:clear`
}

/**
 * 清空所有缓存
 * @summary Clear Cache
 */
export const clearAdminCache = async ( options?: RequestInit): Promise<ClearAdminCache200> => {

  return customFetch<ClearAdminCache200>(getClearAdminCacheUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getClearAdminCacheMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearAdminCache>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof clearAdminCache>>, TError,void, TContext> => {

const mutationKey = ['clearAdminCache'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clearAdminCache>>, void> = () => {


          return  clearAdminCache(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClearAdminCacheMutationResult = NonNullable<Awaited<ReturnType<typeof clearAdminCache>>>

    export type ClearAdminCacheMutationError = unknown

    /**
 * @summary Clear Cache
 */
export const useClearAdminCache = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearAdminCache>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clearAdminCache>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getClearAdminCacheMutationOptions(options), queryClient);
    }
