/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.5
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteAdminUser200,
  HTTPValidationError,
  ListAdminUsersParams,
  PaginatedResponseUserListItem,
  UpdateAdminUserPassword200,
  UserCreate,
  UserInvite,
  UserLogin,
  UserLoginResponse,
  UserResponse,
  UserUpdate,
  UserUpdatePassword
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListAdminUsersUrl = (params?: ListAdminUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/users?${stringifiedParams}` : `/admin/v1/users`
}

/**
 * 获取用户列表

- **page**: 页码
- **size**: 每页数量
- **role**: 角色筛选 (admin/tenant_admin/site_admin)
- **status**: 状态筛选 (active/inactive/pending)
- **search**: 搜索关键词（匹配用户名或邮箱）
- **site_id**: 站点ID筛选
- **order_by**: 排序字段
- **order_dir**: 排序方向 (asc/desc)
 * @summary List Users
 */
export const listAdminUsers = async (params?: ListAdminUsersParams, options?: RequestInit): Promise<PaginatedResponseUserListItem | null> => {

  return customFetch<PaginatedResponseUserListItem | null>(getListAdminUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAdminUsersQueryKey = (params?: ListAdminUsersParams,) => {
    return [
    `/admin/v1/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAdminUsersQueryOptions = <TData = Awaited<ReturnType<typeof listAdminUsers>>, TError = HTTPValidationError>(params?: ListAdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminUsers>>> = ({ signal }) => listAdminUsers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminUsers>>>
export type ListAdminUsersQueryError = HTTPValidationError


export function useListAdminUsers<TData = Awaited<ReturnType<typeof listAdminUsers>>, TError = HTTPValidationError>(
 params: undefined |  ListAdminUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminUsers>>,
          TError,
          Awaited<ReturnType<typeof listAdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminUsers<TData = Awaited<ReturnType<typeof listAdminUsers>>, TError = HTTPValidationError>(
 params?: ListAdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminUsers>>,
          TError,
          Awaited<ReturnType<typeof listAdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminUsers<TData = Awaited<ReturnType<typeof listAdminUsers>>, TError = HTTPValidationError>(
 params?: ListAdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Users
 */

export function useListAdminUsers<TData = Awaited<ReturnType<typeof listAdminUsers>>, TError = HTTPValidationError>(
 params?: ListAdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateAdminUserUrl = () => {




  return `/admin/v1/users`
}

/**
 * 创建用户

- **name**: 用户名
- **email**: 邮箱
- **password**: 密码（至少6位）
- **role**: 角色（默认为 site_admin）
- **managed_site_ids**: 管理的站点ID列表
- **avatar_url**: 头像URL（可选）
 * @summary Create User
 */
export const createAdminUser = async (userCreate: UserCreate, options?: RequestInit): Promise<UserResponse | null> => {

  return customFetch<UserResponse | null>(getCreateAdminUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userCreate)
  }
);}




export const getCreateAdminUserMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminUser>>, TError,{data: UserCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createAdminUser>>, TError,{data: UserCreate}, TContext> => {

const mutationKey = ['createAdminUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdminUser>>, {data: UserCreate}> = (props) => {
          const {data} = props ?? {};

          return  createAdminUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAdminUserMutationResult = NonNullable<Awaited<ReturnType<typeof createAdminUser>>>
    export type CreateAdminUserMutationBody = UserCreate
    export type CreateAdminUserMutationError = HTTPValidationError

    /**
 * @summary Create User
 */
export const useCreateAdminUser = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminUser>>, TError,{data: UserCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAdminUser>>,
        TError,
        {data: UserCreate},
        TContext
      > => {
      return useMutation(getCreateAdminUserMutationOptions(options), queryClient);
    }
    export const getGetAdminUserUrl = (userId: number,) => {




  return `/admin/v1/users/${userId}`
}

/**
 * 获取用户详情
 * @summary Get User
 */
export const getAdminUser = async (userId: number, options?: RequestInit): Promise<UserResponse | null> => {

  return customFetch<UserResponse | null>(getGetAdminUserUrl(userId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminUserQueryKey = (userId: number,) => {
    return [
    `/admin/v1/users/${userId}`
    ] as const;
    }


export const getGetAdminUserQueryOptions = <TData = Awaited<ReturnType<typeof getAdminUser>>, TError = HTTPValidationError>(userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUser>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminUserQueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminUser>>> = ({ signal }) => getAdminUser(userId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminUserQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminUser>>>
export type GetAdminUserQueryError = HTTPValidationError


export function useGetAdminUser<TData = Awaited<ReturnType<typeof getAdminUser>>, TError = HTTPValidationError>(
 userId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminUser>>,
          TError,
          Awaited<ReturnType<typeof getAdminUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminUser<TData = Awaited<ReturnType<typeof getAdminUser>>, TError = HTTPValidationError>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminUser>>,
          TError,
          Awaited<ReturnType<typeof getAdminUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminUser<TData = Awaited<ReturnType<typeof getAdminUser>>, TError = HTTPValidationError>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUser>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User
 */

export function useGetAdminUser<TData = Awaited<ReturnType<typeof getAdminUser>>, TError = HTTPValidationError>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUser>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminUserQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateAdminUserUrl = (userId: number,) => {




  return `/admin/v1/users/${userId}`
}

/**
 * 更新用户信息

- **name**: 用户名
- **email**: 邮箱
- **role**: 角色
- **managed_site_ids**: 管理的站点ID列表
- **status**: 状态
- **avatar_url**: 头像URL
 * @summary Update User
 */
export const updateAdminUser = async (userId: number,
    userUpdate: UserUpdate, options?: RequestInit): Promise<UserResponse | null> => {

  return customFetch<UserResponse | null>(getUpdateAdminUserUrl(userId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdate)
  }
);}




export const getUpdateAdminUserMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminUser>>, TError,{userId: number;data: UserUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminUser>>, TError,{userId: number;data: UserUpdate}, TContext> => {

const mutationKey = ['updateAdminUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminUser>>, {userId: number;data: UserUpdate}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateAdminUser(userId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminUser>>>
    export type UpdateAdminUserMutationBody = UserUpdate
    export type UpdateAdminUserMutationError = HTTPValidationError

    /**
 * @summary Update User
 */
export const useUpdateAdminUser = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminUser>>, TError,{userId: number;data: UserUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminUser>>,
        TError,
        {userId: number;data: UserUpdate},
        TContext
      > => {
      return useMutation(getUpdateAdminUserMutationOptions(options), queryClient);
    }
    export const getDeleteAdminUserUrl = (userId: number,) => {




  return `/admin/v1/users/${userId}`
}

/**
 * 删除用户
 * @summary Delete User
 */
export const deleteAdminUser = async (userId: number, options?: RequestInit): Promise<DeleteAdminUser200> => {

  return customFetch<DeleteAdminUser200>(getDeleteAdminUserUrl(userId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAdminUserMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminUser>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminUser>>, TError,{userId: number}, TContext> => {

const mutationKey = ['deleteAdminUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminUser>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  deleteAdminUser(userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminUser>>>

    export type DeleteAdminUserMutationError = HTTPValidationError

    /**
 * @summary Delete User
 */
export const useDeleteAdminUser = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminUser>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminUser>>,
        TError,
        {userId: number},
        TContext
      > => {
      return useMutation(getDeleteAdminUserMutationOptions(options), queryClient);
    }
    export const getInviteAdminUserUrl = () => {




  return `/admin/v1/users:invite`
}

/**
 * 邀请用户（直接创建用户并返回临时密码）

- **email**: 邮箱
- **role**: 角色（默认为 site_admin）
- **managed_site_ids**: 管理的站点ID列表

返回创建的用户信息和临时密码
 * @summary Invite User
 */
export const inviteAdminUser = async (userInvite: UserInvite, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getInviteAdminUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userInvite)
  }
);}




export const getInviteAdminUserMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inviteAdminUser>>, TError,{data: UserInvite}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof inviteAdminUser>>, TError,{data: UserInvite}, TContext> => {

const mutationKey = ['inviteAdminUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inviteAdminUser>>, {data: UserInvite}> = (props) => {
          const {data} = props ?? {};

          return  inviteAdminUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InviteAdminUserMutationResult = NonNullable<Awaited<ReturnType<typeof inviteAdminUser>>>
    export type InviteAdminUserMutationBody = UserInvite
    export type InviteAdminUserMutationError = HTTPValidationError

    /**
 * @summary Invite User
 */
export const useInviteAdminUser = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inviteAdminUser>>, TError,{data: UserInvite}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inviteAdminUser>>,
        TError,
        {data: UserInvite},
        TContext
      > => {
      return useMutation(getInviteAdminUserMutationOptions(options), queryClient);
    }
    export const getUpdateAdminUserPasswordUrl = (userId: number,) => {




  return `/admin/v1/users/${userId}/password`
}

/**
 * 更新用户密码
 * @summary Update User Password
 */
export const updateAdminUserPassword = async (userId: number,
    userUpdatePassword: UserUpdatePassword, options?: RequestInit): Promise<UpdateAdminUserPassword200> => {

  return customFetch<UpdateAdminUserPassword200>(getUpdateAdminUserPasswordUrl(userId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdatePassword)
  }
);}




export const getUpdateAdminUserPasswordMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminUserPassword>>, TError,{userId: number;data: UserUpdatePassword}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminUserPassword>>, TError,{userId: number;data: UserUpdatePassword}, TContext> => {

const mutationKey = ['updateAdminUserPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminUserPassword>>, {userId: number;data: UserUpdatePassword}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateAdminUserPassword(userId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminUserPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminUserPassword>>>
    export type UpdateAdminUserPasswordMutationBody = UserUpdatePassword
    export type UpdateAdminUserPasswordMutationError = HTTPValidationError

    /**
 * @summary Update User Password
 */
export const useUpdateAdminUserPassword = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminUserPassword>>, TError,{userId: number;data: UserUpdatePassword}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminUserPassword>>,
        TError,
        {userId: number;data: UserUpdatePassword},
        TContext
      > => {
      return useMutation(getUpdateAdminUserPasswordMutationOptions(options), queryClient);
    }
    export const getResetAdminUserPasswordUrl = (userId: number,) => {




  return `/admin/v1/users/${userId}:resetPassword`
}

/**
 * Reset user password (generate random temporary password)

- Admin can reset password for any user
- Returns randomly generated temporary password
 * @summary Reset User Password
 */
export const resetAdminUserPassword = async (userId: number, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getResetAdminUserPasswordUrl(userId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getResetAdminUserPasswordMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetAdminUserPassword>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof resetAdminUserPassword>>, TError,{userId: number}, TContext> => {

const mutationKey = ['resetAdminUserPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetAdminUserPassword>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  resetAdminUserPassword(userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResetAdminUserPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetAdminUserPassword>>>

    export type ResetAdminUserPasswordMutationError = HTTPValidationError

    /**
 * @summary Reset User Password
 */
export const useResetAdminUserPassword = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetAdminUserPassword>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetAdminUserPassword>>,
        TError,
        {userId: number},
        TContext
      > => {
      return useMutation(getResetAdminUserPasswordMutationOptions(options), queryClient);
    }
    export const getLoginAdminUrl = () => {




  return `/admin/v1/users:login`
}

/**
 * 用户登录

- **email**: 邮箱
- **password**: 密码
 * @summary Login
 */
export const loginAdmin = async (userLogin: UserLogin, options?: RequestInit): Promise<UserLoginResponse | null> => {

  return customFetch<UserLoginResponse | null>(getLoginAdminUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userLogin)
  }
);}




export const getLoginAdminMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAdmin>>, TError,{data: UserLogin}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof loginAdmin>>, TError,{data: UserLogin}, TContext> => {

const mutationKey = ['loginAdmin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginAdmin>>, {data: UserLogin}> = (props) => {
          const {data} = props ?? {};

          return  loginAdmin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginAdminMutationResult = NonNullable<Awaited<ReturnType<typeof loginAdmin>>>
    export type LoginAdminMutationBody = UserLogin
    export type LoginAdminMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginAdmin = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAdmin>>, TError,{data: UserLogin}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginAdmin>>,
        TError,
        {data: UserLogin},
        TContext
      > => {
      return useMutation(getLoginAdminMutationOptions(options), queryClient);
    }
