/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.6
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListAdminTasksParams,
  PaginatedResponseTask,
  Task
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListAdminTasksUrl = (params?: ListAdminTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/tasks?${stringifiedParams}` : `/admin/v1/tasks`
}

/**
 * 获取异步任务列表
 * @summary List Tasks
 */
export const listAdminTasks = async (params?: ListAdminTasksParams, options?: RequestInit): Promise<PaginatedResponseTask | null> => {

  return customFetch<PaginatedResponseTask | null>(getListAdminTasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAdminTasksQueryKey = (params?: ListAdminTasksParams,) => {
    return [
    `/admin/v1/tasks`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAdminTasksQueryOptions = <TData = Awaited<ReturnType<typeof listAdminTasks>>, TError = HTTPValidationError>(params?: ListAdminTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminTasksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminTasks>>> = ({ signal }) => listAdminTasks(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminTasksQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminTasks>>>
export type ListAdminTasksQueryError = HTTPValidationError


export function useListAdminTasks<TData = Awaited<ReturnType<typeof listAdminTasks>>, TError = HTTPValidationError>(
 params: undefined |  ListAdminTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminTasks>>,
          TError,
          Awaited<ReturnType<typeof listAdminTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminTasks<TData = Awaited<ReturnType<typeof listAdminTasks>>, TError = HTTPValidationError>(
 params?: ListAdminTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminTasks>>,
          TError,
          Awaited<ReturnType<typeof listAdminTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminTasks<TData = Awaited<ReturnType<typeof listAdminTasks>>, TError = HTTPValidationError>(
 params?: ListAdminTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Tasks
 */

export function useListAdminTasks<TData = Awaited<ReturnType<typeof listAdminTasks>>, TError = HTTPValidationError>(
 params?: ListAdminTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetAdminTaskUrl = (taskId: number,) => {




  return `/admin/v1/tasks/${taskId}`
}

/**
 * 获取单个任务详情和状态
 * @summary Get Task Status
 */
export const getAdminTask = async (taskId: number, options?: RequestInit): Promise<Task | null> => {

  return customFetch<Task | null>(getGetAdminTaskUrl(taskId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminTaskQueryKey = (taskId: number,) => {
    return [
    `/admin/v1/tasks/${taskId}`
    ] as const;
    }


export const getGetAdminTaskQueryOptions = <TData = Awaited<ReturnType<typeof getAdminTask>>, TError = HTTPValidationError>(taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminTaskQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminTask>>> = ({ signal }) => getAdminTask(taskId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: taskId !== null && taskId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminTask>>>
export type GetAdminTaskQueryError = HTTPValidationError


export function useGetAdminTask<TData = Awaited<ReturnType<typeof getAdminTask>>, TError = HTTPValidationError>(
 taskId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTask>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTask>>,
          TError,
          Awaited<ReturnType<typeof getAdminTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminTask<TData = Awaited<ReturnType<typeof getAdminTask>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTask>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTask>>,
          TError,
          Awaited<ReturnType<typeof getAdminTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminTask<TData = Awaited<ReturnType<typeof getAdminTask>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Task Status
 */

export function useGetAdminTask<TData = Awaited<ReturnType<typeof getAdminTask>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminTaskQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






