/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.5
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminSiteStatsParams,
  HTTPValidationError,
  SiteStats
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetAdminSiteStatsUrl = (params: GetAdminSiteStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/stats:siteStats?${stringifiedParams}` : `/admin/v1/stats:siteStats`
}

/**
 * 获取站点统计数据

返回:
    - total_documents: 文档总数
    - total_views: 总访问次数
 * @summary Get Site Stats
 */
export const getAdminSiteStats = async (params: GetAdminSiteStatsParams, options?: RequestInit): Promise<SiteStats | null> => {

  return customFetch<SiteStats | null>(getGetAdminSiteStatsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminSiteStatsQueryKey = (params?: GetAdminSiteStatsParams,) => {
    return [
    `/admin/v1/stats:siteStats`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminSiteStatsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSiteStats>>, TError = HTTPValidationError>(params: GetAdminSiteStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSiteStatsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSiteStats>>> = ({ signal }) => getAdminSiteStats(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminSiteStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSiteStats>>>
export type GetAdminSiteStatsQueryError = HTTPValidationError


export function useGetAdminSiteStats<TData = Awaited<ReturnType<typeof getAdminSiteStats>>, TError = HTTPValidationError>(
 params: GetAdminSiteStatsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSiteStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminSiteStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSiteStats<TData = Awaited<ReturnType<typeof getAdminSiteStats>>, TError = HTTPValidationError>(
 params: GetAdminSiteStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSiteStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminSiteStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSiteStats<TData = Awaited<ReturnType<typeof getAdminSiteStats>>, TError = HTTPValidationError>(
 params: GetAdminSiteStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Site Stats
 */

export function useGetAdminSiteStats<TData = Awaited<ReturnType<typeof getAdminSiteStats>>, TError = HTTPValidationError>(
 params: GetAdminSiteStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminSiteStatsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






