/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.7
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AiGenerateRequest,
  AiGenerateResponse,
  BodyImportDocument,
  Document,
  DocumentCreate,
  DocumentUpdate,
  GetAdminDocumentChunks200,
  HTTPValidationError,
  ListAdminDocumentsParams,
  PaginatedResponseDocument,
  Task,
  VectorRetrieveRequest,
  VectorRetrieveResult,
  VectorizeRequest,
  VectorizeResponse
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListAdminDocumentsUrl = (params?: ListAdminDocumentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/documents?${stringifiedParams}` : `/admin/v1/documents`
}

/**
 * @summary List Documents
 */
export const listAdminDocuments = async (params?: ListAdminDocumentsParams, options?: RequestInit): Promise<PaginatedResponseDocument | null> => {

  return customFetch<PaginatedResponseDocument | null>(getListAdminDocumentsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAdminDocumentsQueryKey = (params?: ListAdminDocumentsParams,) => {
    return [
    `/admin/v1/documents`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAdminDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof listAdminDocuments>>, TError = HTTPValidationError>(params?: ListAdminDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminDocuments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminDocumentsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminDocuments>>> = ({ signal }) => listAdminDocuments(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminDocuments>>>
export type ListAdminDocumentsQueryError = HTTPValidationError


export function useListAdminDocuments<TData = Awaited<ReturnType<typeof listAdminDocuments>>, TError = HTTPValidationError>(
 params: undefined |  ListAdminDocumentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminDocuments>>,
          TError,
          Awaited<ReturnType<typeof listAdminDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminDocuments<TData = Awaited<ReturnType<typeof listAdminDocuments>>, TError = HTTPValidationError>(
 params?: ListAdminDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminDocuments>>,
          TError,
          Awaited<ReturnType<typeof listAdminDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminDocuments<TData = Awaited<ReturnType<typeof listAdminDocuments>>, TError = HTTPValidationError>(
 params?: ListAdminDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminDocuments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Documents
 */

export function useListAdminDocuments<TData = Awaited<ReturnType<typeof listAdminDocuments>>, TError = HTTPValidationError>(
 params?: ListAdminDocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminDocuments>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminDocumentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateAdminDocumentUrl = () => {




  return `/admin/v1/documents`
}

/**
 * @summary Create Document
 */
export const createAdminDocument = async (documentCreate: DocumentCreate, options?: RequestInit): Promise<Document | null> => {

  return customFetch<Document | null>(getCreateAdminDocumentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(documentCreate)
  }
);}




export const getCreateAdminDocumentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminDocument>>, TError,{data: DocumentCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createAdminDocument>>, TError,{data: DocumentCreate}, TContext> => {

const mutationKey = ['createAdminDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdminDocument>>, {data: DocumentCreate}> = (props) => {
          const {data} = props ?? {};

          return  createAdminDocument(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAdminDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof createAdminDocument>>>
    export type CreateAdminDocumentMutationBody = DocumentCreate
    export type CreateAdminDocumentMutationError = HTTPValidationError

    /**
 * @summary Create Document
 */
export const useCreateAdminDocument = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminDocument>>, TError,{data: DocumentCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAdminDocument>>,
        TError,
        {data: DocumentCreate},
        TContext
      > => {
      return useMutation(getCreateAdminDocumentMutationOptions(options), queryClient);
    }
    export const getGetAdminDocumentUrl = (documentId: number,) => {




  return `/admin/v1/documents/${documentId}`
}

/**
 * @summary Get Document
 */
export const getAdminDocument = async (documentId: number, options?: RequestInit): Promise<Document | null> => {

  return customFetch<Document | null>(getGetAdminDocumentUrl(documentId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminDocumentQueryKey = (documentId: number,) => {
    return [
    `/admin/v1/documents/${documentId}`
    ] as const;
    }


export const getGetAdminDocumentQueryOptions = <TData = Awaited<ReturnType<typeof getAdminDocument>>, TError = HTTPValidationError>(documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocument>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminDocumentQueryKey(documentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminDocument>>> = ({ signal }) => getAdminDocument(documentId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: documentId !== null && documentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminDocument>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminDocument>>>
export type GetAdminDocumentQueryError = HTTPValidationError


export function useGetAdminDocument<TData = Awaited<ReturnType<typeof getAdminDocument>>, TError = HTTPValidationError>(
 documentId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocument>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDocument>>,
          TError,
          Awaited<ReturnType<typeof getAdminDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminDocument<TData = Awaited<ReturnType<typeof getAdminDocument>>, TError = HTTPValidationError>(
 documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocument>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDocument>>,
          TError,
          Awaited<ReturnType<typeof getAdminDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminDocument<TData = Awaited<ReturnType<typeof getAdminDocument>>, TError = HTTPValidationError>(
 documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocument>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document
 */

export function useGetAdminDocument<TData = Awaited<ReturnType<typeof getAdminDocument>>, TError = HTTPValidationError>(
 documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocument>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminDocumentQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateAdminDocumentUrl = (documentId: number,) => {




  return `/admin/v1/documents/${documentId}`
}

/**
 * @summary Update Document
 */
export const updateAdminDocument = async (documentId: number,
    documentUpdate: DocumentUpdate, options?: RequestInit): Promise<Document | null> => {

  return customFetch<Document | null>(getUpdateAdminDocumentUrl(documentId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(documentUpdate)
  }
);}




export const getUpdateAdminDocumentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminDocument>>, TError,{documentId: number;data: DocumentUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminDocument>>, TError,{documentId: number;data: DocumentUpdate}, TContext> => {

const mutationKey = ['updateAdminDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminDocument>>, {documentId: number;data: DocumentUpdate}> = (props) => {
          const {documentId,data} = props ?? {};

          return  updateAdminDocument(documentId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminDocument>>>
    export type UpdateAdminDocumentMutationBody = DocumentUpdate
    export type UpdateAdminDocumentMutationError = HTTPValidationError

    /**
 * @summary Update Document
 */
export const useUpdateAdminDocument = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminDocument>>, TError,{documentId: number;data: DocumentUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminDocument>>,
        TError,
        {documentId: number;data: DocumentUpdate},
        TContext
      > => {
      return useMutation(getUpdateAdminDocumentMutationOptions(options), queryClient);
    }
    export const getDeleteAdminDocumentUrl = (documentId: number,) => {




  return `/admin/v1/documents/${documentId}`
}

/**
 * @summary Delete Document
 */
export const deleteAdminDocument = async (documentId: number, options?: RequestInit): Promise<null> => {

  return customFetch<null>(getDeleteAdminDocumentUrl(documentId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAdminDocumentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminDocument>>, TError,{documentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminDocument>>, TError,{documentId: number}, TContext> => {

const mutationKey = ['deleteAdminDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminDocument>>, {documentId: number}> = (props) => {
          const {documentId} = props ?? {};

          return  deleteAdminDocument(documentId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminDocument>>>

    export type DeleteAdminDocumentMutationError = HTTPValidationError

    /**
 * @summary Delete Document
 */
export const useDeleteAdminDocument = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminDocument>>, TError,{documentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminDocument>>,
        TError,
        {documentId: number},
        TContext
      > => {
      return useMutation(getDeleteAdminDocumentMutationOptions(options), queryClient);
    }
    export const getImportDocumentUrl = () => {




  return `/admin/v1/documents:import`
}

/**
 * 导入文档 (上传 -> 异步解析 -> 创建)
duplicate_strategy: "skip" = 已存在则跳过, "allow" = 不检测直接上传（默认）
auto_vectorize: 解析完成后是否自动入向量库（链一个向量化任务）
 * @summary Import Document
 */
export const importDocument = async (bodyImportDocument: BodyImportDocument, options?: RequestInit): Promise<Task | null> => {
    const formData = new FormData();
formData.append(`file`, bodyImportDocument.file);
formData.append(`site_id`, bodyImportDocument.site_id.toString())
formData.append(`collection_id`, bodyImportDocument.collection_id.toString())
if(bodyImportDocument.processor_type !== undefined) {
 formData.append(`processor_type`, bodyImportDocument.processor_type);
 }
if(bodyImportDocument.ocr_enabled !== undefined) {
 formData.append(`ocr_enabled`, bodyImportDocument.ocr_enabled.toString())
 }
if(bodyImportDocument.extract_images !== undefined) {
 formData.append(`extract_images`, bodyImportDocument.extract_images.toString())
 }
if(bodyImportDocument.extract_tables !== undefined) {
 formData.append(`extract_tables`, bodyImportDocument.extract_tables.toString())
 }
if(bodyImportDocument.duplicate_strategy !== undefined) {
 formData.append(`duplicate_strategy`, bodyImportDocument.duplicate_strategy);
 }
if(bodyImportDocument.generate_summary !== undefined) {
 formData.append(`generate_summary`, bodyImportDocument.generate_summary.toString())
 }
if(bodyImportDocument.generate_tags !== undefined) {
 formData.append(`generate_tags`, bodyImportDocument.generate_tags.toString())
 }
if(bodyImportDocument.auto_vectorize !== undefined) {
 formData.append(`auto_vectorize`, bodyImportDocument.auto_vectorize.toString())
 }

  return customFetch<Task | null>(getImportDocumentUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}




export const getImportDocumentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importDocument>>, TError,{data: BodyImportDocument}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof importDocument>>, TError,{data: BodyImportDocument}, TContext> => {

const mutationKey = ['importDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importDocument>>, {data: BodyImportDocument}> = (props) => {
          const {data} = props ?? {};

          return  importDocument(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ImportDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof importDocument>>>
    export type ImportDocumentMutationBody = BodyImportDocument
    export type ImportDocumentMutationError = HTTPValidationError

    /**
 * @summary Import Document
 */
export const useImportDocument = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importDocument>>, TError,{data: BodyImportDocument}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importDocument>>,
        TError,
        {data: BodyImportDocument},
        TContext
      > => {
      return useMutation(getImportDocumentMutationOptions(options), queryClient);
    }
    export const getBatchVectorizeAdminDocumentsUrl = () => {




  return `/admin/v1/documents:batchVectorize`
}

/**
 * 批量向量化文档（将文档状态设置为 pending，并启动向量化后台任务）
 * @summary Vectorize Documents
 */
export const batchVectorizeAdminDocuments = async (vectorizeRequest: VectorizeRequest, options?: RequestInit): Promise<VectorizeResponse | null> => {

  return customFetch<VectorizeResponse | null>(getBatchVectorizeAdminDocumentsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(vectorizeRequest)
  }
);}




export const getBatchVectorizeAdminDocumentsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchVectorizeAdminDocuments>>, TError,{data: VectorizeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof batchVectorizeAdminDocuments>>, TError,{data: VectorizeRequest}, TContext> => {

const mutationKey = ['batchVectorizeAdminDocuments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof batchVectorizeAdminDocuments>>, {data: VectorizeRequest}> = (props) => {
          const {data} = props ?? {};

          return  batchVectorizeAdminDocuments(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BatchVectorizeAdminDocumentsMutationResult = NonNullable<Awaited<ReturnType<typeof batchVectorizeAdminDocuments>>>
    export type BatchVectorizeAdminDocumentsMutationBody = VectorizeRequest
    export type BatchVectorizeAdminDocumentsMutationError = HTTPValidationError

    /**
 * @summary Vectorize Documents
 */
export const useBatchVectorizeAdminDocuments = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchVectorizeAdminDocuments>>, TError,{data: VectorizeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof batchVectorizeAdminDocuments>>,
        TError,
        {data: VectorizeRequest},
        TContext
      > => {
      return useMutation(getBatchVectorizeAdminDocumentsMutationOptions(options), queryClient);
    }
    export const getVectorizeAdminDocumentUrl = (documentId: number,) => {




  return `/admin/v1/documents/${documentId}:vectorize`
}

/**
 * @summary Vectorize Single Document
 */
export const vectorizeAdminDocument = async (documentId: number, options?: RequestInit): Promise<Document | null> => {

  return customFetch<Document | null>(getVectorizeAdminDocumentUrl(documentId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getVectorizeAdminDocumentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vectorizeAdminDocument>>, TError,{documentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof vectorizeAdminDocument>>, TError,{documentId: number}, TContext> => {

const mutationKey = ['vectorizeAdminDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof vectorizeAdminDocument>>, {documentId: number}> = (props) => {
          const {documentId} = props ?? {};

          return  vectorizeAdminDocument(documentId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VectorizeAdminDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof vectorizeAdminDocument>>>

    export type VectorizeAdminDocumentMutationError = HTTPValidationError

    /**
 * @summary Vectorize Single Document
 */
export const useVectorizeAdminDocument = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vectorizeAdminDocument>>, TError,{documentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof vectorizeAdminDocument>>,
        TError,
        {documentId: number},
        TContext
      > => {
      return useMutation(getVectorizeAdminDocumentMutationOptions(options), queryClient);
    }
    export const getRemoveAdminDocumentVectorUrl = (documentId: number,) => {




  return `/admin/v1/documents/${documentId}:removeVector`
}

/**
 * @summary Remove Document Vector
 */
export const removeAdminDocumentVector = async (documentId: number, options?: RequestInit): Promise<Document | null> => {

  return customFetch<Document | null>(getRemoveAdminDocumentVectorUrl(documentId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getRemoveAdminDocumentVectorMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeAdminDocumentVector>>, TError,{documentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeAdminDocumentVector>>, TError,{documentId: number}, TContext> => {

const mutationKey = ['removeAdminDocumentVector'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeAdminDocumentVector>>, {documentId: number}> = (props) => {
          const {documentId} = props ?? {};

          return  removeAdminDocumentVector(documentId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveAdminDocumentVectorMutationResult = NonNullable<Awaited<ReturnType<typeof removeAdminDocumentVector>>>

    export type RemoveAdminDocumentVectorMutationError = HTTPValidationError

    /**
 * @summary Remove Document Vector
 */
export const useRemoveAdminDocumentVector = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeAdminDocumentVector>>, TError,{documentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeAdminDocumentVector>>,
        TError,
        {documentId: number},
        TContext
      > => {
      return useMutation(getRemoveAdminDocumentVectorMutationOptions(options), queryClient);
    }
    export const getGetAdminDocumentChunksUrl = (documentId: number,) => {




  return `/admin/v1/documents/${documentId}/chunks`
}

/**
 * @summary Get Document Chunks
 */
export const getAdminDocumentChunks = async (documentId: number, options?: RequestInit): Promise<GetAdminDocumentChunks200> => {

  return customFetch<GetAdminDocumentChunks200>(getGetAdminDocumentChunksUrl(documentId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminDocumentChunksQueryKey = (documentId: number,) => {
    return [
    `/admin/v1/documents/${documentId}/chunks`
    ] as const;
    }


export const getGetAdminDocumentChunksQueryOptions = <TData = Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError = HTTPValidationError>(documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminDocumentChunksQueryKey(documentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminDocumentChunks>>> = ({ signal }) => getAdminDocumentChunks(documentId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: documentId !== null && documentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminDocumentChunksQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminDocumentChunks>>>
export type GetAdminDocumentChunksQueryError = HTTPValidationError


export function useGetAdminDocumentChunks<TData = Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError = HTTPValidationError>(
 documentId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDocumentChunks>>,
          TError,
          Awaited<ReturnType<typeof getAdminDocumentChunks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminDocumentChunks<TData = Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError = HTTPValidationError>(
 documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDocumentChunks>>,
          TError,
          Awaited<ReturnType<typeof getAdminDocumentChunks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminDocumentChunks<TData = Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError = HTTPValidationError>(
 documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document Chunks
 */

export function useGetAdminDocumentChunks<TData = Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError = HTTPValidationError>(
 documentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocumentChunks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminDocumentChunksQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getRetrieveDocumentsUrl = () => {




  return `/admin/v1/documents:retrieve`
}

/**
 * 语义检索向量数据库 (delegates to RAGService)
 * @summary Retrieve Vectors
 */
export const retrieveDocuments = async (vectorRetrieveRequest: VectorRetrieveRequest, options?: RequestInit): Promise<VectorRetrieveResult | null> => {

  return customFetch<VectorRetrieveResult | null>(getRetrieveDocumentsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(vectorRetrieveRequest)
  }
);}




export const getRetrieveDocumentsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retrieveDocuments>>, TError,{data: VectorRetrieveRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof retrieveDocuments>>, TError,{data: VectorRetrieveRequest}, TContext> => {

const mutationKey = ['retrieveDocuments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof retrieveDocuments>>, {data: VectorRetrieveRequest}> = (props) => {
          const {data} = props ?? {};

          return  retrieveDocuments(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RetrieveDocumentsMutationResult = NonNullable<Awaited<ReturnType<typeof retrieveDocuments>>>
    export type RetrieveDocumentsMutationBody = VectorRetrieveRequest
    export type RetrieveDocumentsMutationError = HTTPValidationError

    /**
 * @summary Retrieve Vectors
 */
export const useRetrieveDocuments = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retrieveDocuments>>, TError,{data: VectorRetrieveRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof retrieveDocuments>>,
        TError,
        {data: VectorRetrieveRequest},
        TContext
      > => {
      return useMutation(getRetrieveDocumentsMutationOptions(options), queryClient);
    }
    export const getAiGenerateDocumentFieldsUrl = () => {




  return `/admin/v1/documents:aiGenerate`
}

/**
 * 用 AI 生成文档字段（摘要 / 标签）
- fields: ["summary"] / ["tags"] / ["summary", "tags"]
- content: 由前端截断后的文章正文，不超过调用方设定的字符上限
 * @summary Ai Generate Fields
 */
export const aiGenerateDocumentFields = async (aiGenerateRequest: AiGenerateRequest, options?: RequestInit): Promise<AiGenerateResponse | null> => {

  return customFetch<AiGenerateResponse | null>(getAiGenerateDocumentFieldsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(aiGenerateRequest)
  }
);}




export const getAiGenerateDocumentFieldsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aiGenerateDocumentFields>>, TError,{data: AiGenerateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof aiGenerateDocumentFields>>, TError,{data: AiGenerateRequest}, TContext> => {

const mutationKey = ['aiGenerateDocumentFields'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof aiGenerateDocumentFields>>, {data: AiGenerateRequest}> = (props) => {
          const {data} = props ?? {};

          return  aiGenerateDocumentFields(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AiGenerateDocumentFieldsMutationResult = NonNullable<Awaited<ReturnType<typeof aiGenerateDocumentFields>>>
    export type AiGenerateDocumentFieldsMutationBody = AiGenerateRequest
    export type AiGenerateDocumentFieldsMutationError = HTTPValidationError

    /**
 * @summary Ai Generate Fields
 */
export const useAiGenerateDocumentFields = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aiGenerateDocumentFields>>, TError,{data: AiGenerateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof aiGenerateDocumentFields>>,
        TError,
        {data: AiGenerateRequest},
        TContext
      > => {
      return useMutation(getAiGenerateDocumentFieldsMutationOptions(options), queryClient);
    }
