/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.5
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TenantSchema
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetAdminCurrentTenantUrl = () => {




  return `/admin/v1/tenants/current`
}

/**
 * 根据 Token 和 X-Selected-Tenant-ID Header 获取当前生效的租户详情
 * @summary 获取当前生效租户
 */
export const getAdminCurrentTenant = async ( options?: RequestInit): Promise<TenantSchema | null> => {

  return customFetch<TenantSchema | null>(getGetAdminCurrentTenantUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminCurrentTenantQueryKey = () => {
    return [
    `/admin/v1/tenants/current`
    ] as const;
    }


export const getGetAdminCurrentTenantQueryOptions = <TData = Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminCurrentTenantQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminCurrentTenant>>> = ({ signal }) => getAdminCurrentTenant({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminCurrentTenantQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminCurrentTenant>>>
export type GetAdminCurrentTenantQueryError = unknown


export function useGetAdminCurrentTenant<TData = Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCurrentTenant>>,
          TError,
          Awaited<ReturnType<typeof getAdminCurrentTenant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCurrentTenant<TData = Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCurrentTenant>>,
          TError,
          Awaited<ReturnType<typeof getAdminCurrentTenant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCurrentTenant<TData = Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取当前生效租户
 */

export function useGetAdminCurrentTenant<TData = Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCurrentTenant>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminCurrentTenantQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






