/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.5
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AIConfigResponse,
  AIConfigUpdate,
  DeleteAdminConfig200,
  DeleteAdminConfigParams,
  DocProcessorResponse,
  DocProcessorsUpdate,
  GetAdminAiConfigParams,
  GetAdminDocProcessorConfigParams,
  HTTPValidationError,
  TestConnectionRequest,
  TestDocProcessorConnection200,
  TestDocProcessorConnectionParams,
  TestDocProcessorRequest,
  TestModelConnection200,
  TestModelConnectionParams,
  UpdateAdminAiConfigParams,
  UpdateAdminDocProcessorConfigParams
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetAdminAiConfigUrl = (params?: GetAdminAiConfigParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/system-configs/ai-config?${stringifiedParams}` : `/admin/v1/system-configs/ai-config`
}

/**
 * 获取 AI 模型配置
 * @summary Get Ai Config
 */
export const getAdminAiConfig = async (params?: GetAdminAiConfigParams, options?: RequestInit): Promise<AIConfigResponse | null> => {

  return customFetch<AIConfigResponse | null>(getGetAdminAiConfigUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminAiConfigQueryKey = (params?: GetAdminAiConfigParams,) => {
    return [
    `/admin/v1/system-configs/ai-config`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminAiConfigQueryOptions = <TData = Awaited<ReturnType<typeof getAdminAiConfig>>, TError = HTTPValidationError>(params?: GetAdminAiConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAiConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminAiConfigQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminAiConfig>>> = ({ signal }) => getAdminAiConfig(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminAiConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminAiConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminAiConfig>>>
export type GetAdminAiConfigQueryError = HTTPValidationError


export function useGetAdminAiConfig<TData = Awaited<ReturnType<typeof getAdminAiConfig>>, TError = HTTPValidationError>(
 params: undefined |  GetAdminAiConfigParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAiConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAiConfig>>,
          TError,
          Awaited<ReturnType<typeof getAdminAiConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminAiConfig<TData = Awaited<ReturnType<typeof getAdminAiConfig>>, TError = HTTPValidationError>(
 params?: GetAdminAiConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAiConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAiConfig>>,
          TError,
          Awaited<ReturnType<typeof getAdminAiConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminAiConfig<TData = Awaited<ReturnType<typeof getAdminAiConfig>>, TError = HTTPValidationError>(
 params?: GetAdminAiConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAiConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Ai Config
 */

export function useGetAdminAiConfig<TData = Awaited<ReturnType<typeof getAdminAiConfig>>, TError = HTTPValidationError>(
 params?: GetAdminAiConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAiConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminAiConfigQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateAdminAiConfigUrl = (params?: UpdateAdminAiConfigParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/system-configs/ai-config?${stringifiedParams}` : `/admin/v1/system-configs/ai-config`
}

/**
 * 更新 AI 模型配置 (仅更新传入部分，返回全量状态)
 * @summary Update Ai Config
 */
export const updateAdminAiConfig = async (aIConfigUpdate: AIConfigUpdate,
    params?: UpdateAdminAiConfigParams, options?: RequestInit): Promise<AIConfigResponse | null> => {

  return customFetch<AIConfigResponse | null>(getUpdateAdminAiConfigUrl(params),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(aIConfigUpdate)
  }
);}




export const getUpdateAdminAiConfigMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminAiConfig>>, TError,{data: AIConfigUpdate;params?: UpdateAdminAiConfigParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminAiConfig>>, TError,{data: AIConfigUpdate;params?: UpdateAdminAiConfigParams}, TContext> => {

const mutationKey = ['updateAdminAiConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminAiConfig>>, {data: AIConfigUpdate;params?: UpdateAdminAiConfigParams}> = (props) => {
          const {data,params} = props ?? {};

          return  updateAdminAiConfig(data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminAiConfigMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminAiConfig>>>
    export type UpdateAdminAiConfigMutationBody = AIConfigUpdate
    export type UpdateAdminAiConfigMutationError = HTTPValidationError

    /**
 * @summary Update Ai Config
 */
export const useUpdateAdminAiConfig = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminAiConfig>>, TError,{data: AIConfigUpdate;params?: UpdateAdminAiConfigParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminAiConfig>>,
        TError,
        {data: AIConfigUpdate;params?: UpdateAdminAiConfigParams},
        TContext
      > => {
      return useMutation(getUpdateAdminAiConfigMutationOptions(options), queryClient);
    }
    export const getDeleteAdminConfigUrl = (configKey: string,
    params?: DeleteAdminConfigParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/system-configs/${configKey}?${stringifiedParams}` : `/admin/v1/system-configs/${configKey}`
}

/**
 * 删除指定配置
 * @summary Delete Config
 */
export const deleteAdminConfig = async (configKey: string,
    params?: DeleteAdminConfigParams, options?: RequestInit): Promise<DeleteAdminConfig200> => {

  return customFetch<DeleteAdminConfig200>(getDeleteAdminConfigUrl(configKey,params),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAdminConfigMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminConfig>>, TError,{configKey: string;params?: DeleteAdminConfigParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminConfig>>, TError,{configKey: string;params?: DeleteAdminConfigParams}, TContext> => {

const mutationKey = ['deleteAdminConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminConfig>>, {configKey: string;params?: DeleteAdminConfigParams}> = (props) => {
          const {configKey,params} = props ?? {};

          return  deleteAdminConfig(configKey,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminConfigMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminConfig>>>

    export type DeleteAdminConfigMutationError = HTTPValidationError

    /**
 * @summary Delete Config
 */
export const useDeleteAdminConfig = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminConfig>>, TError,{configKey: string;params?: DeleteAdminConfigParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminConfig>>,
        TError,
        {configKey: string;params?: DeleteAdminConfigParams},
        TContext
      > => {
      return useMutation(getDeleteAdminConfigMutationOptions(options), queryClient);
    }
    export const getTestModelConnectionUrl = (params?: TestModelConnectionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/system-configs/ai-config/test-connection?${stringifiedParams}` : `/admin/v1/system-configs/ai-config/test-connection`
}

/**
 * 测试模型连接性
 * @summary Test Model Connection
 */
export const testModelConnection = async (testConnectionRequest: TestConnectionRequest,
    params?: TestModelConnectionParams, options?: RequestInit): Promise<TestModelConnection200> => {

  return customFetch<TestModelConnection200>(getTestModelConnectionUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(testConnectionRequest)
  }
);}




export const getTestModelConnectionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testModelConnection>>, TError,{data: TestConnectionRequest;params?: TestModelConnectionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof testModelConnection>>, TError,{data: TestConnectionRequest;params?: TestModelConnectionParams}, TContext> => {

const mutationKey = ['testModelConnection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testModelConnection>>, {data: TestConnectionRequest;params?: TestModelConnectionParams}> = (props) => {
          const {data,params} = props ?? {};

          return  testModelConnection(data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestModelConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof testModelConnection>>>
    export type TestModelConnectionMutationBody = TestConnectionRequest
    export type TestModelConnectionMutationError = HTTPValidationError

    /**
 * @summary Test Model Connection
 */
export const useTestModelConnection = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testModelConnection>>, TError,{data: TestConnectionRequest;params?: TestModelConnectionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testModelConnection>>,
        TError,
        {data: TestConnectionRequest;params?: TestModelConnectionParams},
        TContext
      > => {
      return useMutation(getTestModelConnectionMutationOptions(options), queryClient);
    }
    export const getGetAdminDocProcessorConfigUrl = (params?: GetAdminDocProcessorConfigParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/system-configs/doc-processor?${stringifiedParams}` : `/admin/v1/system-configs/doc-processor`
}

/**
 * 获取文档处理服务配置 (自动合并平台资源)
 * @summary Get Doc Processor Config
 */
export const getAdminDocProcessorConfig = async (params?: GetAdminDocProcessorConfigParams, options?: RequestInit): Promise<DocProcessorResponse | null> => {

  return customFetch<DocProcessorResponse | null>(getGetAdminDocProcessorConfigUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminDocProcessorConfigQueryKey = (params?: GetAdminDocProcessorConfigParams,) => {
    return [
    `/admin/v1/system-configs/doc-processor`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminDocProcessorConfigQueryOptions = <TData = Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError = HTTPValidationError>(params?: GetAdminDocProcessorConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminDocProcessorConfigQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminDocProcessorConfig>>> = ({ signal }) => getAdminDocProcessorConfig(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminDocProcessorConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminDocProcessorConfig>>>
export type GetAdminDocProcessorConfigQueryError = HTTPValidationError


export function useGetAdminDocProcessorConfig<TData = Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError = HTTPValidationError>(
 params: undefined |  GetAdminDocProcessorConfigParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDocProcessorConfig>>,
          TError,
          Awaited<ReturnType<typeof getAdminDocProcessorConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminDocProcessorConfig<TData = Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError = HTTPValidationError>(
 params?: GetAdminDocProcessorConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminDocProcessorConfig>>,
          TError,
          Awaited<ReturnType<typeof getAdminDocProcessorConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminDocProcessorConfig<TData = Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError = HTTPValidationError>(
 params?: GetAdminDocProcessorConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Doc Processor Config
 */

export function useGetAdminDocProcessorConfig<TData = Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError = HTTPValidationError>(
 params?: GetAdminDocProcessorConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminDocProcessorConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminDocProcessorConfigQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateAdminDocProcessorConfigUrl = (params?: UpdateAdminDocProcessorConfigParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/system-configs/doc-processor?${stringifiedParams}` : `/admin/v1/system-configs/doc-processor`
}

/**
 * 更新文档处理服务配置 (仅保存租户私有配置)
 * @summary Update Doc Processor Config
 */
export const updateAdminDocProcessorConfig = async (docProcessorsUpdate: DocProcessorsUpdate,
    params?: UpdateAdminDocProcessorConfigParams, options?: RequestInit): Promise<DocProcessorResponse | null> => {

  return customFetch<DocProcessorResponse | null>(getUpdateAdminDocProcessorConfigUrl(params),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(docProcessorsUpdate)
  }
);}




export const getUpdateAdminDocProcessorConfigMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminDocProcessorConfig>>, TError,{data: DocProcessorsUpdate;params?: UpdateAdminDocProcessorConfigParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminDocProcessorConfig>>, TError,{data: DocProcessorsUpdate;params?: UpdateAdminDocProcessorConfigParams}, TContext> => {

const mutationKey = ['updateAdminDocProcessorConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminDocProcessorConfig>>, {data: DocProcessorsUpdate;params?: UpdateAdminDocProcessorConfigParams}> = (props) => {
          const {data,params} = props ?? {};

          return  updateAdminDocProcessorConfig(data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminDocProcessorConfigMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminDocProcessorConfig>>>
    export type UpdateAdminDocProcessorConfigMutationBody = DocProcessorsUpdate
    export type UpdateAdminDocProcessorConfigMutationError = HTTPValidationError

    /**
 * @summary Update Doc Processor Config
 */
export const useUpdateAdminDocProcessorConfig = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminDocProcessorConfig>>, TError,{data: DocProcessorsUpdate;params?: UpdateAdminDocProcessorConfigParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminDocProcessorConfig>>,
        TError,
        {data: DocProcessorsUpdate;params?: UpdateAdminDocProcessorConfigParams},
        TContext
      > => {
      return useMutation(getUpdateAdminDocProcessorConfigMutationOptions(options), queryClient);
    }
    export const getTestDocProcessorConnectionUrl = (params?: TestDocProcessorConnectionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/system-configs/doc-processor/test-connection?${stringifiedParams}` : `/admin/v1/system-configs/doc-processor/test-connection`
}

/**
 * 测试文档处理服务连接性
 * @summary Test Doc Processor Connection
 */
export const testDocProcessorConnection = async (testDocProcessorRequest: TestDocProcessorRequest,
    params?: TestDocProcessorConnectionParams, options?: RequestInit): Promise<TestDocProcessorConnection200> => {

  return customFetch<TestDocProcessorConnection200>(getTestDocProcessorConnectionUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(testDocProcessorRequest)
  }
);}




export const getTestDocProcessorConnectionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testDocProcessorConnection>>, TError,{data: TestDocProcessorRequest;params?: TestDocProcessorConnectionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof testDocProcessorConnection>>, TError,{data: TestDocProcessorRequest;params?: TestDocProcessorConnectionParams}, TContext> => {

const mutationKey = ['testDocProcessorConnection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testDocProcessorConnection>>, {data: TestDocProcessorRequest;params?: TestDocProcessorConnectionParams}> = (props) => {
          const {data,params} = props ?? {};

          return  testDocProcessorConnection(data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestDocProcessorConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof testDocProcessorConnection>>>
    export type TestDocProcessorConnectionMutationBody = TestDocProcessorRequest
    export type TestDocProcessorConnectionMutationError = HTTPValidationError

    /**
 * @summary Test Doc Processor Connection
 */
export const useTestDocProcessorConnection = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testDocProcessorConnection>>, TError,{data: TestDocProcessorRequest;params?: TestDocProcessorConnectionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testDocProcessorConnection>>,
        TError,
        {data: TestDocProcessorRequest;params?: TestDocProcessorConnectionParams},
        TContext
      > => {
      return useMutation(getTestDocProcessorConnectionMutationOptions(options), queryClient);
    }
