/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.7
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Collection,
  CollectionCreate,
  CollectionTree,
  CollectionUpdate,
  GetAdminCollectionTreeParams,
  HTTPValidationError,
  ListAdminCollectionsParams,
  MoveCollectionRequest,
  PaginatedResponseCollection
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListAdminCollectionsUrl = (params: ListAdminCollectionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/collections?${stringifiedParams}` : `/admin/v1/collections`
}

/**
 * 获取合集列表
 * @summary List Collections
 */
export const listAdminCollections = async (params: ListAdminCollectionsParams, options?: RequestInit): Promise<PaginatedResponseCollection | null> => {

  return customFetch<PaginatedResponseCollection | null>(getListAdminCollectionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAdminCollectionsQueryKey = (params?: ListAdminCollectionsParams,) => {
    return [
    `/admin/v1/collections`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAdminCollectionsQueryOptions = <TData = Awaited<ReturnType<typeof listAdminCollections>>, TError = HTTPValidationError>(params: ListAdminCollectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCollections>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminCollectionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminCollections>>> = ({ signal }) => listAdminCollections(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminCollections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminCollectionsQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminCollections>>>
export type ListAdminCollectionsQueryError = HTTPValidationError


export function useListAdminCollections<TData = Awaited<ReturnType<typeof listAdminCollections>>, TError = HTTPValidationError>(
 params: ListAdminCollectionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCollections>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminCollections>>,
          TError,
          Awaited<ReturnType<typeof listAdminCollections>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminCollections<TData = Awaited<ReturnType<typeof listAdminCollections>>, TError = HTTPValidationError>(
 params: ListAdminCollectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCollections>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminCollections>>,
          TError,
          Awaited<ReturnType<typeof listAdminCollections>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminCollections<TData = Awaited<ReturnType<typeof listAdminCollections>>, TError = HTTPValidationError>(
 params: ListAdminCollectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCollections>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Collections
 */

export function useListAdminCollections<TData = Awaited<ReturnType<typeof listAdminCollections>>, TError = HTTPValidationError>(
 params: ListAdminCollectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCollections>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminCollectionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateAdminCollectionUrl = () => {




  return `/admin/v1/collections`
}

/**
 * 创建合集
 * @summary Create Collection
 */
export const createAdminCollection = async (collectionCreate: CollectionCreate, options?: RequestInit): Promise<Collection | null> => {

  return customFetch<Collection | null>(getCreateAdminCollectionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(collectionCreate)
  }
);}




export const getCreateAdminCollectionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminCollection>>, TError,{data: CollectionCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createAdminCollection>>, TError,{data: CollectionCreate}, TContext> => {

const mutationKey = ['createAdminCollection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdminCollection>>, {data: CollectionCreate}> = (props) => {
          const {data} = props ?? {};

          return  createAdminCollection(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAdminCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof createAdminCollection>>>
    export type CreateAdminCollectionMutationBody = CollectionCreate
    export type CreateAdminCollectionMutationError = HTTPValidationError

    /**
 * @summary Create Collection
 */
export const useCreateAdminCollection = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminCollection>>, TError,{data: CollectionCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAdminCollection>>,
        TError,
        {data: CollectionCreate},
        TContext
      > => {
      return useMutation(getCreateAdminCollectionMutationOptions(options), queryClient);
    }
    export const getGetAdminCollectionTreeUrl = (params: GetAdminCollectionTreeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/collections:tree?${stringifiedParams}` : `/admin/v1/collections:tree`
}

/**
 * @summary Get Collection Tree
 */
export const getAdminCollectionTree = async (params: GetAdminCollectionTreeParams, options?: RequestInit): Promise<CollectionTree[] | null> => {

  return customFetch<CollectionTree[] | null>(getGetAdminCollectionTreeUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminCollectionTreeQueryKey = (params?: GetAdminCollectionTreeParams,) => {
    return [
    `/admin/v1/collections:tree`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminCollectionTreeQueryOptions = <TData = Awaited<ReturnType<typeof getAdminCollectionTree>>, TError = HTTPValidationError>(params: GetAdminCollectionTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollectionTree>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminCollectionTreeQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminCollectionTree>>> = ({ signal }) => getAdminCollectionTree(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminCollectionTree>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminCollectionTreeQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminCollectionTree>>>
export type GetAdminCollectionTreeQueryError = HTTPValidationError


export function useGetAdminCollectionTree<TData = Awaited<ReturnType<typeof getAdminCollectionTree>>, TError = HTTPValidationError>(
 params: GetAdminCollectionTreeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollectionTree>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCollectionTree>>,
          TError,
          Awaited<ReturnType<typeof getAdminCollectionTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCollectionTree<TData = Awaited<ReturnType<typeof getAdminCollectionTree>>, TError = HTTPValidationError>(
 params: GetAdminCollectionTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollectionTree>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCollectionTree>>,
          TError,
          Awaited<ReturnType<typeof getAdminCollectionTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCollectionTree<TData = Awaited<ReturnType<typeof getAdminCollectionTree>>, TError = HTTPValidationError>(
 params: GetAdminCollectionTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollectionTree>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Collection Tree
 */

export function useGetAdminCollectionTree<TData = Awaited<ReturnType<typeof getAdminCollectionTree>>, TError = HTTPValidationError>(
 params: GetAdminCollectionTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollectionTree>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminCollectionTreeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetAdminCollectionUrl = (collectionId: number,) => {




  return `/admin/v1/collections/${collectionId}`
}

/**
 * 获取合集详情
 * @summary Get Collection
 */
export const getAdminCollection = async (collectionId: number, options?: RequestInit): Promise<Collection | null> => {

  return customFetch<Collection | null>(getGetAdminCollectionUrl(collectionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminCollectionQueryKey = (collectionId: number,) => {
    return [
    `/admin/v1/collections/${collectionId}`
    ] as const;
    }


export const getGetAdminCollectionQueryOptions = <TData = Awaited<ReturnType<typeof getAdminCollection>>, TError = HTTPValidationError>(collectionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollection>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminCollectionQueryKey(collectionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminCollection>>> = ({ signal }) => getAdminCollection(collectionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: collectionId !== null && collectionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminCollection>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminCollectionQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminCollection>>>
export type GetAdminCollectionQueryError = HTTPValidationError


export function useGetAdminCollection<TData = Awaited<ReturnType<typeof getAdminCollection>>, TError = HTTPValidationError>(
 collectionId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollection>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCollection>>,
          TError,
          Awaited<ReturnType<typeof getAdminCollection>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCollection<TData = Awaited<ReturnType<typeof getAdminCollection>>, TError = HTTPValidationError>(
 collectionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollection>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCollection>>,
          TError,
          Awaited<ReturnType<typeof getAdminCollection>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCollection<TData = Awaited<ReturnType<typeof getAdminCollection>>, TError = HTTPValidationError>(
 collectionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollection>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Collection
 */

export function useGetAdminCollection<TData = Awaited<ReturnType<typeof getAdminCollection>>, TError = HTTPValidationError>(
 collectionId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCollection>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminCollectionQueryOptions(collectionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateAdminCollectionUrl = (collectionId: number,) => {




  return `/admin/v1/collections/${collectionId}`
}

/**
 * 更新合集
 * @summary Update Collection
 */
export const updateAdminCollection = async (collectionId: number,
    collectionUpdate: CollectionUpdate, options?: RequestInit): Promise<Collection | null> => {

  return customFetch<Collection | null>(getUpdateAdminCollectionUrl(collectionId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(collectionUpdate)
  }
);}




export const getUpdateAdminCollectionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminCollection>>, TError,{collectionId: number;data: CollectionUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminCollection>>, TError,{collectionId: number;data: CollectionUpdate}, TContext> => {

const mutationKey = ['updateAdminCollection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminCollection>>, {collectionId: number;data: CollectionUpdate}> = (props) => {
          const {collectionId,data} = props ?? {};

          return  updateAdminCollection(collectionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminCollection>>>
    export type UpdateAdminCollectionMutationBody = CollectionUpdate
    export type UpdateAdminCollectionMutationError = HTTPValidationError

    /**
 * @summary Update Collection
 */
export const useUpdateAdminCollection = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminCollection>>, TError,{collectionId: number;data: CollectionUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminCollection>>,
        TError,
        {collectionId: number;data: CollectionUpdate},
        TContext
      > => {
      return useMutation(getUpdateAdminCollectionMutationOptions(options), queryClient);
    }
    export const getDeleteAdminCollectionUrl = (collectionId: number,) => {




  return `/admin/v1/collections/${collectionId}`
}

/**
 * 删除合集
 * @summary Delete Collection
 */
export const deleteAdminCollection = async (collectionId: number, options?: RequestInit): Promise<null> => {

  return customFetch<null>(getDeleteAdminCollectionUrl(collectionId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAdminCollectionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCollection>>, TError,{collectionId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCollection>>, TError,{collectionId: number}, TContext> => {

const mutationKey = ['deleteAdminCollection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminCollection>>, {collectionId: number}> = (props) => {
          const {collectionId} = props ?? {};

          return  deleteAdminCollection(collectionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminCollection>>>

    export type DeleteAdminCollectionMutationError = HTTPValidationError

    /**
 * @summary Delete Collection
 */
export const useDeleteAdminCollection = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCollection>>, TError,{collectionId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminCollection>>,
        TError,
        {collectionId: number},
        TContext
      > => {
      return useMutation(getDeleteAdminCollectionMutationOptions(options), queryClient);
    }
    export const getMoveAdminCollectionUrl = (collectionId: number,) => {




  return `/admin/v1/collections/${collectionId}:move`
}

/**
 * 移动合集到新位置

这个接口会：
1. 更新合集的 parent_id
2. 重新计算目标父级下所有合集的 order，确保顺序连续
 * @summary Move Collection
 */
export const moveAdminCollection = async (collectionId: number,
    moveCollectionRequest: MoveCollectionRequest, options?: RequestInit): Promise<Collection | null> => {

  return customFetch<Collection | null>(getMoveAdminCollectionUrl(collectionId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(moveCollectionRequest)
  }
);}




export const getMoveAdminCollectionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveAdminCollection>>, TError,{collectionId: number;data: MoveCollectionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof moveAdminCollection>>, TError,{collectionId: number;data: MoveCollectionRequest}, TContext> => {

const mutationKey = ['moveAdminCollection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveAdminCollection>>, {collectionId: number;data: MoveCollectionRequest}> = (props) => {
          const {collectionId,data} = props ?? {};

          return  moveAdminCollection(collectionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MoveAdminCollectionMutationResult = NonNullable<Awaited<ReturnType<typeof moveAdminCollection>>>
    export type MoveAdminCollectionMutationBody = MoveCollectionRequest
    export type MoveAdminCollectionMutationError = HTTPValidationError

    /**
 * @summary Move Collection
 */
export const useMoveAdminCollection = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveAdminCollection>>, TError,{collectionId: number;data: MoveCollectionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moveAdminCollection>>,
        TError,
        {collectionId: number;data: MoveCollectionRequest},
        TContext
      > => {
      return useMutation(getMoveAdminCollectionMutationOptions(options), queryClient);
    }
