/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.5
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyUploadToDataSource,
  BrowseDataSourceParams,
  DataSource,
  DataSourceCreate,
  DataSourceImportRequest,
  DataSourceUpdate,
  DeleteDataSourceFileParams,
  HTTPValidationError,
  ImportFromDataSource200,
  S3FileItem,
  UploadedFile
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListDataSourcesUrl = () => {




  return `/admin/v1/data-sources`
}

/**
 * @summary List Data Sources
 */
export const listDataSources = async ( options?: RequestInit): Promise<DataSource[] | null> => {

  return customFetch<DataSource[] | null>(getListDataSourcesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDataSourcesQueryKey = () => {
    return [
    `/admin/v1/data-sources`
    ] as const;
    }


export const getListDataSourcesQueryOptions = <TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDataSourcesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDataSources>>> = ({ signal }) => listDataSources({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDataSourcesQueryResult = NonNullable<Awaited<ReturnType<typeof listDataSources>>>
export type ListDataSourcesQueryError = unknown


export function useListDataSources<TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDataSources>>,
          TError,
          Awaited<ReturnType<typeof listDataSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDataSources<TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDataSources>>,
          TError,
          Awaited<ReturnType<typeof listDataSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDataSources<TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Data Sources
 */

export function useListDataSources<TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDataSourcesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateDataSourceUrl = () => {




  return `/admin/v1/data-sources`
}

/**
 * @summary Create Data Source
 */
export const createDataSource = async (dataSourceCreate: DataSourceCreate, options?: RequestInit): Promise<DataSource | null> => {

  return customFetch<DataSource | null>(getCreateDataSourceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(dataSourceCreate)
  }
);}




export const getCreateDataSourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDataSource>>, TError,{data: DataSourceCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createDataSource>>, TError,{data: DataSourceCreate}, TContext> => {

const mutationKey = ['createDataSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDataSource>>, {data: DataSourceCreate}> = (props) => {
          const {data} = props ?? {};

          return  createDataSource(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDataSourceMutationResult = NonNullable<Awaited<ReturnType<typeof createDataSource>>>
    export type CreateDataSourceMutationBody = DataSourceCreate
    export type CreateDataSourceMutationError = HTTPValidationError

    /**
 * @summary Create Data Source
 */
export const useCreateDataSource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDataSource>>, TError,{data: DataSourceCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDataSource>>,
        TError,
        {data: DataSourceCreate},
        TContext
      > => {
      return useMutation(getCreateDataSourceMutationOptions(options), queryClient);
    }
    export const getUpdateDataSourceUrl = (dsId: number,) => {




  return `/admin/v1/data-sources/${dsId}`
}

/**
 * @summary Update Data Source
 */
export const updateDataSource = async (dsId: number,
    dataSourceUpdate: DataSourceUpdate, options?: RequestInit): Promise<DataSource | null> => {

  return customFetch<DataSource | null>(getUpdateDataSourceUrl(dsId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(dataSourceUpdate)
  }
);}




export const getUpdateDataSourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDataSource>>, TError,{dsId: number;data: DataSourceUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDataSource>>, TError,{dsId: number;data: DataSourceUpdate}, TContext> => {

const mutationKey = ['updateDataSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDataSource>>, {dsId: number;data: DataSourceUpdate}> = (props) => {
          const {dsId,data} = props ?? {};

          return  updateDataSource(dsId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDataSourceMutationResult = NonNullable<Awaited<ReturnType<typeof updateDataSource>>>
    export type UpdateDataSourceMutationBody = DataSourceUpdate
    export type UpdateDataSourceMutationError = HTTPValidationError

    /**
 * @summary Update Data Source
 */
export const useUpdateDataSource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDataSource>>, TError,{dsId: number;data: DataSourceUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDataSource>>,
        TError,
        {dsId: number;data: DataSourceUpdate},
        TContext
      > => {
      return useMutation(getUpdateDataSourceMutationOptions(options), queryClient);
    }
    export const getDeleteDataSourceUrl = (dsId: number,) => {




  return `/admin/v1/data-sources/${dsId}`
}

/**
 * @summary Delete Data Source
 */
export const deleteDataSource = async (dsId: number, options?: RequestInit): Promise<null> => {

  return customFetch<null>(getDeleteDataSourceUrl(dsId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteDataSourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSource>>, TError,{dsId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDataSource>>, TError,{dsId: number}, TContext> => {

const mutationKey = ['deleteDataSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDataSource>>, {dsId: number}> = (props) => {
          const {dsId} = props ?? {};

          return  deleteDataSource(dsId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDataSourceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDataSource>>>

    export type DeleteDataSourceMutationError = HTTPValidationError

    /**
 * @summary Delete Data Source
 */
export const useDeleteDataSource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSource>>, TError,{dsId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDataSource>>,
        TError,
        {dsId: number},
        TContext
      > => {
      return useMutation(getDeleteDataSourceMutationOptions(options), queryClient);
    }
    export const getBrowseDataSourceUrl = (dsId: number,
    params?: BrowseDataSourceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/data-sources/${dsId}/browse?${stringifiedParams}` : `/admin/v1/data-sources/${dsId}/browse`
}

/**
 * @summary Browse Data Source
 */
export const browseDataSource = async (dsId: number,
    params?: BrowseDataSourceParams, options?: RequestInit): Promise<S3FileItem[] | null> => {

  return customFetch<S3FileItem[] | null>(getBrowseDataSourceUrl(dsId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBrowseDataSourceQueryKey = (dsId: number,
    params?: BrowseDataSourceParams,) => {
    return [
    `/admin/v1/data-sources/${dsId}/browse`, ...(params ? [params] : [])
    ] as const;
    }


export const getBrowseDataSourceQueryOptions = <TData = Awaited<ReturnType<typeof browseDataSource>>, TError = HTTPValidationError>(dsId: number,
    params?: BrowseDataSourceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof browseDataSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBrowseDataSourceQueryKey(dsId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof browseDataSource>>> = ({ signal }) => browseDataSource(dsId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: dsId !== null && dsId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof browseDataSource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BrowseDataSourceQueryResult = NonNullable<Awaited<ReturnType<typeof browseDataSource>>>
export type BrowseDataSourceQueryError = HTTPValidationError


export function useBrowseDataSource<TData = Awaited<ReturnType<typeof browseDataSource>>, TError = HTTPValidationError>(
 dsId: number,
    params: undefined |  BrowseDataSourceParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof browseDataSource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof browseDataSource>>,
          TError,
          Awaited<ReturnType<typeof browseDataSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBrowseDataSource<TData = Awaited<ReturnType<typeof browseDataSource>>, TError = HTTPValidationError>(
 dsId: number,
    params?: BrowseDataSourceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof browseDataSource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof browseDataSource>>,
          TError,
          Awaited<ReturnType<typeof browseDataSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBrowseDataSource<TData = Awaited<ReturnType<typeof browseDataSource>>, TError = HTTPValidationError>(
 dsId: number,
    params?: BrowseDataSourceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof browseDataSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Browse Data Source
 */

export function useBrowseDataSource<TData = Awaited<ReturnType<typeof browseDataSource>>, TError = HTTPValidationError>(
 dsId: number,
    params?: BrowseDataSourceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof browseDataSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBrowseDataSourceQueryOptions(dsId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUploadToDataSourceUrl = (dsId: number,) => {




  return `/admin/v1/data-sources/${dsId}/upload`
}

/**
 * @summary Upload To Data Source
 */
export const uploadToDataSource = async (dsId: number,
    bodyUploadToDataSource: BodyUploadToDataSource, options?: RequestInit): Promise<UploadedFile | null> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadToDataSource.file);
if(bodyUploadToDataSource.prefix !== undefined) {
 formData.append(`prefix`, bodyUploadToDataSource.prefix);
 }

  return customFetch<UploadedFile | null>(getUploadToDataSourceUrl(dsId),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}




export const getUploadToDataSourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadToDataSource>>, TError,{dsId: number;data: BodyUploadToDataSource}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadToDataSource>>, TError,{dsId: number;data: BodyUploadToDataSource}, TContext> => {

const mutationKey = ['uploadToDataSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadToDataSource>>, {dsId: number;data: BodyUploadToDataSource}> = (props) => {
          const {dsId,data} = props ?? {};

          return  uploadToDataSource(dsId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadToDataSourceMutationResult = NonNullable<Awaited<ReturnType<typeof uploadToDataSource>>>
    export type UploadToDataSourceMutationBody = BodyUploadToDataSource
    export type UploadToDataSourceMutationError = HTTPValidationError

    /**
 * @summary Upload To Data Source
 */
export const useUploadToDataSource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadToDataSource>>, TError,{dsId: number;data: BodyUploadToDataSource}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadToDataSource>>,
        TError,
        {dsId: number;data: BodyUploadToDataSource},
        TContext
      > => {
      return useMutation(getUploadToDataSourceMutationOptions(options), queryClient);
    }
    export const getDeleteDataSourceFileUrl = (dsId: number,
    params: DeleteDataSourceFileParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/data-sources/${dsId}/files?${stringifiedParams}` : `/admin/v1/data-sources/${dsId}/files`
}

/**
 * @summary Delete Data Source File
 */
export const deleteDataSourceFile = async (dsId: number,
    params: DeleteDataSourceFileParams, options?: RequestInit): Promise<null> => {

  return customFetch<null>(getDeleteDataSourceFileUrl(dsId,params),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteDataSourceFileMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSourceFile>>, TError,{dsId: number;params: DeleteDataSourceFileParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDataSourceFile>>, TError,{dsId: number;params: DeleteDataSourceFileParams}, TContext> => {

const mutationKey = ['deleteDataSourceFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDataSourceFile>>, {dsId: number;params: DeleteDataSourceFileParams}> = (props) => {
          const {dsId,params} = props ?? {};

          return  deleteDataSourceFile(dsId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDataSourceFileMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDataSourceFile>>>

    export type DeleteDataSourceFileMutationError = HTTPValidationError

    /**
 * @summary Delete Data Source File
 */
export const useDeleteDataSourceFile = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSourceFile>>, TError,{dsId: number;params: DeleteDataSourceFileParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDataSourceFile>>,
        TError,
        {dsId: number;params: DeleteDataSourceFileParams},
        TContext
      > => {
      return useMutation(getDeleteDataSourceFileMutationOptions(options), queryClient);
    }
    export const getImportFromDataSourceUrl = (dsId: number,) => {




  return `/admin/v1/data-sources/${dsId}/import`
}

/**
 * @summary Import From Data Source
 */
export const importFromDataSource = async (dsId: number,
    dataSourceImportRequest: DataSourceImportRequest, options?: RequestInit): Promise<ImportFromDataSource200> => {

  return customFetch<ImportFromDataSource200>(getImportFromDataSourceUrl(dsId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(dataSourceImportRequest)
  }
);}




export const getImportFromDataSourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importFromDataSource>>, TError,{dsId: number;data: DataSourceImportRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof importFromDataSource>>, TError,{dsId: number;data: DataSourceImportRequest}, TContext> => {

const mutationKey = ['importFromDataSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importFromDataSource>>, {dsId: number;data: DataSourceImportRequest}> = (props) => {
          const {dsId,data} = props ?? {};

          return  importFromDataSource(dsId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ImportFromDataSourceMutationResult = NonNullable<Awaited<ReturnType<typeof importFromDataSource>>>
    export type ImportFromDataSourceMutationBody = DataSourceImportRequest
    export type ImportFromDataSourceMutationError = HTTPValidationError

    /**
 * @summary Import From Data Source
 */
export const useImportFromDataSource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importFromDataSource>>, TError,{dsId: number;data: DataSourceImportRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importFromDataSource>>,
        TError,
        {dsId: number;data: DataSourceImportRequest},
        TContext
      > => {
      return useMutation(getImportFromDataSourceMutationOptions(options), queryClient);
    }
