/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.7
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BatchUploadAdminFiles200,
  BatchUploadAdminFilesParams,
  BodyBatchUploadAdminFiles,
  BodyUploadAdminFile,
  GetAdminFileInfo200,
  GetAdminPresignedUrl200,
  GetAdminPresignedUrlParams,
  HTTPValidationError,
  ListAdminFilesParams,
  PaginatedResponseDict,
  UploadAdminFile200,
  UploadAdminFileParams
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getUploadAdminFileUrl = (params?: UploadAdminFileParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/files:upload?${stringifiedParams}` : `/admin/v1/files:upload`
}

/**
 * 上传文件到 RustFS
 * @summary Upload File
 */
export const uploadAdminFile = async (bodyUploadAdminFile: BodyUploadAdminFile,
    params?: UploadAdminFileParams, options?: RequestInit): Promise<UploadAdminFile200> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadAdminFile.file);

  return customFetch<UploadAdminFile200>(getUploadAdminFileUrl(params),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}




export const getUploadAdminFileMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAdminFile>>, TError,{data: BodyUploadAdminFile;params?: UploadAdminFileParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadAdminFile>>, TError,{data: BodyUploadAdminFile;params?: UploadAdminFileParams}, TContext> => {

const mutationKey = ['uploadAdminFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadAdminFile>>, {data: BodyUploadAdminFile;params?: UploadAdminFileParams}> = (props) => {
          const {data,params} = props ?? {};

          return  uploadAdminFile(data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadAdminFileMutationResult = NonNullable<Awaited<ReturnType<typeof uploadAdminFile>>>
    export type UploadAdminFileMutationBody = BodyUploadAdminFile
    export type UploadAdminFileMutationError = HTTPValidationError

    /**
 * @summary Upload File
 */
export const useUploadAdminFile = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAdminFile>>, TError,{data: BodyUploadAdminFile;params?: UploadAdminFileParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadAdminFile>>,
        TError,
        {data: BodyUploadAdminFile;params?: UploadAdminFileParams},
        TContext
      > => {
      return useMutation(getUploadAdminFileMutationOptions(options), queryClient);
    }
    export const getBatchUploadAdminFilesUrl = (params?: BatchUploadAdminFilesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/files:batchUpload?${stringifiedParams}` : `/admin/v1/files:batchUpload`
}

/**
 * 批量上传文件到 RustFS
 * @summary Upload Multiple Files
 */
export const batchUploadAdminFiles = async (bodyBatchUploadAdminFiles: BodyBatchUploadAdminFiles,
    params?: BatchUploadAdminFilesParams, options?: RequestInit): Promise<BatchUploadAdminFiles200> => {
    const formData = new FormData();
bodyBatchUploadAdminFiles.files.forEach(value => formData.append(`files`, value));

  return customFetch<BatchUploadAdminFiles200>(getBatchUploadAdminFilesUrl(params),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}




export const getBatchUploadAdminFilesMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchUploadAdminFiles>>, TError,{data: BodyBatchUploadAdminFiles;params?: BatchUploadAdminFilesParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof batchUploadAdminFiles>>, TError,{data: BodyBatchUploadAdminFiles;params?: BatchUploadAdminFilesParams}, TContext> => {

const mutationKey = ['batchUploadAdminFiles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof batchUploadAdminFiles>>, {data: BodyBatchUploadAdminFiles;params?: BatchUploadAdminFilesParams}> = (props) => {
          const {data,params} = props ?? {};

          return  batchUploadAdminFiles(data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BatchUploadAdminFilesMutationResult = NonNullable<Awaited<ReturnType<typeof batchUploadAdminFiles>>>
    export type BatchUploadAdminFilesMutationBody = BodyBatchUploadAdminFiles
    export type BatchUploadAdminFilesMutationError = HTTPValidationError

    /**
 * @summary Upload Multiple Files
 */
export const useBatchUploadAdminFiles = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchUploadAdminFiles>>, TError,{data: BodyBatchUploadAdminFiles;params?: BatchUploadAdminFilesParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof batchUploadAdminFiles>>,
        TError,
        {data: BodyBatchUploadAdminFiles;params?: BatchUploadAdminFilesParams},
        TContext
      > => {
      return useMutation(getBatchUploadAdminFilesMutationOptions(options), queryClient);
    }
    export const getDownloadAdminFileUrl = (objectName: string,) => {




  return `/admin/v1/files/${objectName}:download`
}

/**
 * 下载文件
 * @summary Download File
 */
export const downloadAdminFile = async (objectName: string, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getDownloadAdminFileUrl(objectName),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDownloadAdminFileQueryKey = (objectName: string,) => {
    return [
    `/admin/v1/files/${objectName}:download`
    ] as const;
    }


export const getDownloadAdminFileQueryOptions = <TData = Awaited<ReturnType<typeof downloadAdminFile>>, TError = HTTPValidationError>(objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAdminFile>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadAdminFileQueryKey(objectName);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadAdminFile>>> = ({ signal }) => downloadAdminFile(objectName, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadAdminFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadAdminFileQueryResult = NonNullable<Awaited<ReturnType<typeof downloadAdminFile>>>
export type DownloadAdminFileQueryError = HTTPValidationError


export function useDownloadAdminFile<TData = Awaited<ReturnType<typeof downloadAdminFile>>, TError = HTTPValidationError>(
 objectName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAdminFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAdminFile>>,
          TError,
          Awaited<ReturnType<typeof downloadAdminFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAdminFile<TData = Awaited<ReturnType<typeof downloadAdminFile>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAdminFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAdminFile>>,
          TError,
          Awaited<ReturnType<typeof downloadAdminFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAdminFile<TData = Awaited<ReturnType<typeof downloadAdminFile>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAdminFile>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download File
 */

export function useDownloadAdminFile<TData = Awaited<ReturnType<typeof downloadAdminFile>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAdminFile>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadAdminFileQueryOptions(objectName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getDeleteAdminFileUrl = (objectName: string,) => {




  return `/admin/v1/files/${objectName}`
}

/**
 * 删除文件
 * @summary Delete File
 */
export const deleteAdminFile = async (objectName: string, options?: RequestInit): Promise<null> => {

  return customFetch<null>(getDeleteAdminFileUrl(objectName),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAdminFileMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminFile>>, TError,{objectName: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminFile>>, TError,{objectName: string}, TContext> => {

const mutationKey = ['deleteAdminFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminFile>>, {objectName: string}> = (props) => {
          const {objectName} = props ?? {};

          return  deleteAdminFile(objectName,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminFileMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminFile>>>

    export type DeleteAdminFileMutationError = HTTPValidationError

    /**
 * @summary Delete File
 */
export const useDeleteAdminFile = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminFile>>, TError,{objectName: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminFile>>,
        TError,
        {objectName: string},
        TContext
      > => {
      return useMutation(getDeleteAdminFileMutationOptions(options), queryClient);
    }
    export const getListAdminFilesUrl = (params?: ListAdminFilesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/files?${stringifiedParams}` : `/admin/v1/files`
}

/**
 * 列出文件
 * @summary List Files
 */
export const listAdminFiles = async (params?: ListAdminFilesParams, options?: RequestInit): Promise<PaginatedResponseDict | null> => {

  return customFetch<PaginatedResponseDict | null>(getListAdminFilesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAdminFilesQueryKey = (params?: ListAdminFilesParams,) => {
    return [
    `/admin/v1/files`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAdminFilesQueryOptions = <TData = Awaited<ReturnType<typeof listAdminFiles>>, TError = HTTPValidationError>(params?: ListAdminFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminFiles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminFilesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminFiles>>> = ({ signal }) => listAdminFiles(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminFiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminFilesQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminFiles>>>
export type ListAdminFilesQueryError = HTTPValidationError


export function useListAdminFiles<TData = Awaited<ReturnType<typeof listAdminFiles>>, TError = HTTPValidationError>(
 params: undefined |  ListAdminFilesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminFiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminFiles>>,
          TError,
          Awaited<ReturnType<typeof listAdminFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminFiles<TData = Awaited<ReturnType<typeof listAdminFiles>>, TError = HTTPValidationError>(
 params?: ListAdminFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminFiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminFiles>>,
          TError,
          Awaited<ReturnType<typeof listAdminFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminFiles<TData = Awaited<ReturnType<typeof listAdminFiles>>, TError = HTTPValidationError>(
 params?: ListAdminFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminFiles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Files
 */

export function useListAdminFiles<TData = Awaited<ReturnType<typeof listAdminFiles>>, TError = HTTPValidationError>(
 params?: ListAdminFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminFiles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminFilesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetAdminFileInfoUrl = (objectName: string,) => {




  return `/admin/v1/files/${objectName}:info`
}

/**
 * 获取文件信息
 * @summary Get File Info
 */
export const getAdminFileInfo = async (objectName: string, options?: RequestInit): Promise<GetAdminFileInfo200> => {

  return customFetch<GetAdminFileInfo200>(getGetAdminFileInfoUrl(objectName),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminFileInfoQueryKey = (objectName: string,) => {
    return [
    `/admin/v1/files/${objectName}:info`
    ] as const;
    }


export const getGetAdminFileInfoQueryOptions = <TData = Awaited<ReturnType<typeof getAdminFileInfo>>, TError = HTTPValidationError>(objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFileInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminFileInfoQueryKey(objectName);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminFileInfo>>> = ({ signal }) => getAdminFileInfo(objectName, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminFileInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminFileInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminFileInfo>>>
export type GetAdminFileInfoQueryError = HTTPValidationError


export function useGetAdminFileInfo<TData = Awaited<ReturnType<typeof getAdminFileInfo>>, TError = HTTPValidationError>(
 objectName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFileInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminFileInfo>>,
          TError,
          Awaited<ReturnType<typeof getAdminFileInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminFileInfo<TData = Awaited<ReturnType<typeof getAdminFileInfo>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFileInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminFileInfo>>,
          TError,
          Awaited<ReturnType<typeof getAdminFileInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminFileInfo<TData = Awaited<ReturnType<typeof getAdminFileInfo>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFileInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get File Info
 */

export function useGetAdminFileInfo<TData = Awaited<ReturnType<typeof getAdminFileInfo>>, TError = HTTPValidationError>(
 objectName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFileInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminFileInfoQueryOptions(objectName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetAdminPresignedUrlUrl = (objectName: string,
    params?: GetAdminPresignedUrlParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/files/${objectName}:presignedUrl?${stringifiedParams}` : `/admin/v1/files/${objectName}:presignedUrl`
}

/**
 * 获取文件的预签名 URL
 * @summary Get Presigned Url
 */
export const getAdminPresignedUrl = async (objectName: string,
    params?: GetAdminPresignedUrlParams, options?: RequestInit): Promise<GetAdminPresignedUrl200> => {

  return customFetch<GetAdminPresignedUrl200>(getGetAdminPresignedUrlUrl(objectName,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminPresignedUrlQueryKey = (objectName: string,
    params?: GetAdminPresignedUrlParams,) => {
    return [
    `/admin/v1/files/${objectName}:presignedUrl`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminPresignedUrlQueryOptions = <TData = Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError = HTTPValidationError>(objectName: string,
    params?: GetAdminPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminPresignedUrlQueryKey(objectName,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminPresignedUrl>>> = ({ signal }) => getAdminPresignedUrl(objectName,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: objectName !== null && objectName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminPresignedUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminPresignedUrl>>>
export type GetAdminPresignedUrlQueryError = HTTPValidationError


export function useGetAdminPresignedUrl<TData = Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError = HTTPValidationError>(
 objectName: string,
    params: undefined |  GetAdminPresignedUrlParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminPresignedUrl>>,
          TError,
          Awaited<ReturnType<typeof getAdminPresignedUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminPresignedUrl<TData = Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError = HTTPValidationError>(
 objectName: string,
    params?: GetAdminPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminPresignedUrl>>,
          TError,
          Awaited<ReturnType<typeof getAdminPresignedUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminPresignedUrl<TData = Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError = HTTPValidationError>(
 objectName: string,
    params?: GetAdminPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Presigned Url
 */

export function useGetAdminPresignedUrl<TData = Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError = HTTPValidationError>(
 objectName: string,
    params?: GetAdminPresignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminPresignedUrl>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminPresignedUrlQueryOptions(objectName,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






