/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.6
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListAdminSitesParams,
  PaginatedResponseSite,
  Site,
  SiteCreate,
  SiteUpdate
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListAdminSitesUrl = (params?: ListAdminSitesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/sites?${stringifiedParams}` : `/admin/v1/sites`
}

/**
 * @summary List Sites
 */
export const listAdminSites = async (params?: ListAdminSitesParams, options?: RequestInit): Promise<PaginatedResponseSite | null> => {

  return customFetch<PaginatedResponseSite | null>(getListAdminSitesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAdminSitesQueryKey = (params?: ListAdminSitesParams,) => {
    return [
    `/admin/v1/sites`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAdminSitesQueryOptions = <TData = Awaited<ReturnType<typeof listAdminSites>>, TError = HTTPValidationError>(params?: ListAdminSitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminSites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminSitesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminSites>>> = ({ signal }) => listAdminSites(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminSites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminSitesQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminSites>>>
export type ListAdminSitesQueryError = HTTPValidationError


export function useListAdminSites<TData = Awaited<ReturnType<typeof listAdminSites>>, TError = HTTPValidationError>(
 params: undefined |  ListAdminSitesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminSites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminSites>>,
          TError,
          Awaited<ReturnType<typeof listAdminSites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminSites<TData = Awaited<ReturnType<typeof listAdminSites>>, TError = HTTPValidationError>(
 params?: ListAdminSitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminSites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminSites>>,
          TError,
          Awaited<ReturnType<typeof listAdminSites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminSites<TData = Awaited<ReturnType<typeof listAdminSites>>, TError = HTTPValidationError>(
 params?: ListAdminSitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminSites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Sites
 */

export function useListAdminSites<TData = Awaited<ReturnType<typeof listAdminSites>>, TError = HTTPValidationError>(
 params?: ListAdminSitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminSites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminSitesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateAdminSiteUrl = () => {




  return `/admin/v1/sites`
}

/**
 * @summary Create Site
 */
export const createAdminSite = async (siteCreate: SiteCreate, options?: RequestInit): Promise<Site | null> => {

  return customFetch<Site | null>(getCreateAdminSiteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(siteCreate)
  }
);}




export const getCreateAdminSiteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminSite>>, TError,{data: SiteCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createAdminSite>>, TError,{data: SiteCreate}, TContext> => {

const mutationKey = ['createAdminSite'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdminSite>>, {data: SiteCreate}> = (props) => {
          const {data} = props ?? {};

          return  createAdminSite(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAdminSiteMutationResult = NonNullable<Awaited<ReturnType<typeof createAdminSite>>>
    export type CreateAdminSiteMutationBody = SiteCreate
    export type CreateAdminSiteMutationError = HTTPValidationError

    /**
 * @summary Create Site
 */
export const useCreateAdminSite = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminSite>>, TError,{data: SiteCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAdminSite>>,
        TError,
        {data: SiteCreate},
        TContext
      > => {
      return useMutation(getCreateAdminSiteMutationOptions(options), queryClient);
    }
    export const getGetAdminSiteUrl = (siteId: number,) => {




  return `/admin/v1/sites/${siteId}`
}

/**
 * @summary Get Site
 */
export const getAdminSite = async (siteId: number, options?: RequestInit): Promise<Site | null> => {

  return customFetch<Site | null>(getGetAdminSiteUrl(siteId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminSiteQueryKey = (siteId: number,) => {
    return [
    `/admin/v1/sites/${siteId}`
    ] as const;
    }


export const getGetAdminSiteQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSite>>, TError = HTTPValidationError>(siteId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSite>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSiteQueryKey(siteId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSite>>> = ({ signal }) => getAdminSite(siteId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: siteId !== null && siteId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSite>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminSiteQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSite>>>
export type GetAdminSiteQueryError = HTTPValidationError


export function useGetAdminSite<TData = Awaited<ReturnType<typeof getAdminSite>>, TError = HTTPValidationError>(
 siteId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSite>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSite>>,
          TError,
          Awaited<ReturnType<typeof getAdminSite>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSite<TData = Awaited<ReturnType<typeof getAdminSite>>, TError = HTTPValidationError>(
 siteId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSite>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSite>>,
          TError,
          Awaited<ReturnType<typeof getAdminSite>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSite<TData = Awaited<ReturnType<typeof getAdminSite>>, TError = HTTPValidationError>(
 siteId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSite>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Site
 */

export function useGetAdminSite<TData = Awaited<ReturnType<typeof getAdminSite>>, TError = HTTPValidationError>(
 siteId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSite>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminSiteQueryOptions(siteId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateAdminSiteUrl = (siteId: number,) => {




  return `/admin/v1/sites/${siteId}`
}

/**
 * @summary Update Site
 */
export const updateAdminSite = async (siteId: number,
    siteUpdate: SiteUpdate, options?: RequestInit): Promise<Site | null> => {

  return customFetch<Site | null>(getUpdateAdminSiteUrl(siteId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(siteUpdate)
  }
);}




export const getUpdateAdminSiteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminSite>>, TError,{siteId: number;data: SiteUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminSite>>, TError,{siteId: number;data: SiteUpdate}, TContext> => {

const mutationKey = ['updateAdminSite'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminSite>>, {siteId: number;data: SiteUpdate}> = (props) => {
          const {siteId,data} = props ?? {};

          return  updateAdminSite(siteId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminSiteMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminSite>>>
    export type UpdateAdminSiteMutationBody = SiteUpdate
    export type UpdateAdminSiteMutationError = HTTPValidationError

    /**
 * @summary Update Site
 */
export const useUpdateAdminSite = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminSite>>, TError,{siteId: number;data: SiteUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminSite>>,
        TError,
        {siteId: number;data: SiteUpdate},
        TContext
      > => {
      return useMutation(getUpdateAdminSiteMutationOptions(options), queryClient);
    }
    export const getDeleteAdminSiteUrl = (siteId: number,) => {




  return `/admin/v1/sites/${siteId}`
}

/**
 * @summary Delete Site
 */
export const deleteAdminSite = async (siteId: number, options?: RequestInit): Promise<null> => {

  return customFetch<null>(getDeleteAdminSiteUrl(siteId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAdminSiteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminSite>>, TError,{siteId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminSite>>, TError,{siteId: number}, TContext> => {

const mutationKey = ['deleteAdminSite'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminSite>>, {siteId: number}> = (props) => {
          const {siteId} = props ?? {};

          return  deleteAdminSite(siteId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminSiteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminSite>>>

    export type DeleteAdminSiteMutationError = HTTPValidationError

    /**
 * @summary Delete Site
 */
export const useDeleteAdminSite = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminSite>>, TError,{siteId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminSite>>,
        TError,
        {siteId: number},
        TContext
      > => {
      return useMutation(getDeleteAdminSiteMutationOptions(options), queryClient);
    }
    export const getGetAdminSiteBySlugUrl = (slug: string,) => {




  return `/admin/v1/sites:bySlug/${slug}`
}

/**
 * @summary Get Site By Slug
 */
export const getAdminSiteBySlug = async (slug: string, options?: RequestInit): Promise<Site | null> => {

  return customFetch<Site | null>(getGetAdminSiteBySlugUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminSiteBySlugQueryKey = (slug: string,) => {
    return [
    `/admin/v1/sites:bySlug/${slug}`
    ] as const;
    }


export const getGetAdminSiteBySlugQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError = HTTPValidationError>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSiteBySlugQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSiteBySlug>>> = ({ signal }) => getAdminSiteBySlug(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminSiteBySlugQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSiteBySlug>>>
export type GetAdminSiteBySlugQueryError = HTTPValidationError


export function useGetAdminSiteBySlug<TData = Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError = HTTPValidationError>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSiteBySlug>>,
          TError,
          Awaited<ReturnType<typeof getAdminSiteBySlug>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSiteBySlug<TData = Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSiteBySlug>>,
          TError,
          Awaited<ReturnType<typeof getAdminSiteBySlug>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSiteBySlug<TData = Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Site By Slug
 */

export function useGetAdminSiteBySlug<TData = Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError = HTTPValidationError>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSiteBySlug>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminSiteBySlugQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






