/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.7
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FeedbackListPage,
  FeedbackStats,
  GetAdminFeedbackListParams,
  GetAdminFeedbackStatsParams,
  HTTPValidationError
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetAdminFeedbackStatsUrl = (params: GetAdminFeedbackStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/feedback/stats?${stringifiedParams}` : `/admin/v1/feedback/stats`
}

/**
 * 单站点反馈聚合：up/down 总数 + 差评原因分布。
 * @summary Get Feedback Stats
 */
export const getAdminFeedbackStats = async (params: GetAdminFeedbackStatsParams, options?: RequestInit): Promise<FeedbackStats | null> => {

  return customFetch<FeedbackStats | null>(getGetAdminFeedbackStatsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminFeedbackStatsQueryKey = (params?: GetAdminFeedbackStatsParams,) => {
    return [
    `/admin/v1/feedback/stats`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminFeedbackStatsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError = HTTPValidationError>(params: GetAdminFeedbackStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminFeedbackStatsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminFeedbackStats>>> = ({ signal }) => getAdminFeedbackStats(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminFeedbackStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminFeedbackStats>>>
export type GetAdminFeedbackStatsQueryError = HTTPValidationError


export function useGetAdminFeedbackStats<TData = Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError = HTTPValidationError>(
 params: GetAdminFeedbackStatsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminFeedbackStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminFeedbackStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminFeedbackStats<TData = Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError = HTTPValidationError>(
 params: GetAdminFeedbackStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminFeedbackStats>>,
          TError,
          Awaited<ReturnType<typeof getAdminFeedbackStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminFeedbackStats<TData = Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError = HTTPValidationError>(
 params: GetAdminFeedbackStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Feedback Stats
 */

export function useGetAdminFeedbackStats<TData = Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError = HTTPValidationError>(
 params: GetAdminFeedbackStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminFeedbackStatsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetAdminFeedbackListUrl = (params: GetAdminFeedbackListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/feedback/list?${stringifiedParams}` : `/admin/v1/feedback/list`
}

/**
 * 分页列出反馈 + 关联的助手消息内容。默认按时间倒序。
 * @summary List Feedback
 */
export const getAdminFeedbackList = async (params: GetAdminFeedbackListParams, options?: RequestInit): Promise<FeedbackListPage | null> => {

  return customFetch<FeedbackListPage | null>(getGetAdminFeedbackListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminFeedbackListQueryKey = (params?: GetAdminFeedbackListParams,) => {
    return [
    `/admin/v1/feedback/list`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminFeedbackListQueryOptions = <TData = Awaited<ReturnType<typeof getAdminFeedbackList>>, TError = HTTPValidationError>(params: GetAdminFeedbackListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminFeedbackListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminFeedbackList>>> = ({ signal }) => getAdminFeedbackList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminFeedbackListQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminFeedbackList>>>
export type GetAdminFeedbackListQueryError = HTTPValidationError


export function useGetAdminFeedbackList<TData = Awaited<ReturnType<typeof getAdminFeedbackList>>, TError = HTTPValidationError>(
 params: GetAdminFeedbackListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminFeedbackList>>,
          TError,
          Awaited<ReturnType<typeof getAdminFeedbackList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminFeedbackList<TData = Awaited<ReturnType<typeof getAdminFeedbackList>>, TError = HTTPValidationError>(
 params: GetAdminFeedbackListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminFeedbackList>>,
          TError,
          Awaited<ReturnType<typeof getAdminFeedbackList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminFeedbackList<TData = Awaited<ReturnType<typeof getAdminFeedbackList>>, TError = HTTPValidationError>(
 params: GetAdminFeedbackListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Feedback
 */

export function useGetAdminFeedbackList<TData = Awaited<ReturnType<typeof getAdminFeedbackList>>, TError = HTTPValidationError>(
 params: GetAdminFeedbackListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminFeedbackList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminFeedbackListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






