/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.5
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListAdminTenantsParams,
  PaginatedResponseTenantEESchema,
  TenantCreateRequest,
  TenantEESchema,
  TenantEEUpdate
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListAdminTenantsUrl = (params?: ListAdminTenantsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/v1/tenants?${stringifiedParams}` : `/admin/v1/tenants`
}

/**
 * 获取租户列表
仅限系统管理员 (ADMIN) 访问
 * @summary List Tenants
 */
export const listAdminTenants = async (params?: ListAdminTenantsParams, options?: RequestInit): Promise<PaginatedResponseTenantEESchema | null> => {

  return customFetch<PaginatedResponseTenantEESchema | null>(getListAdminTenantsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAdminTenantsQueryKey = (params?: ListAdminTenantsParams,) => {
    return [
    `/admin/v1/tenants`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAdminTenantsQueryOptions = <TData = Awaited<ReturnType<typeof listAdminTenants>>, TError = HTTPValidationError>(params?: ListAdminTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTenants>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAdminTenantsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminTenants>>> = ({ signal }) => listAdminTenants(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminTenants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdminTenantsQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminTenants>>>
export type ListAdminTenantsQueryError = HTTPValidationError


export function useListAdminTenants<TData = Awaited<ReturnType<typeof listAdminTenants>>, TError = HTTPValidationError>(
 params: undefined |  ListAdminTenantsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTenants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminTenants>>,
          TError,
          Awaited<ReturnType<typeof listAdminTenants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminTenants<TData = Awaited<ReturnType<typeof listAdminTenants>>, TError = HTTPValidationError>(
 params?: ListAdminTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTenants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdminTenants>>,
          TError,
          Awaited<ReturnType<typeof listAdminTenants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAdminTenants<TData = Awaited<ReturnType<typeof listAdminTenants>>, TError = HTTPValidationError>(
 params?: ListAdminTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTenants>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Tenants
 */

export function useListAdminTenants<TData = Awaited<ReturnType<typeof listAdminTenants>>, TError = HTTPValidationError>(
 params?: ListAdminTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminTenants>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminTenantsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateAdminTenantUrl = () => {




  return `/admin/v1/tenants`
}

/**
 * 创建新租户
 * @summary Create Tenant
 */
export const createAdminTenant = async (tenantCreateRequest: TenantCreateRequest, options?: RequestInit): Promise<TenantEESchema | null> => {

  return customFetch<TenantEESchema | null>(getCreateAdminTenantUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tenantCreateRequest)
  }
);}




export const getCreateAdminTenantMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminTenant>>, TError,{data: TenantCreateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createAdminTenant>>, TError,{data: TenantCreateRequest}, TContext> => {

const mutationKey = ['createAdminTenant'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdminTenant>>, {data: TenantCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createAdminTenant(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAdminTenantMutationResult = NonNullable<Awaited<ReturnType<typeof createAdminTenant>>>
    export type CreateAdminTenantMutationBody = TenantCreateRequest
    export type CreateAdminTenantMutationError = HTTPValidationError

    /**
 * @summary Create Tenant
 */
export const useCreateAdminTenant = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminTenant>>, TError,{data: TenantCreateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAdminTenant>>,
        TError,
        {data: TenantCreateRequest},
        TContext
      > => {
      return useMutation(getCreateAdminTenantMutationOptions(options), queryClient);
    }
    export const getGetAdminTenantUrl = (tenantId: number,) => {




  return `/admin/v1/tenants/${tenantId}`
}

/**
 * 获取租户详情
 * @summary Get Tenant
 */
export const getAdminTenant = async (tenantId: number, options?: RequestInit): Promise<TenantEESchema | null> => {

  return customFetch<TenantEESchema | null>(getGetAdminTenantUrl(tenantId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminTenantQueryKey = (tenantId: number,) => {
    return [
    `/admin/v1/tenants/${tenantId}`
    ] as const;
    }


export const getGetAdminTenantQueryOptions = <TData = Awaited<ReturnType<typeof getAdminTenant>>, TError = HTTPValidationError>(tenantId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTenant>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminTenantQueryKey(tenantId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminTenant>>> = ({ signal }) => getAdminTenant(tenantId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: tenantId !== null && tenantId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminTenant>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminTenantQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminTenant>>>
export type GetAdminTenantQueryError = HTTPValidationError


export function useGetAdminTenant<TData = Awaited<ReturnType<typeof getAdminTenant>>, TError = HTTPValidationError>(
 tenantId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTenant>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTenant>>,
          TError,
          Awaited<ReturnType<typeof getAdminTenant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminTenant<TData = Awaited<ReturnType<typeof getAdminTenant>>, TError = HTTPValidationError>(
 tenantId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTenant>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminTenant>>,
          TError,
          Awaited<ReturnType<typeof getAdminTenant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminTenant<TData = Awaited<ReturnType<typeof getAdminTenant>>, TError = HTTPValidationError>(
 tenantId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTenant>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Tenant
 */

export function useGetAdminTenant<TData = Awaited<ReturnType<typeof getAdminTenant>>, TError = HTTPValidationError>(
 tenantId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminTenant>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminTenantQueryOptions(tenantId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateAdminTenantUrl = (tenantId: number,) => {




  return `/admin/v1/tenants/${tenantId}`
}

/**
 * 更新租户
 * @summary Update Tenant
 */
export const updateAdminTenant = async (tenantId: number,
    tenantEEUpdate: TenantEEUpdate, options?: RequestInit): Promise<TenantEESchema | null> => {

  return customFetch<TenantEESchema | null>(getUpdateAdminTenantUrl(tenantId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tenantEEUpdate)
  }
);}




export const getUpdateAdminTenantMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminTenant>>, TError,{tenantId: number;data: TenantEEUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminTenant>>, TError,{tenantId: number;data: TenantEEUpdate}, TContext> => {

const mutationKey = ['updateAdminTenant'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminTenant>>, {tenantId: number;data: TenantEEUpdate}> = (props) => {
          const {tenantId,data} = props ?? {};

          return  updateAdminTenant(tenantId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminTenantMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminTenant>>>
    export type UpdateAdminTenantMutationBody = TenantEEUpdate
    export type UpdateAdminTenantMutationError = HTTPValidationError

    /**
 * @summary Update Tenant
 */
export const useUpdateAdminTenant = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminTenant>>, TError,{tenantId: number;data: TenantEEUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminTenant>>,
        TError,
        {tenantId: number;data: TenantEEUpdate},
        TContext
      > => {
      return useMutation(getUpdateAdminTenantMutationOptions(options), queryClient);
    }
    export const getDeleteAdminTenantUrl = (tenantId: number,) => {




  return `/admin/v1/tenants/${tenantId}`
}

/**
 * 删除租户
 * @summary Delete Tenant
 */
export const deleteAdminTenant = async (tenantId: number, options?: RequestInit): Promise<null> => {

  return customFetch<null>(getDeleteAdminTenantUrl(tenantId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAdminTenantMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminTenant>>, TError,{tenantId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminTenant>>, TError,{tenantId: number}, TContext> => {

const mutationKey = ['deleteAdminTenant'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminTenant>>, {tenantId: number}> = (props) => {
          const {tenantId} = props ?? {};

          return  deleteAdminTenant(tenantId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminTenantMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminTenant>>>

    export type DeleteAdminTenantMutationError = HTTPValidationError

    /**
 * @summary Delete Tenant
 */
export const useDeleteAdminTenant = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminTenant>>, TError,{tenantId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminTenant>>,
        TError,
        {tenantId: number},
        TContext
      > => {
      return useMutation(getDeleteAdminTenantMutationOptions(options), queryClient);
    }
