/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * CatWiki Admin API
 * 管理后台 API - 提供完整的增删改查功能
 * OpenAPI spec version: 1.1.6
 */
/**
 * 各模型项配置 (chat/embedding/...)
 */
export type AIConfigResponseConfigs = { [key: string]: unknown };

/**
 * 元数据 (如 Fallback 状态)
 */
export type AIConfigResponseMeta = { [key: string]: unknown } | null;

/**
 * 平台默认配置 (参考用)
 */
export type AIConfigResponsePlatformDefaults = { [key: string]: unknown } | null;

/**
 * AI 配置专用响应结构 (扁平化且优雅)
 */
export interface AIConfigResponse {
  /** 各模型项配置 (chat/embedding/...) */
  configs: AIConfigResponseConfigs;
  /** 元数据 (如 Fallback 状态) */
  meta?: AIConfigResponseMeta;
  /** 平台默认配置 (参考用) */
  platform_defaults?: AIConfigResponsePlatformDefaults;
}

/**
 * 配置模式: custom=自定义, platform=使用平台资源
 */
export type ModelConfigMode = typeof ModelConfigMode[keyof typeof ModelConfigMode];


export const ModelConfigMode = {
  custom: 'custom',
  platform: 'platform',
} as const;

/**
 * 额外请求体参数 (例如: {"chat_template_kwargs": {"enable_thinking": true}})
 */
export type ModelConfigExtraBody = { [key: string]: unknown } | null;

/**
 * 单个模型配置
 */
export interface ModelConfig {
  /** 模型提供商 */
  provider: string;
  /** 模型名称 */
  model: string;
  /** API Key */
  api_key: string;
  /** API Base URL */
  base_url: string;
  /** Embedding 维度 (自动探测) */
  dimension?: number | null;
  /** 配置模式: custom=自定义, platform=使用平台资源 */
  mode?: ModelConfigMode;
  /** 是否支持视觉/多模态 */
  is_vision?: boolean;
  /** 额外请求体参数 (例如: {"chat_template_kwargs": {"enable_thinking": true}}) */
  extra_body?: ModelConfigExtraBody;
}

/**
 * 更新 AI 配置
 */
export interface AIConfigUpdate {
  /** 对话模型配置 */
  chat?: ModelConfig | null;
  /** 向量模型配置 */
  embedding?: ModelConfig | null;
  /** 重排序模型配置 */
  rerank?: ModelConfig | null;
}

/**
 * 更新站点访问控制 (管理端请求)
 */
export interface AccessConfigUpdate {
  is_public?: boolean | null;
  /** 明文密码，后端自动哈希 */
  password?: string | null;
}

export type AiGenerateRequestFieldsItem = typeof AiGenerateRequestFieldsItem[keyof typeof AiGenerateRequestFieldsItem];


export const AiGenerateRequestFieldsItem = {
  summary: 'summary',
  tags: 'tags',
} as const;

/**
 * AI 生成字段请求
 */
export interface AiGenerateRequest {
  /**
     * 文章正文内容（前端截断后传入）
     * @minLength 1
     */
  content: string;
  /**
     * 需要生成的字段列表
     * @minItems 1
     */
  fields: AiGenerateRequestFieldsItem[];
  /** 摘要最大字数限制 */
  summary_max_length?: number | null;
  /** 标签最大个数限制 */
  tags_max_count?: number | null;
}

/**
 * AI 生成字段响应
 */
export interface AiGenerateResponse {
  /** 生成的文章摘要 */
  summary?: string | null;
  /** 生成的标签列表 */
  tags?: string[] | null;
}

/**
 * 问答机器人配置响应 (api_key 脱敏)
 */
export interface ApiBotConfigResponse {
  site_id: number;
  enabled: boolean;
  api_key: string;
  timeout: number;
}

/**
 * 更新问答机器人配置 (管理端请求)
 */
export interface ApiBotConfigUpdate {
  enabled?: boolean | null;
  api_key?: string | null;
  timeout?: number | null;
}

export interface BodyBatchUploadAdminFiles {
  /** 要上传的多个文件 */
  files: Blob[];
}

/**
 * 文档处理服务类型
 */
export type DocProcessorType = typeof DocProcessorType[keyof typeof DocProcessorType];


export const DocProcessorType = {
  Docling: 'Docling',
  MinerU: 'MinerU',
  PaddleOCR: 'PaddleOCR',
} as const;

export interface BodyImportDocument {
  file: Blob;
  site_id: number;
  collection_id: number;
  processor_type?: DocProcessorType;
  ocr_enabled?: boolean;
  extract_images?: boolean;
  extract_tables?: boolean;
  duplicate_strategy?: string;
  generate_summary?: boolean;
  generate_tags?: boolean;
  auto_vectorize?: boolean;
}

export interface BodyUploadAdminFile {
  /** 要上传的文件 */
  file: Blob;
}

export interface BodyUploadToDataSource {
  file: Blob;
  prefix?: string;
}

export type ChatMessageInputAdditionalKwargs = { [key: string]: unknown } | null;

/**
 * OpenAI 兼容的函数调用定义
 */
export interface FunctionCall {
  name: string;
  arguments: string;
}

/**
 * OpenAI 兼容的工具调用定义
 */
export interface ToolCall {
  id: string;
  type?: string;
  function: FunctionCall;
}

/**
 * OpenAI 兼容的聊天消息
 */
export interface ChatMessageInput {
  role: string;
  content?: string | null;
  name?: string | null;
  tool_calls?: ToolCall[] | null;
  tool_call_id?: string | null;
  additional_kwargs?: ChatMessageInputAdditionalKwargs;
}

export type ChatMessageOutputToolCallsItem = { [key: string]: unknown };

/**
 * 引用来源列表（每条消息专属）
 */
export type ChatMessageOutputSources = { [key: string]: unknown }[] | null;

/**
 * 其他元数据
 */
export type ChatMessageOutputAdditionalKwargs = { [key: string]: unknown } | null;

/**
 * 单条消息模型（OpenAI 格式）
 */
export interface ChatMessageOutput {
  /** 角色: user/assistant/system */
  role: string;
  /** 内容，tool_call 时可能为空 */
  content?: string | null;
  /** 消息ID */
  id?: string | null;
  /** 工具调用列表 */
  tool_calls?: ChatMessageOutputToolCallsItem[];
  /** 工具调用ID（role=tool时） */
  tool_call_id?: string | null;
  /** 引用来源列表（每条消息专属） */
  sources?: ChatMessageOutputSources;
  /** 其他元数据 */
  additional_kwargs?: ChatMessageOutputAdditionalKwargs;
  /** 消息创建时间 */
  created_at?: string | null;
}

/**
 * 会话响应模型
 */
export interface ChatSessionResponse {
  /** 会话 thread_id */
  thread_id: string;
  /** 站点ID */
  site_id: number;
  /** 租户ID */
  tenant_id?: number | null;
  /** 会员ID或访客标识 */
  member_id?: string | null;
  /** 会话标题 */
  title?: string | null;
  /** 来源渠道: web_chat / wecom_kefu / wecom_app / wecom_smart / dingtalk_app / feishu_app */
  source?: string | null;
  id: number;
  /** 最后消息预览 */
  last_message?: string | null;
  /** 最后消息角色 */
  last_message_role?: string | null;
  /** 消息数量 */
  message_count?: number;
  created_at: string;
  updated_at: string;
}

/**
 * 会话列表响应
 */
export interface ChatSessionListResponse {
  list: ChatSessionResponse[];
  total: number;
  page: number;
  size: number;
}

/**
 * 会话详细消息列表响应
 */
export interface ChatSessionMessagesResponse {
  thread_id: string;
  messages: ChatMessageOutput[];
}

export type ClientSiteWebWidget = { [key: string]: unknown } | null;

/**
 * 快速问题
 */
export interface QuickQuestion {
  /** 问题内容 */
  text: string;
  /** 问题分类 */
  category?: string | null;
}

/**
 * 客户端展示用的站点信息 (精简版)
 */
export interface ClientSite {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  icon?: string | null;
  article_count?: number;
  view_count?: number;
  tenant_id?: number | null;
  tenant_slug?: string | null;
  theme_color?: string | null;
  layout_mode?: string | null;
  quick_questions?: QuickQuestion[] | null;
  web_widget?: ClientSiteWebWidget;
  is_public?: boolean;
  requires_password?: boolean;
  has_password?: boolean;
}

/**
 * 合集详情
 */
export interface Collection {
  id: number;
  created_at: string;
  updated_at: string;
  /**
     * 合集名称
     * @maxLength 200
     */
  title: string;
  /** 所属租户ID */
  tenant_id?: number | null;
  /** 所属站点ID */
  site_id: number;
  /** 父合集ID */
  parent_id?: number | null;
  /** 排序 */
  order?: number;
}

/**
 * 合集祖先节点
 */
export interface CollectionAncestor {
  /** 合集ID */
  id: number;
  /** 合集名称 */
  title: string;
}

/**
 * 创建合集
 */
export interface CollectionCreate {
  /**
     * 合集名称
     * @maxLength 200
     */
  title: string;
  /** 所属租户ID */
  tenant_id?: number | null;
  /** 所属站点ID */
  site_id: number;
  /** 父合集ID */
  parent_id?: number | null;
  /** 排序 */
  order?: number;
}

/**
 * 文档关联的合集信息
 */
export interface CollectionInfo {
  /** 合集ID */
  id: number;
  /** 合集名称 */
  title: string;
  /** 父合集ID */
  parent_id?: number | null;
  /** 祖先合集链（从根到父级） */
  ancestors?: CollectionAncestor[];
  /** 合集完整路径（如: 流式细胞术基础 > 仪器与试剂 > 选购指南） */
  path: string;
}

/**
 * 合集树形结构
 */
export interface CollectionTree {
  id: number;
  title: string;
  type?: string;
  children?: CollectionTree[] | null;
  status?: string | null;
  views?: number | null;
  tags?: string[] | null;
  collection_id?: number | null;
}

/**
 * 更新合集
 */
export interface CollectionUpdate {
  title?: string | null;
  parent_id?: number | null;
  order?: number | null;
}

export interface DailyViewTrend {
  date: string;
  views: number;
  unique_ips: number;
}

export type DataSourceConfig = { [key: string]: unknown };

/**
 * 数据源响应
 */
export interface DataSource {
  id: number;
  created_at: string;
  updated_at: string;
  tenant_id: number;
  name: string;
  type: string;
  description: string | null;
  config: DataSourceConfig;
}

/**
 * 类型: internal | s3
 */
export type DataSourceCreateType = typeof DataSourceCreateType[keyof typeof DataSourceCreateType];


export const DataSourceCreateType = {
  internal: 'internal',
  s3: 's3',
} as const;

/**
 * 连接配置（external S3 时必填）
 */
export type DataSourceCreateConfig = { [key: string]: unknown };

/**
 * 创建数据源
 */
export interface DataSourceCreate {
  /**
     * 数据源名称
     * @maxLength 100
     */
  name: string;
  /** 类型: internal | s3 */
  type: DataSourceCreateType;
  /** 描述 */
  description?: string | null;
  /** 连接配置（external S3 时必填） */
  config?: DataSourceCreateConfig;
}

/**
 * 从数据源导入文件请求
 */
export interface DataSourceImportRequest {
  /**
     * 要导入的 S3 对象路径列表
     * @minItems 1
     */
  keys: string[];
  /** 目标站点ID */
  site_id: number;
  /** 目标合集ID */
  collection_id: number;
  /** 解析器类型 */
  processor_type?: string;
  /** 是否启用OCR */
  ocr_enabled?: boolean;
  /** 是否提取图片 */
  extract_images?: boolean;
  /** 是否提取表格 */
  extract_tables?: boolean;
  /** 重复文件策略: skip | allow */
  duplicate_strategy?: string;
  /** 是否AI生成摘要 */
  generate_summary?: boolean;
  /** 是否AI生成标签 */
  generate_tags?: boolean;
  /** 解析完成后是否自动入向量库 */
  auto_vectorize?: boolean;
}

export type DataSourceUpdateConfig = { [key: string]: unknown } | null;

/**
 * 更新数据源
 */
export interface DataSourceUpdate {
  name?: string | null;
  description?: string | null;
  config?: DataSourceUpdateConfig;
}

/**
 * 额外配置（如 is_ocr）
 */
export type DocProcessorConfigConfig = { [key: string]: unknown };

/**
 * 单个文档处理服务配置
 */
export interface DocProcessorConfig {
  /** 唯一标识符 */
  id?: string;
  /** 服务名称（用于标识） */
  name: string;
  /** 服务类型 */
  type: DocProcessorType;
  /** API 端点地址 */
  base_url: string;
  /** API 密钥（可选） */
  api_key?: string;
  /** 是否启用 */
  enabled?: boolean;
  /** 额外配置（如 is_ocr） */
  config?: DocProcessorConfigConfig;
  /** 服务来源 */
  origin?: 'platform' | 'tenant' | null;
}

/**
 * 文档处理服务最终响应
 */
export interface DocProcessorResponse {
  /** 服务列表 (已合并租户与平台资源) */
  processors: DocProcessorConfig[];
}

/**
 * 更新文档处理服务配置
 */
export interface DocProcessorsUpdate {
  /** 服务列表 */
  processors: DocProcessorConfig[];
}

/**
 * 解析元数据
 */
export type DocumentParseMeta = { [key: string]: unknown } | null;

/**
 * 文档状态枚举
 */
export type DocumentStatus = typeof DocumentStatus[keyof typeof DocumentStatus];


export const DocumentStatus = {
  draft: 'draft',
  published: 'published',
} as const;

/**
 * 向量化状态枚举
 */
export type VectorStatus = typeof VectorStatus[keyof typeof VectorStatus];


export const VectorStatus = {
  none: 'none',
  outdated: 'outdated',
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

/**
 * 文档详情
 */
export interface Document {
  id: number;
  created_at: string;
  updated_at: string;
  /**
     * 文章标题
     * @maxLength 200
     */
  title: string;
  /** 租户ID */
  tenant_id?: number | null;
  /** 文章内容(Markdown) */
  content?: string | null;
  /** 文章摘要 */
  summary?: string | null;
  /** 封面图片URL */
  cover_image?: string | null;
  /** 所属站点ID */
  site_id: number;
  /** 所属合集ID（必填） */
  collection_id: number;
  /** 分类 */
  category?: string | null;
  /**
     * 作者
     * @maxLength 100
     */
  author: string;
  /** 状态: published, draft */
  status?: DocumentStatus;
  /** 向量化状态: none, pending, processing, completed, failed */
  vector_status?: VectorStatus;
  /** 标签列表 */
  tags?: string[] | null;
  /** 浏览量 */
  views?: number;
  /** 预计阅读时间(分钟) */
  reading_time?: number;
  /** 向量化失败错误信息 */
  vector_error?: string | null;
  /** 最后向量化完成时间 */
  vectorized_at?: string | null;
  /** 站点名称 */
  site_name?: string | null;
  /** 站点标识 */
  site_slug?: string | null;
  /** 租户标识 */
  tenant_slug?: string | null;
  /** 所属合集信息 */
  collection?: CollectionInfo | null;
  /** 解析元数据 */
  parse_meta?: DocumentParseMeta;
}

/**
 * 解析元数据（解析器类型、文件路径等）
 */
export type DocumentCreateParseMeta = { [key: string]: unknown } | null;

/**
 * 创建文档
 */
export interface DocumentCreate {
  /**
     * 文章标题
     * @maxLength 200
     */
  title: string;
  /** 所属租户ID */
  tenant_id?: number | null;
  /** 文章内容(Markdown) */
  content?: string | null;
  /** 文章摘要 */
  summary?: string | null;
  /** 封面图片URL */
  cover_image?: string | null;
  /** 所属站点ID */
  site_id: number;
  /** 所属合集ID（必填） */
  collection_id: number;
  /** 分类 */
  category?: string | null;
  /**
     * 作者
     * @maxLength 100
     */
  author: string;
  /** 状态: published, draft */
  status?: DocumentStatus;
  /** 向量化状态: none, pending, processing, completed, failed */
  vector_status?: VectorStatus;
  /** 标签列表 */
  tags?: string[] | null;
  /** 解析元数据（解析器类型、文件路径等） */
  parse_meta?: DocumentCreateParseMeta;
}

/**
 * 更新文档
 */
export interface DocumentUpdate {
  title?: string | null;
  content?: string | null;
  summary?: string | null;
  cover_image?: string | null;
  collection_id?: number | null;
  category?: string | null;
  author?: string | null;
  status?: DocumentStatus | null;
  vector_status?: VectorStatus | null;
  tags?: string[] | null;
}

export interface FeedbackListItem {
  id: number;
  chat_message_id: number;
  thread_id: string;
  rating: string;
  reason: string | null;
  member_id: string;
  created_at: string;
  message_content: string | null;
}

export interface FeedbackListPage {
  list: FeedbackListItem[];
  total: number;
  page: number;
  size: number;
}

/**
 * POST 响应；撤销时 ``rating`` 为 null，前端按需更新本地 state。
 */
export interface FeedbackOut {
  chat_message_id: number;
  member_id: string;
  rating: 'up' | 'down' | null;
  reason: 'incorrect' | 'irrelevant' | 'incomplete' | 'slow' | null;
}

export type FeedbackStatsReasons = {[key: string]: number};

export interface FeedbackStats {
  total: number;
  up: number;
  down: number;
  up_rate: number;
  reasons: FeedbackStatsReasons;
}

/**
 * POST /v1/chat/feedback 请求体。``rating=None`` 表示撤销反馈。
 */
export interface FeedbackSubmit {
  /** 会话 ID */
  thread_id: string;
  /**
     * 本 thread 内 assistant 消息的 0-based 序号
     * @minimum 0
     */
  message_seq: number;
  /**
     * 访客/会员 ID
     * @maxLength 64
     */
  member_id: string;
  /** up / down / null（撤销） */
  rating?: 'up' | 'down' | null;
  /** 差评原因；仅 down 有意义 */
  reason?: 'incorrect' | 'irrelevant' | 'incomplete' | 'slow' | null;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * 各组件检查状态
 */
export type HealthResponseChecks = {[key: string]: string};

/**
 * 健康检查响应
 */
export interface HealthResponse {
  /** 服务总体状态: healthy, degraded, unhealthy */
  status: string;
  /** API 版本 */
  version: string;
  /** 运行环境 */
  environment: string;
  /** CatWiki 版本 (community | enterprise) */
  edition: string;
  /** 是否已获得企业级授权 */
  is_licensed: boolean;
  /** 检查时间戳 */
  timestamp: string;
  /** 各组件检查状态 */
  checks: HealthResponseChecks;
}

export interface HourlyDistribution {
  hour: number;
  count: number;
}

export interface ModelObject {
  id: string;
  object?: string;
  created?: number;
  owned_by?: string;
}

export interface ModelList {
  object?: string;
  data: ModelObject[];
}

/**
 * 移动合集请求
 */
export interface MoveCollectionRequest {
  /** 目标父合集ID，null表示移到根级别 */
  target_parent_id?: number | null;
  /**
     * 目标位置索引，0表示第一个
     * @minimum 0
     */
  target_position: number;
}

export type OpenAIChatCompletionRequestLogitBias = {[key: string]: number} | null;

export type OpenAIChatCompletionRequestResponseFormat = { [key: string]: unknown } | null;

export type OpenAIChatCompletionRequestTools = { [key: string]: unknown }[] | null;

export type OpenAIChatCompletionRequestToolChoice = string | { [key: string]: unknown } | null;

export type OpenAIChatCompletionRequestStreamOptions = { [key: string]: unknown } | null;

/**
 * 严格 OpenAI 兼容聊天请求（用于对外 Bot API）
 */
export interface OpenAIChatCompletionRequest {
  model: string;
  messages: ChatMessageInput[];
  temperature?: number | null;
  top_p?: number | null;
  n?: number | null;
  stream?: boolean | null;
  stop?: string | string[] | null;
  max_tokens?: number | null;
  presence_penalty?: number | null;
  frequency_penalty?: number | null;
  logit_bias?: OpenAIChatCompletionRequestLogitBias;
  user?: string | null;
  response_format?: OpenAIChatCompletionRequestResponseFormat;
  seed?: number | null;
  tools?: OpenAIChatCompletionRequestTools;
  tool_choice?: OpenAIChatCompletionRequestToolChoice;
  stream_options?: OpenAIChatCompletionRequestStreamOptions;
  reasoning_effort?: string | null;
  verbosity?: string | null;
  serviceTier?: string | null;
}

/**
 * 分页信息模型
 */
export interface PaginationInfo {
  /** 是否分页，1 表示是 */
  is_pager?: number;
  /** 当前页码 */
  page: number;
  /** 每页大小 */
  size: number;
  /** 总记录数 */
  total: number;
}

export interface PaginatedResponseClientSite {
  /** 数据列表 */
  list: ClientSite[];
  /** 分页信息 */
  pagination: PaginationInfo;
}

export interface PaginatedResponseCollection {
  /** 数据列表 */
  list: Collection[];
  /** 分页信息 */
  pagination: PaginationInfo;
}

export interface PaginatedResponseDocument {
  /** 数据列表 */
  list: Document[];
  /** 分页信息 */
  pagination: PaginationInfo;
}

/**
 * 机器人配置
 */
export type SiteBotConfig = { [key: string]: unknown } | null;

/**
 * 网页挂件配置
 */
export type SiteWebWidget = { [key: string]: unknown } | null;

/**
 * 站点详情
 */
export interface Site {
  id: number;
  created_at: string;
  updated_at: string;
  /**
     * 站点名称
     * @maxLength 100
     */
  name: string;
  /** 所属租户ID */
  tenant_id?: number | null;
  /**
     * 站点标识
     * @maxLength 200
     */
  slug: string;
  /** 站点描述 */
  description?: string | null;
  /** 图标URL或名称 */
  icon?: string | null;
  /** 状态: active, draft */
  status?: string;
  /** 主题色 */
  theme_color?: string | null;
  /** 布局模式: sidebar, top */
  layout_mode?: string | null;
  /** 快速问题配置 */
  quick_questions?: QuickQuestion[] | null;
  /** 机器人配置 */
  bot_config?: SiteBotConfig;
  /** 是否在对话页展示 AI 性能统计 trace */
  show_pipeline_trace?: boolean;
  /** 文章数量 */
  article_count?: number;
  /** 所属租户标识 */
  tenant_slug?: string | null;
  /** 网页挂件配置 */
  web_widget?: SiteWebWidget;
}

export interface PaginatedResponseSite {
  /** 数据列表 */
  list: Site[];
  /** 分页信息 */
  pagination: PaginationInfo;
}

export type TaskPayload = { [key: string]: unknown } | null;

export type TaskResult = { [key: string]: unknown } | null;

export interface Task {
  task_type: string;
  status: string;
  progress?: number;
  job_id?: string | null;
  site_id?: number | null;
  id: number;
  tenant_id: number;
  payload?: TaskPayload;
  result?: TaskResult;
  error?: string | null;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface PaginatedResponseTask {
  /** 数据列表 */
  list: Task[];
  /** 分页信息 */
  pagination: PaginationInfo;
}

export type TenantEESchemaAdvancedConfig = { [key: string]: unknown };

export interface TenantEESchema {
  max_sites?: number;
  max_documents?: number;
  max_storage_mb?: number;
  max_users?: number;
  plan?: string;
  platform_resources_allowed?: string[];
  contact_email?: string | null;
  contact_phone?: string | null;
  advanced_config?: TenantEESchemaAdvancedConfig;
  name: string;
  slug: string;
  domain?: string | null;
  logo_url?: string | null;
  description?: string | null;
  status?: string;
  id: number;
  created_at: string;
  updated_at: string;
  plan_expires_at?: string | null;
  /** 是否为演示模式 */
  readonly is_demo: boolean;
}

export interface PaginatedResponseTenantEESchema {
  /** 数据列表 */
  list: TenantEESchema[];
  /** 分页信息 */
  pagination: PaginationInfo;
}

/**
 * 用户角色枚举
 */
export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  admin: 'admin',
  tenant_admin: 'tenant_admin',
  site_admin: 'site_admin',
} as const;

/**
 * 用户状态枚举
 */
export type UserStatus = typeof UserStatus[keyof typeof UserStatus];


export const UserStatus = {
  active: 'active',
  inactive: 'inactive',
  pending: 'pending',
} as const;

/**
 * 用户列表项
 */
export interface UserListItem {
  id: number;
  name: string;
  email: string;
  role: UserRole;
  managed_site_ids: number[];
  status: UserStatus;
  last_login_at?: string | null;
  created_at: string;
}

export interface PaginatedResponseUserListItem {
  /** 数据列表 */
  list: UserListItem[];
  /** 分页信息 */
  pagination: PaginationInfo;
}

export type PaginatedResponseDictListItem = { [key: string]: unknown };

export interface PaginatedResponseDict {
  /** 数据列表 */
  list: PaginatedResponseDictListItem[];
  /** 分页信息 */
  pagination: PaginationInfo;
}

/**
 * 最近会话简报
 */
export interface RecentSession {
  thread_id: string;
  title: string;
  created_at: string;
  message_count: number;
  source?: string | null;
}

export interface RefererStat {
  source: string;
  count: number;
}

export interface RegionStat {
  region: string;
  count: number;
}

export interface ResponseOutputContent {
  type?: string;
  text: string;
}

export interface ResponseOutputItem {
  type?: string;
  id: string;
  role?: string;
  content: ResponseOutputContent[];
}

/**
 * 向量检索过滤器
 */
export interface VectorRetrieveFilter {
  /** 租户ID (可选过滤) */
  tenant_id?: number | null;
  /** 站点ID (可选过滤) */
  site_id?: number | null;
  /** 文档ID (可选过滤) */
  id?: string | null;
  /** 来源 (可选过滤) */
  source?: string | null;
}

/**
 * 标准 OpenAI Responses API 请求（含 CatWiki 扩展字段）
 */
export interface ResponsesAPIRequest {
  model?: string | null;
  input: string | ChatMessageInput[];
  instructions?: string | null;
  previous_response_id?: string | null;
  stream?: boolean | null;
  temperature?: number | null;
  max_output_tokens?: number | null;
  user?: string | null;
  filter?: VectorRetrieveFilter | null;
}

/**
 * OpenAI Responses API spec usage 对象。

与 ``ChatCompletionUsage`` 字段名不同 —— Responses API 用 ``input/output``，
Chat Completions 用 ``prompt/completion``。两边按各自 spec 单独定义，不复用。
 */
export interface ResponsesAPIUsage {
  input_tokens: number;
  output_tokens: number;
  total_tokens: number;
}

export interface ResponsesAPIResponse {
  id: string;
  object?: string;
  created_at?: number;
  status?: string;
  model: string;
  output: ResponseOutputItem[];
  usage?: ResponsesAPIUsage | null;
}

/**
 * 类型: file | dir
 */
export type S3FileItemType = typeof S3FileItemType[keyof typeof S3FileItemType];


export const S3FileItemType = {
  file: 'file',
  dir: 'dir',
} as const;

/**
 * S3 文件/目录项
 */
export interface S3FileItem {
  /** 文件或目录名（不含路径） */
  name: string;
  /** 完整对象路径 */
  path: string;
  /** 类型: file | dir */
  type: S3FileItemType;
  /** 文件大小（字节），目录为 None */
  size?: number | null;
  /** 最后修改时间（ISO格式） */
  last_modified?: string | null;
}

export interface TopDocument {
  document_id: number;
  title: string;
  views: number;
  unique_visitors: number;
}

export interface VisitorStat {
  ip: string;
  views: number;
  last_active: string;
  location: string;
}

/**
 * 站点数据分析概览响应
 */
export interface SiteAnalyticsResponse {
  trends: DailyViewTrend[];
  hourly_distribution: HourlyDistribution[];
  top_documents: TopDocument[];
  referer_stats: RefererStat[];
  visitor_stats: VisitorStat[];
  region_stats: RegionStat[];
}

/**
 * 机器人配置
 */
export type SiteCreateBotConfig = { [key: string]: unknown } | null;

/**
 * 创建站点
 */
export interface SiteCreate {
  /**
     * 站点名称
     * @maxLength 100
     */
  name: string;
  /** 所属租户ID */
  tenant_id?: number | null;
  /**
     * 站点标识
     * @maxLength 200
     */
  slug: string;
  /** 站点描述 */
  description?: string | null;
  /** 图标URL或名称 */
  icon?: string | null;
  /** 状态: active, draft */
  status?: string;
  /** 主题色 */
  theme_color?: string | null;
  /** 布局模式: sidebar, top */
  layout_mode?: string | null;
  /** 快速问题配置 */
  quick_questions?: QuickQuestion[] | null;
  /** 机器人配置 */
  bot_config?: SiteCreateBotConfig;
  /** 是否在对话页展示 AI 性能统计 trace */
  show_pipeline_trace?: boolean;
  /** 管理员邮箱 */
  admin_email?: string | null;
  /** 管理员姓名 */
  admin_name?: string | null;
  /** 管理员密码 */
  admin_password?: string | null;
}

/**
 * 站点 EE 配置响应
 */
export interface SiteEEConfigResponse {
  site_id: number;
  is_public?: boolean;
  has_password?: boolean;
  generated_password?: string | null;
}

/**
 * 统一站点 EE 配置响应
 */
export interface SiteEEConfigFullResponse {
  site_id: number;
  access: SiteEEConfigResponse;
  api_bot: ApiBotConfigResponse;
}

/**
 * 统一更新请求
 */
export interface SiteEEConfigUpdate {
  access?: AccessConfigUpdate | null;
  api_bot?: ApiBotConfigUpdate | null;
}

/**
 * 趋势数据
 */
export interface TrendData {
  date: string;
  sessions: number;
  messages: number;
}

/**
 * 站点统计数据
 */
export interface SiteStats {
  /** 文档总数 */
  total_documents: number;
  /** 总访问次数 */
  total_views: number;
  /** 今日浏览量 */
  views_today?: number;
  /** 今日独立IP数 */
  unique_ips_today?: number;
  /** 历史独立IP总数 */
  total_unique_ips?: number;
  /** AI会话总数 */
  total_chat_sessions?: number;
  /** AI消息总数 */
  total_chat_messages?: number;
  /** 活跃AI用户数 */
  active_chat_users?: number;
  /** 今日新增会话 */
  new_sessions_today?: number;
  /** 今日新增消息 */
  new_messages_today?: number;
  /** 最近7天趋势 */
  daily_trends?: TrendData[];
  /** 最近对话记录 */
  recent_sessions?: RecentSession[];
}

/**
 * 机器人配置
 */
export type SiteUpdateBotConfig = { [key: string]: unknown } | null;

/**
 * 更新站点
 */
export interface SiteUpdate {
  name?: string | null;
  slug?: string | null;
  description?: string | null;
  icon?: string | null;
  status?: string | null;
  theme_color?: string | null;
  layout_mode?: string | null;
  /** 快速问题配置 */
  quick_questions?: QuickQuestion[] | null;
  /** 机器人配置 */
  bot_config?: SiteUpdateBotConfig;
  /** 是否在对话页展示 AI 性能统计 trace */
  show_pipeline_trace?: boolean | null;
}

export type TenantCreateRequestAdvancedConfig = { [key: string]: unknown };

export interface TenantCreateRequest {
  max_sites?: number;
  max_documents?: number;
  max_storage_mb?: number;
  max_users?: number;
  plan?: string;
  platform_resources_allowed?: string[];
  contact_email?: string | null;
  contact_phone?: string | null;
  advanced_config?: TenantCreateRequestAdvancedConfig;
  plan_expires_at?: string | null;
  name: string;
  slug: string;
  domain?: string | null;
  logo_url?: string | null;
  description?: string | null;
  status?: string;
  admin_email: string;
  admin_password: string;
  admin_name?: string | null;
}

export type TenantEEUpdateAdvancedConfig = { [key: string]: unknown };

export interface TenantEEUpdate {
  max_sites?: number;
  max_documents?: number;
  max_storage_mb?: number;
  max_users?: number;
  plan?: string;
  platform_resources_allowed?: string[];
  contact_email?: string | null;
  contact_phone?: string | null;
  advanced_config?: TenantEEUpdateAdvancedConfig;
  name?: string | null;
  slug?: string | null;
  domain?: string | null;
  logo_url?: string | null;
  description?: string | null;
  status?: string;
  plan_expires_at?: string | null;
}

export interface TenantSchema {
  name: string;
  slug: string;
  domain?: string | null;
  logo_url?: string | null;
  description?: string | null;
  status?: string;
  id: number;
  created_at: string;
  updated_at: string;
  readonly is_demo: boolean;
}

/**
 * 模型类型
 */
export type TestConnectionRequestModelType = typeof TestConnectionRequestModelType[keyof typeof TestConnectionRequestModelType];


export const TestConnectionRequestModelType = {
  chat: 'chat',
  embedding: 'embedding',
  rerank: 'rerank',
} as const;

/**
 * 测试连接请求
 */
export interface TestConnectionRequest {
  /** 模型类型 */
  model_type: TestConnectionRequestModelType;
  /** 模型配置 */
  config: ModelConfig;
}

/**
 * 测试文档处理服务连接请求
 */
export interface TestDocProcessorRequest {
  /** 服务配置 */
  config: DocProcessorConfig;
}

/**
 * 上传到数据源后的响应
 */
export interface UploadedFile {
  /** 完整对象路径 */
  key: string;
  /** 文件名（不含路径） */
  name: string;
  /** 字节数 */
  size: number;
}

/**
 * 创建用户请求
 */
export interface UserCreate {
  /**
     * 用户名
     * @minLength 1
     * @maxLength 100
     */
  name: string;
  /** 邮箱 */
  email: string;
  /**
     * 密码
     * @minLength 8
     * @maxLength 100
     */
  password: string;
  /** 所属租户ID(null=平台管理员) */
  tenant_id?: number | null;
  /** 用户角色 */
  role?: UserRole;
  /** 管理的站点ID列表 */
  managed_site_ids?: number[];
  /** 头像URL */
  avatar_url?: string | null;
}

/**
 * 邀请用户请求
 */
export interface UserInvite {
  /** 邮箱 */
  email: string;
  /** 所属租户ID(null=平台管理员) */
  tenant_id?: number | null;
  /** 用户角色 */
  role?: UserRole;
  /** 管理的站点ID列表 */
  managed_site_ids?: number[];
}

/**
 * 用户登录请求
 */
export interface UserLogin {
  /** 邮箱 */
  email: string;
  /** 密码 */
  password: string;
}

/**
 * 用户响应
 */
export interface UserResponse {
  id: number;
  name: string;
  email: string;
  role: UserRole;
  managed_site_ids: number[];
  status: UserStatus;
  avatar_url?: string | null;
  last_login_at?: string | null;
  last_login_ip?: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * 用户登录响应
 */
export interface UserLoginResponse {
  /** 访问令牌 */
  token: string;
  /** 用户信息 */
  user: UserResponse;
}

/**
 * 更新用户请求
 */
export interface UserUpdate {
  /** 用户名 */
  name?: string | null;
  /** 邮箱 */
  email?: string | null;
  /** 用户角色 */
  role?: UserRole | null;
  /** 管理的站点ID列表 */
  managed_site_ids?: number[] | null;
  /** 用户状态 */
  status?: UserStatus | null;
  /** 头像URL */
  avatar_url?: string | null;
}

/**
 * 更新用户密码请求
 */
export interface UserUpdatePassword {
  /** 旧密码 */
  old_password: string;
  /**
     * 新密码
     * @minLength 8
     * @maxLength 100
     */
  new_password: string;
}

/**
 * 向量检索请求
 */
export interface VectorRetrieveRequest {
  /** 检索查询语句 */
  query: string;
  /** 返回结果数量 */
  k?: number;
  /** 相似度阈值 */
  threshold?: number;
  /** 过滤器 (可选) */
  filter?: VectorRetrieveFilter | null;
  /** 是否启用重排序 */
  enable_rerank?: boolean;
  /** 重排序后返回的数量 */
  rerank_k?: number;
}

/**
 * 元数据
 */
export type VectorRetrieveResponseMetadata = { [key: string]: unknown };

/**
 * 向量检索响应
 */
export interface VectorRetrieveResponse {
  /** 文档片段内容 */
  content: string;
  /** 检索得分 (相似度) */
  score: number;
  /** 原始检索得分 (重排序前) */
  original_score?: number | null;
  /** 文档 ID */
  document_id: number;
  /** 文档标题 */
  document_title?: string | null;
  /** 元数据 */
  metadata?: VectorRetrieveResponseMetadata;
}

/**
 * 向量检索结果集
 */
export interface VectorRetrieveResult {
  /** 检索结果列表 */
  list: VectorRetrieveResponse[];
}

/**
 * 向量化请求
 */
export interface VectorizeRequest {
  /**
     * 要向量化的文档ID列表
     * @minItems 1
     */
  document_ids: number[];
}

/**
 * 向量化响应
 */
export interface VectorizeResponse {
  /** 成功排队的文档数 */
  success_count: number;
  /** 失败的文档数 */
  failed_count: number;
  /** 已排队的文档ID列表 */
  document_ids: number[];
}

/**
 * 客户端验证站点密码请求
 */
export interface VerifyPasswordRequest {
  /**
     * @minLength 1
     * @maxLength 64
     */
  password: string;
}

/**
 * 客户端验证站点密码响应
 */
export interface VerifyPasswordResponse {
  access_token: string;
  /** 过期时间 (秒) */
  expires_in: number;
}

export type ListAdminSitesParams = {
page?: number;
size?: number;
/**
 * 是否分页，0=返回全部，1=分页
 */
is_pager?: number;
status?: string | null;
};

export type ListAdminDocumentsParams = {
page?: number;
size?: number;
/**
 * 是否分页，0=返回全部，1=分页
 */
is_pager?: number;
/**
 * 站点ID
 */
site_id?: number | null;
/**
 * 合集ID
 */
collection_id?: number | null;
/**
 * 状态过滤: published, draft
 */
status?: string | null;
/**
 * 向量化状态过滤: none, outdated, pending, processing, completed, failed
 */
vector_status?: string | null;
/**
 * 搜索关键词
 */
keyword?: string | null;
/**
 * 排序字段: views, created_at, updated_at
 */
order_by?: string | null;
/**
 * 排序方向: asc, desc
 */
order_dir?: string | null;
/**
 * 是否排除文档内容（用于列表展示，提升性能）
 */
exclude_content?: boolean;
};

/**
 * 响应数据
 */
export type GetAdminDocumentChunks200 = { [key: string]: unknown }[] | null;

export type ListAdminTasksParams = {
page?: number;
size?: number;
/**
 * 是否分页，0=返回全部，1=分页
 */
is_pager?: number;
/**
 * 站点ID
 */
site_id?: number | null;
};

export type ListAdminCollectionsParams = {
/**
 * 页码
 * @minimum 1
 */
page?: number;
/**
 * 每页大小
 * @minimum 1
 * @maximum 100
 */
size?: number;
/**
 * 是否分页，0=返回全部，1=分页
 */
is_pager?: number;
/**
 * 父合集ID，为空则获取根合集
 */
parent_id?: number | null;
site_id: number;
};

export type GetAdminCollectionTreeParams = {
/**
 * 树节点类型：不指定则显示合集和文档，'collection'则只显示合集
 */
type?: string | null;
site_id: number;
};

export type ListAdminUsersParams = {
/**
 * 页码
 * @minimum 1
 */
page?: number;
/**
 * 每页数量
 * @minimum 1
 * @maximum 100
 */
size?: number;
/**
 * 是否分页，0=返回全部，1=分页
 */
is_pager?: number;
/**
 * 角色筛选
 */
role?: UserRole | null;
/**
 * 状态筛选
 */
status?: UserStatus | null;
/**
 * 搜索关键词
 */
search?: string | null;
/**
 * 站点ID筛选
 */
site_id?: number | null;
/**
 * 排序字段
 */
order_by?: string;
/**
 * 排序方向
 */
order_dir?: ListAdminUsersOrderDir;
};

export type ListAdminUsersOrderDir = typeof ListAdminUsersOrderDir[keyof typeof ListAdminUsersOrderDir];


export const ListAdminUsersOrderDir = {
  asc: 'asc',
  desc: 'desc',
} as const;

/**
 * 响应数据
 */
export type DeleteAdminUser200 = { [key: string]: unknown } | null;

/**
 * 响应数据
 */
export type UpdateAdminUserPassword200 = { [key: string]: unknown } | null;

export type GetAdminAiConfigParams = {
scope?: GetAdminAiConfigScope;
};

export type GetAdminAiConfigScope = typeof GetAdminAiConfigScope[keyof typeof GetAdminAiConfigScope];


export const GetAdminAiConfigScope = {
  platform: 'platform',
  tenant: 'tenant',
} as const;

export type UpdateAdminAiConfigParams = {
scope?: UpdateAdminAiConfigScope;
};

export type UpdateAdminAiConfigScope = typeof UpdateAdminAiConfigScope[keyof typeof UpdateAdminAiConfigScope];


export const UpdateAdminAiConfigScope = {
  platform: 'platform',
  tenant: 'tenant',
} as const;

export type DeleteAdminConfigParams = {
scope?: DeleteAdminConfigScope;
};

export type DeleteAdminConfigScope = typeof DeleteAdminConfigScope[keyof typeof DeleteAdminConfigScope];


export const DeleteAdminConfigScope = {
  platform: 'platform',
  tenant: 'tenant',
} as const;

/**
 * 响应数据
 */
export type DeleteAdminConfig200 = { [key: string]: unknown } | null;

export type TestModelConnectionParams = {
scope?: TestModelConnectionScope;
};

export type TestModelConnectionScope = typeof TestModelConnectionScope[keyof typeof TestModelConnectionScope];


export const TestModelConnectionScope = {
  platform: 'platform',
  tenant: 'tenant',
} as const;

/**
 * 响应数据
 */
export type TestModelConnection200 = { [key: string]: unknown } | null;

export type GetAdminDocProcessorConfigParams = {
scope?: GetAdminDocProcessorConfigScope;
};

export type GetAdminDocProcessorConfigScope = typeof GetAdminDocProcessorConfigScope[keyof typeof GetAdminDocProcessorConfigScope];


export const GetAdminDocProcessorConfigScope = {
  platform: 'platform',
  tenant: 'tenant',
} as const;

export type UpdateAdminDocProcessorConfigParams = {
scope?: UpdateAdminDocProcessorConfigScope;
};

export type UpdateAdminDocProcessorConfigScope = typeof UpdateAdminDocProcessorConfigScope[keyof typeof UpdateAdminDocProcessorConfigScope];


export const UpdateAdminDocProcessorConfigScope = {
  platform: 'platform',
  tenant: 'tenant',
} as const;

export type TestDocProcessorConnectionParams = {
scope?: TestDocProcessorConnectionScope;
};

export type TestDocProcessorConnectionScope = typeof TestDocProcessorConnectionScope[keyof typeof TestDocProcessorConnectionScope];


export const TestDocProcessorConnectionScope = {
  platform: 'platform',
  tenant: 'tenant',
} as const;

/**
 * 响应数据
 */
export type TestDocProcessorConnection200 = { [key: string]: unknown } | null;

export type GetAdminSiteStatsParams = {
/**
 * 站点ID
 */
site_id: number;
};

export type UploadAdminFileParams = {
/**
 * 存储文件夹
 */
folder?: string;
};

/**
 * 响应数据
 */
export type UploadAdminFile200 = { [key: string]: unknown } | null;

export type BatchUploadAdminFilesParams = {
/**
 * 存储文件夹
 */
folder?: string;
};

/**
 * 响应数据
 */
export type BatchUploadAdminFiles200 = { [key: string]: unknown } | null;

export type ListAdminFilesParams = {
/**
 * 文件路径前缀
 */
prefix?: string;
/**
 * 是否递归列出
 */
recursive?: boolean;
/**
 * 页码
 * @minimum 1
 */
page?: number;
/**
 * 每页数量
 * @minimum 1
 * @maximum 100
 */
size?: number;
/**
 * 是否分页，0=返回全部，1=分页
 */
is_pager?: number;
};

/**
 * 响应数据
 */
export type GetAdminFileInfo200 = { [key: string]: unknown } | null;

export type GetAdminPresignedUrlParams = {
/**
 * URL 有效期（小时）
 * @minimum 1
 * @maximum 168
 */
expires_hours?: number;
};

/**
 * 响应数据
 */
export type GetAdminPresignedUrl200 = { [key: string]: unknown } | null;

/**
 * 响应数据
 */
export type GetAdminCacheStats200 = { [key: string]: unknown } | null;

/**
 * 响应数据
 */
export type ClearAdminCache200 = { [key: string]: unknown } | null;

/**
 * 响应数据
 */
export type GetSystemInfo200 = { [key: string]: unknown } | null;

export type BrowseDataSourceParams = {
/**
 * 浏览路径前缀
 */
prefix?: string;
};

export type DeleteDataSourceFileParams = {
/**
 * 完整文件路径
 */
key: string;
};

/**
 * 响应数据
 */
export type ImportFromDataSource200 = { [key: string]: unknown }[] | null;

export type ListAdminTenantsParams = {
/**
 * 页码
 * @minimum 1
 */
page?: number;
/**
 * 每页数量
 * @minimum 1
 * @maximum 100
 */
size?: number;
/**
 * 搜索关键词
 */
keyword?: string | null;
/**
 * 是否分页，0=返回全部，1=分页
 */
is_pager?: number;
};

export type EeAdminAnalyticsOverviewParams = {
/**
 * @minimum 1
 * @maximum 90
 */
days?: number;
};

export type EeAdminListChatSessionsParams = {
/**
 * 搜索关键词
 */
keyword?: string | null;
/**
 * 搜索范围：all=全部，text=标题或最后消息，thread_id=会话ID，member_id=访客标识
 */
search_field?: EeAdminListChatSessionsSearchField;
/**
 * 来源渠道过滤：web_chat/wecom_kefu/wecom_app/wecom_smart/dingtalk_app/feishu_app
 */
source?: string | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
size?: number;
};

export type EeAdminListChatSessionsSearchField = typeof EeAdminListChatSessionsSearchField[keyof typeof EeAdminListChatSessionsSearchField];


export const EeAdminListChatSessionsSearchField = {
  all: 'all',
  text: 'text',
  thread_id: 'thread_id',
  member_id: 'member_id',
} as const;

/**
 * 响应数据
 */
export type EeAdminDeleteChatSession200 = { [key: string]: unknown } | null;

export type GetAdminFeedbackStatsParams = {
/**
 * 站点 ID
 */
site_id: number;
};

export type GetAdminFeedbackListParams = {
/**
 * 站点 ID
 */
site_id: number;
/**
 * 只看 up 或 down，默认全部
 */
rating?: 'up' | 'down' | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
size?: number;
};

